// âœ¨ æ–°å¢ - æ”»å‡»èƒ½åŠ›åŸºç±»å®ç°
// Copyright Epic Games, Inc. All Rights Reserved.

/**
 * @file SG_GameplayAbility_Attack.cpp
 * @brief æ”»å‡»èƒ½åŠ›åŸºç±»å®ç°
 */

#include "AbilitySystem/Abilities/SG_GameplayAbility_Attack.h"
#include "AbilitySystem/SG_AbilitySystemComponent.h"
#include "AbilitySystem/SG_AttributeSet.h"
#include "Units/SG_UnitsBase.h"
#include "Debug/SG_LogCategories.h"
#include "Animation/AnimMontage.h"
#include "Animation/AnimInstance.h"
#include "Kismet/GameplayStatics.h"
#include "GameplayEffect.h"
#include "Engine/OverlapResult.h"
#include "AbilitySystemGlobals.h"
#include "DrawDebugHelpers.h"
#include "Buildings/SG_BuildingAttributeSet.h"
#include "Buildings/SG_MainCityBase.h"
#include "Components/BoxComponent.h"  // âœ¨ æ–°å¢ - å¿…é¡»åŒ…å«å®Œæ•´å®šä¹‰
#include "Abilities/Tasks/AbilityTask_WaitGameplayEvent.h"

// ========== æ„é€ å‡½æ•° ==========

/**
 * @brief æ„é€ å‡½æ•°
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - è®¾ç½®æŠ€èƒ½æ ‡ç­¾
 * - é…ç½®å®ä¾‹åŒ–ç­–ç•¥
 * - é…ç½®ç½‘ç»œæ‰§è¡Œç­–ç•¥
 */
USG_GameplayAbility_Attack::USG_GameplayAbility_Attack()
{
	// è®¾ç½®æŠ€èƒ½çš„é»˜è®¤æ ‡ç­¾
	// Tag "Ability.Attack" ç”¨äºæ ‡è¯†æ”»å‡»ç±»æŠ€èƒ½
	FGameplayTag AttackTag = FGameplayTag::RequestGameplayTag(FName("Ability.Attack"), false);
	if (AttackTag.IsValid())
	{
		FGameplayTagContainer Tags;
		Tags.AddTag(AttackTag);
		SetAssetTags(Tags);
		
		UE_LOG(LogSGGameplay, Log, TEXT("âœ“ æ”»å‡»èƒ½åŠ›æ ‡ç­¾è®¾ç½®æˆåŠŸï¼š%s"), *AttackTag.ToString());
	}
	else
	{
		UE_LOG(LogSGGameplay, Warning, TEXT("âš ï¸ GameplayTag 'Ability.Attack' æœªæ‰¾åˆ°"));
		UE_LOG(LogSGGameplay, Warning, TEXT("  è¯·åœ¨ Config/DefaultGameplayTags.ini ä¸­é…ç½®"));
	}
	
	// è®¾ç½®æŠ€èƒ½å®ä¾‹åŒ–ç­–ç•¥
	// InstancedPerActorï¼šæ¯ä¸ª Actor åªæœ‰ä¸€ä¸ªå®ä¾‹ï¼ˆæ€§èƒ½æ›´å¥½ï¼‰
	InstancingPolicy = EGameplayAbilityInstancingPolicy::InstancedPerActor;
	
	// è®¾ç½®æŠ€èƒ½çš„ç½‘ç»œæ‰§è¡Œç­–ç•¥
	// LocalPredictedï¼šå®¢æˆ·ç«¯é¢„æµ‹ï¼ŒæœåŠ¡å™¨ç¡®è®¤
	NetExecutionPolicy = EGameplayAbilityNetExecutionPolicy::LocalPredicted;

	// âœ¨ æ–°å¢ - åˆå§‹åŒ–é»˜è®¤çš„æ”»å‡»é€šçŸ¥åˆ—è¡¨
	AttackNotifyNames.Add(TEXT("AttackHit"));
}

// ========== æ¿€æ´»æŠ€èƒ½ ==========

/**
 * @brief æ¿€æ´»èƒ½åŠ›
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - æ’­æ”¾æ”»å‡»åŠ¨ç”»
 * - ç»‘å®šåŠ¨ç”»é€šçŸ¥å›è°ƒ
 * - å¦‚æœæ²¡æœ‰åŠ¨ç”»ï¼Œç›´æ¥æ‰§è¡Œæ”»å‡»åˆ¤å®š
 */
void USG_GameplayAbility_Attack::ActivateAbility(
	const FGameplayAbilitySpecHandle Handle,
	const FGameplayAbilityActorInfo* ActorInfo,
	const FGameplayAbilityActivationInfo ActivationInfo,
	const FGameplayEventData* TriggerEventData
)
{
	Super::ActivateAbility(Handle, ActorInfo, ActivationInfo, TriggerEventData);

	// âœ¨ æ–°å¢ - é‡ç½®æ”»å‡»æ®µæ•°è®¡æ•°å™¨
	CurrentAttackIndex = 0;

	UE_LOG(LogSGGameplay, Log, TEXT("========== æ”»å‡»æŠ€èƒ½æ¿€æ´» =========="));
	UE_LOG(LogSGGameplay, Log, TEXT("  æ–½æ”¾è€…ï¼š%s"), 
		ActorInfo->AvatarActor.IsValid() ? *ActorInfo->AvatarActor->GetName() : TEXT("None"));
	UE_LOG(LogSGGameplay, Log, TEXT("  æ”»å‡»ç±»å‹ï¼š%s"), 
		*UEnum::GetValueAsString(AttackType));
	UE_LOG(LogSGGameplay, Log, TEXT("  æ”»å‡»æ®µæ•°ï¼š%d"), AttackNotifyNames.Num());

	if (AttackMontage && ActorInfo->AvatarActor.IsValid())
	{
		if (ACharacter* Character = Cast<ACharacter>(ActorInfo->AvatarActor.Get()))
		{
			if (UAnimInstance* AnimInstance = Character->GetMesh()->GetAnimInstance())
			{
				// âœ¨ æ–°å¢ - è·å–æ”»å‡»é€Ÿåº¦å€ç‡
				float PlayRate = 1.0f;
				if (const USG_AbilitySystemComponent* SGASC = Cast<USG_AbilitySystemComponent>(GetAbilitySystemComponentFromActorInfo()))
				{
					if (const USG_AttributeSet* AttributeSet = SGASC->GetSet<USG_AttributeSet>())
					{
						PlayRate = AttributeSet->GetAttackSpeed();
					}
				}

				// ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨æ”»å‡»é€Ÿåº¦æ’­æ”¾è’™å¤ªå¥‡
				// å¦‚æœ PlayRate æ˜¯ 2.0ï¼ŒåŠ¨ç”»æ’­æ”¾é€Ÿåº¦å°±æ˜¯ 2 å€
				float MontageLength = AnimInstance->Montage_Play(AttackMontage, PlayRate);
				
			
				// ç»‘å®šä¼ ç»Ÿçš„ AnimNotify å›è°ƒï¼ˆå…¼å®¹æ—§çš„é…ç½®ï¼‰
				AnimInstance->OnPlayMontageNotifyBegin.AddDynamic(
					this, 
					&USG_GameplayAbility_Attack::OnMontageNotifyBegin
				);
				// âœ¨ æ–°å¢ - ç›‘å¬æ”»å‡»å‘½ä¸­äº‹ä»¶ (é…åˆæ–°çš„ SG_ANS_MeleeDetection ä½¿ç”¨)
				// ç›‘å¬ Tag: Event.Attack.Hit
				UAbilityTask_WaitGameplayEvent* WaitEventTask = UAbilityTask_WaitGameplayEvent::WaitGameplayEvent(
					this,
					FGameplayTag::RequestGameplayTag(FName("Event.Attack.Hit")),
					nullptr, // OptionalExternalTarget
					false,   // OnlyTriggerOnce (è®¾ä¸º false ä»¥ä¾¿ä¸€æ¬¡æŒ¥å‡»å‡»ä¸­å¤šä¸ªæ•Œäºº)
					false    // OnlyMatchExact
				);

				if (WaitEventTask)
				{
					// ç»‘å®šåˆ°æˆ‘ä»¬æ–°å†™çš„ OnDamageGameplayEvent å‡½æ•°
					WaitEventTask->EventReceived.AddDynamic(this, &USG_GameplayAbility_Attack::OnDamageGameplayEvent);
					WaitEventTask->ReadyForActivation();
					UE_LOG(LogSGGameplay, Verbose, TEXT("  âœ“ å·²å¯åŠ¨ WaitGameplayEvent ç›‘å¬ä»»åŠ¡"));
				}

				UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ æ”»å‡»åŠ¨ç”»å·²æ’­æ”¾ï¼š%s"), *AttackMontage->GetName());
				// ğŸ”§ ä¿®æ”¹ - æ ¹æ®å€ç‡è®¡ç®—å®é™…æŒç»­æ—¶é—´
				// Montage_Play è¿”å›çš„æ˜¯åŸå§‹é•¿åº¦ï¼Œå®é™…æ’­æ”¾æ—¶é—´ = åŸå§‹é•¿åº¦ / æ’­æ”¾é€Ÿç‡
				float ActualDuration = (PlayRate > 0.0f) ? (MontageLength / PlayRate) : MontageLength;
				UE_LOG(LogSGGameplay, Log, TEXT("  å®é™…åŠ¨ç”»æ—¶é•¿ï¼š%.2f ç§’"), ActualDuration);
				
				// è®¾ç½®å®šæ—¶å™¨ï¼Œç¡®ä¿èƒ½åŠ›åœ¨åŠ¨ç”»ç»“æŸåç»“æŸ
				FTimerHandle TimerHandle;
				FTimerDelegate TimerDelegate;
				TimerDelegate.BindLambda([this, Handle, ActorInfo, ActivationInfo, AnimInstance]()
				{
					if (AnimInstance)
					{
						AnimInstance->OnPlayMontageNotifyBegin.RemoveDynamic(
							this, 
							&USG_GameplayAbility_Attack::OnMontageNotifyBegin
						);
						UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ è§£ç»‘åŠ¨ç”»é€šçŸ¥å›è°ƒ"));
					}
					
					UE_LOG(LogSGGameplay, Log, TEXT("  â° æ”»å‡»åŠ¨ç”»ç»“æŸï¼Œç»“æŸèƒ½åŠ›"));
					EndAbility(Handle, ActorInfo, ActivationInfo, true, false);
				});
				
				// ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨è®¡ç®—åçš„å®é™…æ—¶é•¿è®¾ç½®å®šæ—¶å™¨
				ActorInfo->AvatarActor->GetWorldTimerManager().SetTimer(
					TimerHandle,
					TimerDelegate,
					ActualDuration, // ä½¿ç”¨ä¿®æ­£åçš„æ—¶é—´
					false
				);
			}
			else
			{
				UE_LOG(LogSGGameplay, Error, TEXT("  âŒ æ— æ³•è·å– AnimInstance"));
				EndAbility(Handle, ActorInfo, ActivationInfo, true, false);
			}
		}
		else
		{
			UE_LOG(LogSGGameplay, Error, TEXT("  âŒ æ–½æ”¾è€…ä¸æ˜¯ Character ç±»å‹"));
			EndAbility(Handle, ActorInfo, ActivationInfo, true, false);
		}
	}
	else
	{
		UE_LOG(LogSGGameplay, Warning, TEXT("  âš ï¸ æ— æ”»å‡»åŠ¨ç”»ï¼Œç›´æ¥æ‰§è¡Œæ”»å‡»åˆ¤å®š"));
		PerformAttack();
		EndAbility(Handle, ActorInfo, ActivationInfo, true, false);
	}

	UE_LOG(LogSGGameplay, Log, TEXT("========================================"));
}

// ========== ç»“æŸæŠ€èƒ½ ==========

/**
 * @brief ç»“æŸèƒ½åŠ›
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - æ¸…ç†èµ„æº
 * - è°ƒç”¨çˆ¶ç±»ç»“æŸ
 */
void USG_GameplayAbility_Attack::EndAbility(
	const FGameplayAbilitySpecHandle Handle,
	const FGameplayAbilityActorInfo* ActorInfo,
	const FGameplayAbilityActivationInfo ActivationInfo,
	bool bReplicateEndAbility,
	bool bWasCancelled
)
{
	// âœ¨ æ–°å¢ - é‡ç½®æ”»å‡»æ®µæ•°è®¡æ•°å™¨
	CurrentAttackIndex = 0;

	UE_LOG(LogSGGameplay, Verbose, TEXT("æ”»å‡»æŠ€èƒ½ç»“æŸ (å–æ¶ˆ: %s)"), 
		bWasCancelled ? TEXT("æ˜¯") : TEXT("å¦"));

	Super::EndAbility(Handle, ActorInfo, ActivationInfo, bReplicateEndAbility, bWasCancelled);
}

// ========== åŠ¨ç”»é€šçŸ¥å›è°ƒ ==========

/**
 * @brief åŠ¨ç”»é€šçŸ¥å›è°ƒ
 * @param NotifyName é€šçŸ¥åç§°
 * @param BranchingPointPayload åˆ†æ”¯ç‚¹è½½è·
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - åœ¨åŠ¨ç”»æ’­æ”¾åˆ°ç‰¹å®šå¸§æ—¶è§¦å‘
 * - æ£€æŸ¥é€šçŸ¥åç§°æ˜¯å¦åŒ¹é…
 * - æ‰§è¡Œæ”»å‡»åˆ¤å®š
 */
void USG_GameplayAbility_Attack::OnMontageNotifyBegin(
	FName NotifyName,
	const FBranchingPointNotifyPayload& BranchingPointPayload
)
{
	// âœ¨ æ–°å¢ - æ£€æŸ¥é€šçŸ¥åç§°æ˜¯å¦åœ¨åˆ—è¡¨ä¸­
	int32 NotifyIndex = AttackNotifyNames.IndexOfByKey(NotifyName);
	
	if (NotifyIndex != INDEX_NONE)
	{
		UE_LOG(LogSGGameplay, Log, TEXT("  ğŸ¯ æ”»å‡»åˆ¤å®šå¸§è§¦å‘ (é€šçŸ¥: %s, ç¬¬ %d æ®µ)"), 
			*NotifyName.ToString(), NotifyIndex + 1);
		
		// âœ¨ æ–°å¢ - è·å–å½“å‰æ®µçš„ä¼¤å®³å€ç‡
		float CurrentDamageMultiplier = DamageMultiplier;
		if (AttackDamageMultipliers.IsValidIndex(NotifyIndex))
		{
			CurrentDamageMultiplier = AttackDamageMultipliers[NotifyIndex];
			UE_LOG(LogSGGameplay, Log, TEXT("    ä½¿ç”¨ç¬¬ %d æ®µä¼¤å®³å€ç‡ï¼š%.2f"), 
				NotifyIndex + 1, CurrentDamageMultiplier);
		}
		else
		{
			UE_LOG(LogSGGameplay, Log, TEXT("    ä½¿ç”¨é»˜è®¤ä¼¤å®³å€ç‡ï¼š%.2f"), CurrentDamageMultiplier);
		}
		
		// âœ¨ æ–°å¢ - ä¸´æ—¶ä¿®æ”¹ä¼¤å®³å€ç‡
		float OriginalMultiplier = DamageMultiplier;
		DamageMultiplier = CurrentDamageMultiplier;
		
		// æ‰§è¡Œæ”»å‡»åˆ¤å®š
		PerformAttack();
		
		// âœ¨ æ–°å¢ - æ¢å¤åŸå§‹å€ç‡
		DamageMultiplier = OriginalMultiplier;
		
		// å¢åŠ æ”»å‡»æ®µæ•°è®¡æ•°
		CurrentAttackIndex++;
	}
	else
	{
		UE_LOG(LogSGGameplay, Verbose, TEXT("  AnimNotify: %s (ä¸åœ¨æ”»å‡»é€šçŸ¥åˆ—è¡¨ä¸­)"), 
			*NotifyName.ToString());
	}
}

// ========== æ‰§è¡Œæ”»å‡»åˆ¤å®š ==========

/**
 * @brief æ‰§è¡Œæ”»å‡»åˆ¤å®š
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - æŸ¥æ‰¾èŒƒå›´å†…çš„ç›®æ ‡
 * - å¯¹æ¯ä¸ªç›®æ ‡åº”ç”¨ä¼¤å®³
 * - è§¦å‘è“å›¾äº‹ä»¶
 */
void USG_GameplayAbility_Attack::PerformAttack()
{
	// è¾“å‡ºæ—¥å¿—ï¼šæ‰§è¡Œæ”»å‡»åˆ¤å®š
	UE_LOG(LogSGGameplay, Log, TEXT("========== æ‰§è¡Œæ”»å‡»åˆ¤å®š =========="));

	// æŸ¥æ‰¾èŒƒå›´å†…çš„ç›®æ ‡
	TArray<AActor*> Targets;
	int32 TargetCount = FindTargetsInRange(Targets);

	// è¾“å‡ºæ—¥å¿—ï¼šæ‰¾åˆ°çš„ç›®æ ‡æ•°é‡
	UE_LOG(LogSGGameplay, Log, TEXT("  æ‰¾åˆ°ç›®æ ‡æ•°é‡ï¼š%d"), TargetCount);

	// å¦‚æœæ‰¾åˆ°ç›®æ ‡ï¼Œåº”ç”¨ä¼¤å®³
	if (TargetCount > 0)
	{
		// éå†æ‰€æœ‰ç›®æ ‡
		for (int32 i = 0; i < Targets.Num(); ++i)
		{
			AActor* Target = Targets[i];
			if (Target)
			{
				// è¾“å‡ºæ—¥å¿—ï¼šæ”»å‡»ç›®æ ‡
				UE_LOG(LogSGGameplay, Log, TEXT("  [%d] æ”»å‡»ç›®æ ‡ï¼š%s"), i + 1, *Target->GetName());
				
				// åº”ç”¨ä¼¤å®³
				ApplyDamageToTarget(Target);
			}
		}

		// è§¦å‘è“å›¾äº‹ä»¶ï¼šæ”»å‡»å‘½ä¸­
		OnAttackHit(Targets);
	}
	else
	{
		// è¾“å‡ºæ—¥å¿—ï¼šæœªæ‰¾åˆ°ç›®æ ‡
		UE_LOG(LogSGGameplay, Warning, TEXT("  âš ï¸ æœªæ‰¾åˆ°ä»»ä½•ç›®æ ‡"));
	}

	// è¾“å‡ºæ—¥å¿—ï¼šæ”»å‡»åˆ¤å®šç»“æŸ
	UE_LOG(LogSGGameplay, Log, TEXT("========================================"));
}

// ========== æŸ¥æ‰¾èŒƒå›´å†…çš„ç›®æ ‡ ==========

/**
 * @brief æŸ¥æ‰¾èŒƒå›´å†…çš„ç›®æ ‡
 * @param OutTargets è¾“å‡ºï¼šæ‰¾åˆ°çš„ç›®æ ‡åˆ—è¡¨
 * @return æ‰¾åˆ°çš„ç›®æ ‡æ•°é‡
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - æ ¹æ®æ”»å‡»ç±»å‹æ‰§è¡Œä¸åŒçš„æ£€æµ‹
 * - è¿‘æˆ˜ï¼šçƒå½¢èŒƒå›´æ£€æµ‹
 * - è¿œç¨‹ï¼šå°„çº¿æ£€æµ‹
 * - æŠ€èƒ½ï¼šç”±å­ç±»å®ç°
 */
int32 USG_GameplayAbility_Attack::FindTargetsInRange(TArray<AActor*>& OutTargets)
{
	OutTargets.Empty();

	AActor* AvatarActor = GetAvatarActorFromActorInfo();
	if (!AvatarActor)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("FindTargetsInRange å¤±è´¥ï¼šæ–½æ”¾è€…ä¸ºç©º"));
		return 0;
	}

	ASG_UnitsBase* SourceUnit = Cast<ASG_UnitsBase>(AvatarActor);
	if (!SourceUnit)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("FindTargetsInRange å¤±è´¥ï¼šæ–½æ”¾è€…ä¸æ˜¯ SG_UnitsBase"));
		return 0;
	}

	FGameplayTag MyFaction = SourceUnit->FactionTag;
	float AttackRange = GetAttackRange();
	FVector SourceLocation = AvatarActor->GetActorLocation();

	UE_LOG(LogSGGameplay, Verbose, TEXT("  æŸ¥æ‰¾èŒƒå›´ï¼š%.1f"), AttackRange);

	switch (AttackType)
	{
	case ESGAttackAbilityType::Melee:
		{
			// ========== è¿‘æˆ˜æ”»å‡»ï¼šçƒå½¢èŒƒå›´æ£€æµ‹ ==========
			
			FCollisionShape CollisionShape = FCollisionShape::MakeSphere(AttackRange);
			FCollisionQueryParams QueryParams;
			QueryParams.AddIgnoredActor(AvatarActor);

			TArray<FOverlapResult> OverlapResults;
			bool bHit = GetWorld()->OverlapMultiByChannel(
				OverlapResults,
				SourceLocation,
				FQuat::Identity,
				ECC_Pawn,
				CollisionShape,
				QueryParams
			);

			if (bShowAttackDetection)
			{
				DrawMeleeAttackDetection(SourceLocation, AttackRange, bHit);
			}

			if (bHit)
			{
				for (const FOverlapResult& Result : OverlapResults)
				{
					AActor* HitActor = Result.GetActor();
					if (!HitActor)
					{
						continue;
					}

					// ========== æ£€æŸ¥æ˜¯å¦æ˜¯æ•Œæ–¹å•ä½ ==========
					ASG_UnitsBase* TargetUnit = Cast<ASG_UnitsBase>(HitActor);
					if (TargetUnit && TargetUnit->FactionTag != MyFaction)
					{
						OutTargets.AddUnique(HitActor);
						UE_LOG(LogSGGameplay, Verbose, TEXT("    æ‰¾åˆ°æ•Œæ–¹å•ä½ï¼š%s"), *HitActor->GetName());
						continue;
					}

					// ========== ğŸ”§ ä¿®å¤ - æ£€æŸ¥æ˜¯å¦æ˜¯ä¸»åŸçš„æ”»å‡»æ£€æµ‹ç›’ ==========
					UPrimitiveComponent* HitComponent = Result.GetComponent();
					if (HitComponent)
					{
						AActor* ComponentOwner = HitComponent->GetOwner();
						ASG_MainCityBase* MainCity = Cast<ASG_MainCityBase>(ComponentOwner);
						
						if (MainCity && MainCity->FactionTag != MyFaction)
						{
							UBoxComponent* HitBoxComponent = Cast<UBoxComponent>(HitComponent);
							UBoxComponent* MainCityDetectionBox = MainCity->GetAttackDetectionBox();
							
							if (HitBoxComponent && MainCityDetectionBox && HitBoxComponent == MainCityDetectionBox)
							{
								// âœ¨ æ–°å¢ - éªŒè¯è·ç¦»ï¼ˆä½¿ç”¨ä¸è£…é¥°å™¨ç›¸åŒçš„é€»è¾‘ï¼‰
								FVector BoxCenter = MainCityDetectionBox->GetComponentLocation();
								FVector BoxExtent = MainCityDetectionBox->GetScaledBoxExtent();
								float BoxRadius = FMath::Max3(BoxExtent.X, BoxExtent.Y, BoxExtent.Z);
								
								float DistanceToCenter = FVector::Dist(SourceLocation, BoxCenter);
								float DistanceToSurface = FMath::Max(0.0f, DistanceToCenter - BoxRadius);
								
								if (DistanceToSurface <= AttackRange)
								{
									OutTargets.AddUnique(MainCity);
									UE_LOG(LogSGGameplay, Log, TEXT("    æ‰¾åˆ°æ•Œæ–¹ä¸»åŸï¼ˆé€šè¿‡æ”»å‡»æ£€æµ‹ç›’ï¼‰ï¼š%s"), 
										*MainCity->GetName());
									UE_LOG(LogSGGameplay, Log, TEXT("      åˆ°è¡¨é¢è·ç¦»ï¼š%.2f / æ”»å‡»èŒƒå›´ï¼š%.2f"), 
										DistanceToSurface, AttackRange);
								}
								else
								{
									UE_LOG(LogSGGameplay, Warning, TEXT("    æ£€æµ‹åˆ°ä¸»åŸä½†è·ç¦»ä¸è¶³ï¼š%.2f > %.2f"), 
										DistanceToSurface, AttackRange);
								}
								
								continue;
							}
						}
					}
				}
			}
		}
		break;

	case ESGAttackAbilityType::Ranged:
		{
			// ========== è¿œç¨‹æ”»å‡»ï¼šå°„çº¿æ£€æµ‹ ==========
			
			FVector StartLocation = AvatarActor->GetActorLocation();
			FVector ForwardVector = AvatarActor->GetActorForwardVector();
			FVector EndLocation = StartLocation + ForwardVector * AttackRange;

			FCollisionQueryParams QueryParams;
			QueryParams.AddIgnoredActor(AvatarActor);

			FHitResult HitResult;
			bool bHit = GetWorld()->LineTraceSingleByChannel(
				HitResult,
				StartLocation,
				EndLocation,
				ECC_Pawn,
				QueryParams
			);

			if (bShowAttackDetection)
			{
				FVector HitLocation = bHit ? HitResult.Location : EndLocation;
				DrawRangedAttackDetection(StartLocation, EndLocation, bHit, HitLocation);
			}

			if (bHit)
			{
				AActor* HitActor = HitResult.GetActor();
				if (HitActor)
				{
					ASG_UnitsBase* TargetUnit = Cast<ASG_UnitsBase>(HitActor);
					if (TargetUnit && TargetUnit->FactionTag != MyFaction)
					{
						OutTargets.AddUnique(HitActor);
						UE_LOG(LogSGGameplay, Verbose, TEXT("    æ‰¾åˆ°æ•Œæ–¹å•ä½ï¼š%s"), *HitActor->GetName());
					}
					
					// ========== ğŸ”§ ä¿®å¤ - æ£€æŸ¥æ˜¯å¦æ˜¯ä¸»åŸçš„æ”»å‡»æ£€æµ‹ç›’ ==========
					UPrimitiveComponent* HitComponent = HitResult.GetComponent();
					if (HitComponent)
					{
						AActor* ComponentOwner = HitComponent->GetOwner();
						ASG_MainCityBase* MainCity = Cast<ASG_MainCityBase>(ComponentOwner);
						
						if (MainCity && MainCity->FactionTag != MyFaction)
						{
							UBoxComponent* HitBoxComponent = Cast<UBoxComponent>(HitComponent);
							UBoxComponent* MainCityDetectionBox = MainCity->GetAttackDetectionBox();
							
							if (HitBoxComponent && MainCityDetectionBox && HitBoxComponent == MainCityDetectionBox)
							{
								// âœ¨ æ–°å¢ - éªŒè¯è·ç¦»
								FVector BoxCenter = MainCityDetectionBox->GetComponentLocation();
								FVector BoxExtent = MainCityDetectionBox->GetScaledBoxExtent();
								float BoxRadius = FMath::Max3(BoxExtent.X, BoxExtent.Y, BoxExtent.Z);
								
								float DistanceToCenter = FVector::Dist(SourceLocation, BoxCenter);
								float DistanceToSurface = FMath::Max(0.0f, DistanceToCenter - BoxRadius);
								
								if (DistanceToSurface <= AttackRange)
								{
									OutTargets.AddUnique(MainCity);
									UE_LOG(LogSGGameplay, Log, TEXT("    æ‰¾åˆ°æ•Œæ–¹ä¸»åŸï¼ˆé€šè¿‡æ”»å‡»æ£€æµ‹ç›’ï¼‰ï¼š%s"), 
										*MainCity->GetName());
									UE_LOG(LogSGGameplay, Log, TEXT("      åˆ°è¡¨é¢è·ç¦»ï¼š%.2f / æ”»å‡»èŒƒå›´ï¼š%.2f"), 
										DistanceToSurface, AttackRange);
								}
								else
								{
									UE_LOG(LogSGGameplay, Warning, TEXT("    æ£€æµ‹åˆ°ä¸»åŸä½†è·ç¦»ä¸è¶³ï¼š%.2f > %.2f"), 
										DistanceToSurface, AttackRange);
								}
							}
						}
					}
				}
			}
		}
		break;

	case ESGAttackAbilityType::Skill:
		{
			UE_LOG(LogSGGameplay, Warning, TEXT("æŠ€èƒ½æ”»å‡»ç±»å‹éœ€è¦åœ¨å­ç±»ä¸­å®ç° FindTargetsInRange"));
		}
		break;
	}

	if (bShowAttackDetection && OutTargets.Num() > 0)
	{
		DrawTargetMarkers(OutTargets);
	}

	return OutTargets.Num();
}

// ========== åº”ç”¨ä¼¤å®³åˆ°ç›®æ ‡ ==========

/**
 * @brief åº”ç”¨ä¼¤å®³åˆ°ç›®æ ‡
 * @param Target ç›®æ ‡ Actor
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - åˆ›å»ºä¼¤å®³ GameplayEffect
 * - è®¾ç½®ä¼¤å®³å€ç‡
 * - åº”ç”¨åˆ°ç›®æ ‡
 */
void USG_GameplayAbility_Attack::ApplyDamageToTarget(AActor* Target)
{
	UE_LOG(LogSGGameplay, Error, TEXT("========================================"));
	UE_LOG(LogSGGameplay, Error, TEXT("ğŸ”¥ ApplyDamageToTarget å¼€å§‹"));
	UE_LOG(LogSGGameplay, Error, TEXT("========================================"));
	// æ£€æŸ¥ç›®æ ‡æ˜¯å¦æœ‰æ•ˆ
	if (!Target)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("ApplyDamageToTarget å¤±è´¥ï¼šç›®æ ‡ä¸ºç©º"));
		return;
	}

	// è·å–ç›®æ ‡çš„ AbilitySystemComponent
	UAbilitySystemComponent* TargetASC = UAbilitySystemGlobals::GetAbilitySystemComponentFromActor(Target);
	if (!TargetASC)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("ApplyDamageToTarget å¤±è´¥ï¼šç›®æ ‡ %s æ²¡æœ‰ ASC"), *Target->GetName());
		return;
	}

	// æ£€æŸ¥ä¼¤å®³ GE æ˜¯å¦æœ‰æ•ˆ
	if (!DamageEffectClass)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("ApplyDamageToTarget å¤±è´¥ï¼šä¼¤å®³ GE æœªè®¾ç½®"));
		return;
	}

	// è·å–æ–½æ”¾è€…çš„ ASC
	UAbilitySystemComponent* SourceASC = GetAbilitySystemComponentFromActorInfo();
	if (!SourceASC)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("ApplyDamageToTarget å¤±è´¥ï¼šæ–½æ”¾è€…æ²¡æœ‰ ASC"));
		return;
	}

	// ========== âœ¨ æ–°å¢ - éªŒè¯ç›®æ ‡çš„ AttributeSet ==========
	UE_LOG(LogSGGameplay, Warning, TEXT("========== éªŒè¯ç›®æ ‡ AttributeSet =========="));
	UE_LOG(LogSGGameplay, Warning, TEXT("  ç›®æ ‡ï¼š%s"), *Target->GetName());
	UE_LOG(LogSGGameplay, Warning, TEXT("  ç›®æ ‡ ASCï¼š%s"), *TargetASC->GetName());
	
	// è·å–ç›®æ ‡çš„ AttributeSet
	const UAttributeSet* TargetAttributeSet = TargetASC->GetAttributeSet(USG_BuildingAttributeSet::StaticClass());
	if (TargetAttributeSet)
	{
		UE_LOG(LogSGGameplay, Warning, TEXT("  âœ“ æ‰¾åˆ° BuildingAttributeSetï¼š%s"), *TargetAttributeSet->GetName());
		
		// æ£€æŸ¥ IncomingDamage å±æ€§
		FGameplayAttribute IncomingDamageAttr = USG_BuildingAttributeSet::GetIncomingDamageAttribute();
		if (IncomingDamageAttr.IsValid())
		{
			UE_LOG(LogSGGameplay, Warning, TEXT("  âœ“ IncomingDamage å±æ€§æœ‰æ•ˆ"));
			UE_LOG(LogSGGameplay, Warning, TEXT("    å±æ€§åç§°ï¼š%s"), *IncomingDamageAttr.GetName());
			UE_LOG(LogSGGameplay, Warning, TEXT("    å±æ€§æ‰€å±ç±»ï¼š%s"), *IncomingDamageAttr.GetAttributeSetClass()->GetName());
		}
		else
		{
			UE_LOG(LogSGGameplay, Error, TEXT("  âŒ IncomingDamage å±æ€§æ— æ•ˆï¼"));
		}
	}
	else
	{
		UE_LOG(LogSGGameplay, Error, TEXT("  âŒ æœªæ‰¾åˆ° BuildingAttributeSetï¼"));
		UE_LOG(LogSGGameplay, Error, TEXT("  ç›®æ ‡å¯èƒ½ä½¿ç”¨äº†é”™è¯¯çš„ AttributeSet ç±»å‹"));
	}
	UE_LOG(LogSGGameplay, Warning, TEXT("========================================"));

	// åˆ›å»º EffectContext
	FGameplayEffectContextHandle EffectContext = SourceASC->MakeEffectContext();
	EffectContext.AddSourceObject(this);

	// åˆ›å»º EffectSpec
	FGameplayEffectSpecHandle SpecHandle = SourceASC->MakeOutgoingSpec(
		DamageEffectClass,
		GetAbilityLevel(),
		EffectContext
	);

	// æ£€æŸ¥ SpecHandle æ˜¯å¦æœ‰æ•ˆ
	if (!SpecHandle.IsValid())
	{
		UE_LOG(LogSGGameplay, Error, TEXT("ApplyDamageToTarget å¤±è´¥ï¼šåˆ›å»º EffectSpec å¤±è´¥"));
		return;
	}

	// è®¾ç½®ä¼¤å®³å€ç‡ï¼ˆSetByCallerï¼‰
	// ä½¿ç”¨ GameplayTag "Data.Damage" ä¼ é€’ä¼¤å®³å€ç‡
	FGameplayTag DamageTag = FGameplayTag::RequestGameplayTag(FName("Data.Damage"), false);
	if (DamageTag.IsValid())
	{
		SpecHandle.Data->SetSetByCallerMagnitude(DamageTag, DamageMultiplier);
		
		// è¾“å‡ºæ—¥å¿—ï¼šåº”ç”¨ä¼¤å®³
		UE_LOG(LogSGGameplay, Verbose, TEXT("    åº”ç”¨ä¼¤å®³ GEï¼Œå€ç‡ï¼š%.2f"), DamageMultiplier);
	}
	else
	{
		UE_LOG(LogSGGameplay, Warning, TEXT("    âš ï¸ Data.Damage æ ‡ç­¾æœªæ‰¾åˆ°ï¼Œä¼¤å®³å€ç‡æœªè®¾ç½®"));
	}

	// ========== æ­¥éª¤10ï¼šåº”ç”¨ GameplayEffect ==========
	UE_LOG(LogSGGameplay, Error, TEXT("========== åº”ç”¨ GE =========="));
	UE_LOG(LogSGGameplay, Error, TEXT("æ–½æ”¾è€… ASCï¼š%s"), *SourceASC->GetName());
	UE_LOG(LogSGGameplay, Error, TEXT("ç›®æ ‡ ASCï¼š%s"), *TargetASC->GetName());
	// åº”ç”¨ GameplayEffect åˆ°ç›®æ ‡
	FActiveGameplayEffectHandle ActiveHandle = SourceASC->ApplyGameplayEffectSpecToTarget(
		*SpecHandle.Data.Get(),
		TargetASC
	);

	// Instant ç±»å‹çš„ GE ä¼šç«‹å³æ‰§è¡Œå¹¶é”€æ¯
	// SpecHandle æœ‰æ•ˆè¯´æ˜ GE åˆ›å»ºå’Œåº”ç”¨è¿‡ç¨‹æ­£å¸¸
	if (SpecHandle.IsValid())
	{
		UE_LOG(LogSGGameplay, Log, TEXT("âœ“ GE åº”ç”¨æˆåŠŸï¼ˆHandle æœ‰æ•ˆï¼‰"));
	}
	else
	{
		UE_LOG(LogSGGameplay, Error, TEXT("âŒ GE åº”ç”¨å¤±è´¥ï¼ˆHandle æ— æ•ˆï¼‰"));
	}

	UE_LOG(LogSGGameplay, Error, TEXT("========================================"));
	UE_LOG(LogSGGameplay, Error, TEXT("ğŸ”¥ ApplyDamageToTarget ç»“æŸ"));
	UE_LOG(LogSGGameplay, Error, TEXT("========================================"));
}

// ========== è·å–æ”»å‡»èŒƒå›´ ==========

/**
 * @brief è·å–æ”»å‡»èŒƒå›´
 * @return æ”»å‡»èŒƒå›´ï¼ˆå˜ç±³ï¼‰
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - ä»æ–½æ”¾è€…çš„ AttributeSet è¯»å–æ”»å‡»èŒƒå›´
 * - å¦‚æœæ— æ³•è·å–ï¼Œè¿”å›é»˜è®¤å€¼ï¼ˆ150ï¼‰
 */
float USG_GameplayAbility_Attack::GetAttackRange() const
{
	// è·å–æ–½æ”¾è€…çš„ ASC
	UAbilitySystemComponent* SourceASC = GetAbilitySystemComponentFromActorInfo();
	if (!SourceASC)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("GetAttackRange å¤±è´¥ï¼šæ–½æ”¾è€…æ²¡æœ‰ ASC"));
		return 150.0f; // é»˜è®¤è¿‘æˆ˜èŒƒå›´
	}

	// ä» AttributeSet è¯»å–æ”»å‡»èŒƒå›´
	const USG_AttributeSet* AttributeSet = SourceASC->GetSet<USG_AttributeSet>();
	if (AttributeSet)
	{
		return AttributeSet->GetAttackRange();
	}

	// å¦‚æœæ²¡æœ‰ AttributeSetï¼Œè¿”å›é»˜è®¤å€¼
	UE_LOG(LogSGGameplay, Warning, TEXT("GetAttackRange å¤±è´¥ï¼šæ²¡æœ‰ AttributeSetï¼Œä½¿ç”¨é»˜è®¤å€¼"));
	return 150.0f;
}

// ========== âœ¨ è°ƒè¯•å¯è§†åŒ–å‡½æ•°å®ç° ==========

/**
 * @brief ç»˜åˆ¶è¿‘æˆ˜æ”»å‡»èŒƒå›´æ£€æµ‹
 * @param Center æ£€æµ‹ä¸­å¿ƒä½ç½®
 * @param Radius æ£€æµ‹åŠå¾„
 * @param bHit æ˜¯å¦å‘½ä¸­ç›®æ ‡
 */
void USG_GameplayAbility_Attack::DrawMeleeAttackDetection(const FVector& Center, float Radius, bool bHit)
{
	if (!GetWorld())
	{
		return;
	}

	// é€‰æ‹©é¢œè‰²ï¼ˆæ ¹æ®æ˜¯å¦å‘½ä¸­ï¼‰
	FColor DrawColor = bHit ? AttackRangeHitColor : AttackRangeMissColor;

	// ç»˜åˆ¶çƒä½“ï¼ˆæ£€æµ‹èŒƒå›´ï¼‰
	DrawDebugSphere(
		GetWorld(),
		Center,
		Radius,
		32,  // åˆ†æ®µæ•°
		DrawColor,
		false,  // ä¸æŒä¹…
		DetectionVisualizationDuration,  // æŒç»­æ—¶é—´
		0,  // æ·±åº¦ä¼˜å…ˆçº§
		2.0f  // çº¿æ¡ç²—ç»†
	);

	// ç»˜åˆ¶ä¸­å¿ƒç‚¹
	DrawDebugPoint(
		GetWorld(),
		Center,
		10.0f,  // ç‚¹çš„å¤§å°
		DrawColor,
		false,
		DetectionVisualizationDuration
	);

	// ç»˜åˆ¶æ–‡æœ¬æ ‡ç­¾
	FString DebugText = FString::Printf(TEXT("è¿‘æˆ˜æ£€æµ‹\nåŠå¾„: %.0f\nå‘½ä¸­: %s"), 
		Radius, 
		bHit ? TEXT("æ˜¯") : TEXT("å¦"));
	
	DrawDebugString(
		GetWorld(),
		Center + FVector(0, 0, Radius + 50.0f),  // æ–‡æœ¬ä½ç½®ï¼ˆçƒä½“ä¸Šæ–¹ï¼‰
		DebugText,
		nullptr,  // ä¸éœ€è¦ Actor
		DrawColor,
		DetectionVisualizationDuration,
		true  // ç»˜åˆ¶é˜´å½±
	);
}

/**
 * @brief ç»˜åˆ¶è¿œç¨‹æ”»å‡»èŒƒå›´æ£€æµ‹
 * @param Start å°„çº¿èµ·ç‚¹
 * @param End å°„çº¿ç»ˆç‚¹
 * @param bHit æ˜¯å¦å‘½ä¸­ç›®æ ‡
 * @param HitLocation å‘½ä¸­ä½ç½®ï¼ˆå¦‚æœå‘½ä¸­ï¼‰
 */
void USG_GameplayAbility_Attack::DrawRangedAttackDetection(
	const FVector& Start, 
	const FVector& End, 
	bool bHit, 
	const FVector& HitLocation)
{
	if (!GetWorld())
	{
		return;
	}

	// é€‰æ‹©é¢œè‰²ï¼ˆæ ¹æ®æ˜¯å¦å‘½ä¸­ï¼‰
	FColor DrawColor = bHit ? AttackRangeHitColor : AttackRangeMissColor;

	// ç»˜åˆ¶å°„çº¿
	if (bHit)
	{
		// å¦‚æœå‘½ä¸­ï¼Œç»˜åˆ¶ä¸¤æ®µçº¿ï¼šèµ·ç‚¹åˆ°å‘½ä¸­ç‚¹ï¼ˆçº¢è‰²ï¼‰ï¼Œå‘½ä¸­ç‚¹åˆ°ç»ˆç‚¹ï¼ˆé»„è‰²è™šçº¿ï¼‰
		DrawDebugLine(
			GetWorld(),
			Start,
			HitLocation,
			AttackRangeHitColor,
			false,
			DetectionVisualizationDuration,
			0,
			3.0f  // çº¿æ¡ç²—ç»†
		);

		// ç»˜åˆ¶æœªå‘½ä¸­éƒ¨åˆ†ï¼ˆè™šçº¿ï¼‰
		DrawDebugLine(
			GetWorld(),
			HitLocation,
			End,
			AttackRangeMissColor,
			false,
			DetectionVisualizationDuration,
			0,
			1.0f  // æ›´ç»†çš„çº¿
		);

		// åœ¨å‘½ä¸­ç‚¹ç»˜åˆ¶åå­—æ ‡è®°
		DrawDebugCrosshairs(
			GetWorld(),
			HitLocation,
			FRotator::ZeroRotator,
			100.0f,  // åå­—å¤§å°
			AttackRangeHitColor,
			false,
			DetectionVisualizationDuration,
			0  
		); 
	}
	else
	{
		// å¦‚æœæœªå‘½ä¸­ï¼Œç»˜åˆ¶å®Œæ•´å°„çº¿
		DrawDebugLine(
			GetWorld(),
			Start,
			End,
			AttackRangeMissColor,
			false,
			DetectionVisualizationDuration,
			0,
			2.0f
		);
	}

	// ç»˜åˆ¶èµ·ç‚¹æ ‡è®°
	DrawDebugPoint(
		GetWorld(),
		Start,
		10.0f,
		FColor::Green,
		false,
		DetectionVisualizationDuration
	);

	// ç»˜åˆ¶ç»ˆç‚¹æ ‡è®°
	DrawDebugPoint(
		GetWorld(),
		End,
		10.0f,
		FColor::Blue,
		false,
		DetectionVisualizationDuration
	);

	// ç»˜åˆ¶æ–‡æœ¬æ ‡ç­¾
	float Distance = FVector::Dist(Start, HitLocation);
	FString DebugText = FString::Printf(TEXT("è¿œç¨‹æ£€æµ‹\nè·ç¦»: %.0f\nå‘½ä¸­: %s"), 
		Distance, 
		bHit ? TEXT("æ˜¯") : TEXT("å¦"));
	
	FVector TextLocation = bHit ? HitLocation : ((Start + End) * 0.5f);
	DrawDebugString(
		GetWorld(),
		TextLocation + FVector(0, 0, 100.0f),
		DebugText,
		nullptr,
		DrawColor,
		DetectionVisualizationDuration,
		true
	);
}

/**
 * @brief ç»˜åˆ¶ç›®æ ‡æ ‡è®°
 * @param Targets æ£€æµ‹åˆ°çš„ç›®æ ‡åˆ—è¡¨
 */
void USG_GameplayAbility_Attack::DrawTargetMarkers(const TArray<AActor*>& Targets)
{
	if (!GetWorld())
	{
		return;
	}

	// è·å–æ–½æ”¾è€…ä½ç½®
	AActor* AvatarActor = GetAvatarActorFromActorInfo();
	if (!AvatarActor)
	{
		return;
	}

	FVector SourceLocation = AvatarActor->GetActorLocation();

	// éå†æ‰€æœ‰ç›®æ ‡
	for (int32 i = 0; i < Targets.Num(); ++i)
	{
		AActor* Target = Targets[i];
		if (!Target)
		{
			continue;
		}

		FVector TargetLocation = Target->GetActorLocation();

		// ç»˜åˆ¶ç›®æ ‡æ ‡è®°ï¼ˆçƒä½“ï¼‰
		DrawDebugSphere(
			GetWorld(),
			TargetLocation,
			TargetMarkerSize,
			16,
			TargetMarkerColor,
			false,
			DetectionVisualizationDuration,
			0,
			3.0f
		);

		// ç»˜åˆ¶ä»æ–½æ”¾è€…åˆ°ç›®æ ‡çš„è¿çº¿
		DrawDebugLine(
			GetWorld(),
			SourceLocation,
			TargetLocation,
			TargetMarkerColor,
			false,
			DetectionVisualizationDuration,
			0,
			2.0f
		);

		// ç»˜åˆ¶ç›®æ ‡åºå·
		FString TargetText = FString::Printf(TEXT("ç›®æ ‡ %d\n%s"), 
			i + 1, 
			*Target->GetName());
		
		DrawDebugString(
			GetWorld(),
			TargetLocation + FVector(0, 0, TargetMarkerSize + 20.0f),
			TargetText,
			nullptr,
			TargetMarkerColor,
			DetectionVisualizationDuration,
			true
		);

		// ç»˜åˆ¶ç›®æ ‡çš„æœå‘ç®­å¤´
		FVector TargetForward = Target->GetActorForwardVector();
		DrawDebugDirectionalArrow(
			GetWorld(),
			TargetLocation,
			TargetLocation + TargetForward * 100.0f,
			50.0f,  // ç®­å¤´å¤§å°
			FColor::Cyan,
			false,
			DetectionVisualizationDuration,
			0,
			2.0f
		);
	}

	// ç»˜åˆ¶æ€»ç»“ä¿¡æ¯
	FString SummaryText = FString::Printf(TEXT("æ£€æµ‹åˆ° %d ä¸ªç›®æ ‡"), Targets.Num());
	DrawDebugString(
		GetWorld(),
		SourceLocation + FVector(0, 0, 200.0f),
		SummaryText,
		nullptr,
		FColor::White,
		DetectionVisualizationDuration,
		true,
		2.0f  // æ–‡å­—å¤§å°
	);
}

void USG_GameplayAbility_Attack::OnDamageGameplayEvent(FGameplayEventData Payload)
{
	if (AActor* Target = const_cast<AActor*>(Payload.Target.Get()))
	{
		// è°ƒç”¨ç°æœ‰çš„åº”ç”¨ä¼¤å®³é€»è¾‘
		ApplyDamageToTarget(Target);
        
		// è§¦å‘å‘½ä¸­åé¦ˆ
		TArray<AActor*> HitActors;
		HitActors.Add(Target);
		OnAttackHit(HitActors); 
	}
}
