// ðŸ”§ MODIFIED FILE - å¡ç‰Œå…¥å£ Widget å®žçŽ°
// Copyright notice placeholder
/**
 * @file SG_CardEntryWidget.cpp
 * @brief æ‰‹ç‰Œå¡ç‰‡å…¥å£ Widget å®žçŽ°
 */
#include "UIHud/SG_CardEntryWidget.h"
// å¼•å…¥å¡ç‰Œ ViewModel
#include "UIHud/SG_CardViewModel.h"
// å¼•å…¥å¡ç»„ç»„ä»¶
#include "CardsAndUnits/SG_CardDeckComponent.h"
// âœ¨ NEW - å¼•å…¥æ—¥å¿—ç³»ç»Ÿ
#include "Debug/SG_LogCategories.h"

// è®¾ç½® ViewModel ä¸Žç»„ä»¶
void USG_CardEntryWidget::SetupCardEntry(USGCardViewModel* InViewModel, USG_CardDeckComponent* InDeckComponent)
{
	// ðŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
	UE_LOG(LogSGUI, Verbose, TEXT("SetupCardEntry - å¡ç‰Œ: %s"), 
		InViewModel ? *InViewModel->CardName.ToString() : TEXT("ç©º"));
	
	// å¦‚æžœä¹‹å‰æœ‰ç»‘å®šçš„ ViewModelï¼Œå…ˆè§£ç»‘
	if (BoundViewModel)
	{
		BoundViewModel->OnSelectionChanged.RemoveDynamic(this, &USG_CardEntryWidget::HandleViewModelSelectionChanged);
	}
	
	// ä¿å­˜æ–°çš„ ViewModel å¼•ç”¨
	BoundViewModel = InViewModel;
	DeckComponent = InDeckComponent;
	
	// ç»‘å®šæ–° ViewModel çš„é€‰ä¸­çŠ¶æ€æ”¹å˜äº‹ä»¶
	if (BoundViewModel)
	{
		BoundViewModel->OnSelectionChanged.AddDynamic(this, &USG_CardEntryWidget::HandleViewModelSelectionChanged);
		
		// é€šçŸ¥è“å›¾æ›´æ–° UI
		OnViewModelSet(InViewModel);
		
		// ç«‹å³æ›´æ–°é€‰ä¸­çŠ¶æ€
		OnSelectionStateChanged(BoundViewModel->bIsSelected);
	}
}

// åˆå§‹åŒ–å›žè°ƒ
void USG_CardEntryWidget::NativeConstruct()
{
	// è°ƒç”¨çˆ¶ç±»åˆå§‹åŒ–
	Super::NativeConstruct();
}

// é”€æ¯å›žè°ƒ
void USG_CardEntryWidget::NativeDestruct()
{
	// æ¸…ç†äº‹ä»¶ç»‘å®š
	if (BoundViewModel)
	{
		BoundViewModel->OnSelectionChanged.RemoveDynamic(this, &USG_CardEntryWidget::HandleViewModelSelectionChanged);
	}
	
	// è°ƒç”¨çˆ¶ç±»é”€æ¯
	Super::NativeDestruct();
}


void USG_CardEntryWidget::HandleViewModelSelectionChanged(USGCardViewModel* ViewModel, bool bIsSelected)
{
	// è®°å½•é€‰ä¸­çŠ¶æ€å˜åŒ–
	UE_LOG(LogSGUI, Verbose, TEXT("HandleViewModelSelectionChanged - å¡ç‰Œ: %s, é€‰ä¸­: %s"), 
		*ViewModel->CardName.ToString(),
		bIsSelected ? TEXT("æ˜¯") : TEXT("å¦"));
	
	// é€šçŸ¥è“å›¾æ›´æ–°è§†è§‰æ•ˆæžœ
	OnSelectionStateChanged(bIsSelected);
}


/**
 * @brief è“å›¾é€šçŸ¥å¡ç‰Œç‚¹å‡»
 * @details éœ€è¦åœ¨è“å›¾ä¸­æ£€æŸ¥ CanInteract
 */
void USG_CardEntryWidget::NotifyCardClicked()
{
	
	// ðŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
	UE_LOG(LogSGUI, Log, TEXT("NotifyCardClicked - å¡ç‰Œ: %s"), 
		BoundViewModel ? *BoundViewModel->CardName.ToString() : TEXT("ç©º"));
	
	// æ£€æŸ¥ç»„ä»¶å’Œ ViewModel æœ‰æ•ˆæ€§
	if (DeckComponent && BoundViewModel)
	{
		// è°ƒç”¨å¡ç»„ç»„ä»¶é€‰æ‹©å¡ç‰Œ
		DeckComponent->SelectCard(BoundViewModel->InstanceId);
	}
}

