// ğŸ”§ MODIFIED FILE - æ‰‹ç‰Œ ViewModel å®ç°
// Copyright notice placeholder
/**
 * @file SG_CardHandViewModel.cpp
 * @brief æ‰‹ç‰Œ ViewModel å®ç°
 */
#include "UIHud/SG_CardHandViewModel.h"
// å¼•å…¥å¡ç»„ç»„ä»¶
#include "CardsAndUnits/SG_CardDeckComponent.h"
// å¼•å…¥å¡ç‰Œ ViewModel
#include "UIHud/SG_CardViewModel.h"
// âœ¨ NEW - å¼•å…¥æ—¥å¿—ç³»ç»Ÿ
#include "Debug/SG_LogCategories.h"

// åˆå§‹åŒ– ViewModel
void USGCardHandViewModel::Initialize(USG_CardDeckComponent* InDeckComponent)
{
	// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
	UE_LOG(LogSGUI, Log, TEXT("CardHandViewModel::Initialize è¢«è°ƒç”¨"));
	
	// ä¿å­˜è¢«è§‚å¯Ÿçš„ç»„ä»¶
	ObservedDeck = InDeckComponent;
	
	// è‹¥ç»„ä»¶æ— æ•ˆåˆ™è¿”å›
	if (!ObservedDeck)
	{
		// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
		UE_LOG(LogSGUI, Error, TEXT("âŒ ObservedDeck ä¸ºç©º"));
		return;
	}
	
	// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
	UE_LOG(LogSGUI, Log, TEXT("ç»‘å®šäº‹ä»¶å§”æ‰˜..."));
	
	// ç»‘å®šæ‰‹ç‰Œæ›´æ–°äº‹ä»¶
	ObservedDeck->OnHandChanged.AddDynamic(this, &USGCardHandViewModel::HandleHandChanged);
	// ç»‘å®šé€‰ä¸­å˜åŒ–äº‹ä»¶
	ObservedDeck->OnSelectionChanged.AddDynamic(this, &USGCardHandViewModel::HandleSelectionChanged);
	// ç»‘å®šè¡ŒåŠ¨çŠ¶æ€äº‹ä»¶
	ObservedDeck->OnActionStateChanged.AddDynamic(this, &USGCardHandViewModel::HandleActionStateChanged);
	
	// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
	UE_LOG(LogSGUI, Log, TEXT("åˆå§‹åŒ–å½“å‰çŠ¶æ€ï¼ˆæ‰‹ç‰Œæ•°ï¼š%dï¼‰..."), ObservedDeck->GetHand().Num());
	
	// åˆå§‹åŒ–å½“å‰æ‰‹ç‰Œ
	HandleHandChanged(ObservedDeck->GetHand());
	// åˆå§‹åŒ–é€‰ä¸­çŠ¶æ€
	HandleSelectionChanged(ObservedDeck->GetSelectedCardId());
	// åˆå§‹åŒ–è¡ŒåŠ¨çŠ¶æ€
	HandleActionStateChanged(ObservedDeck->CanAct(), ObservedDeck->GetCooldownRemaining());
	
	// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
	UE_LOG(LogSGUI, Log, TEXT("âœ“ CardHandViewModel åˆå§‹åŒ–å®Œæˆ"));

}

// ææ„å‰è§£ç»‘
void USGCardHandViewModel::BeginDestroy()
{
	// è‹¥å­˜åœ¨ç»„ä»¶åˆ™è§£ç»‘å§”æ‰˜
	if (ObservedDeck)
	{
		// è§£ç»‘æ‰‹ç‰Œæ›´æ–°
		ObservedDeck->OnHandChanged.RemoveDynamic(this, &USGCardHandViewModel::HandleHandChanged);
		// è§£ç»‘é€‰ä¸­å˜åŒ–
		ObservedDeck->OnSelectionChanged.RemoveDynamic(this, &USGCardHandViewModel::HandleSelectionChanged);
		// è§£ç»‘è¡ŒåŠ¨çŠ¶æ€
		ObservedDeck->OnActionStateChanged.RemoveDynamic(this, &USGCardHandViewModel::HandleActionStateChanged);
	}
	
	// è°ƒç”¨çˆ¶ç±»ææ„
	Super::BeginDestroy();
}

// å¤„ç†æ‰‹ç‰Œæ›´æ–°
void USGCardHandViewModel::HandleHandChanged(const TArray<FSGCardInstance>& NewHand)
{
	/*// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
	UE_LOG(LogSGUI, Log, TEXT("HandleHandChanged - æ–°æ‰‹ç‰Œæ•°ï¼š%d"), NewHand.Num());
	
	// æ„å»ºæ–°æ—§æ˜ å°„ï¼Œç”¨äºå¤ç”¨å·²æœ‰çš„ ViewModel
	TMap<FGuid, int32> OldIndexMap;
	for (int32 i = 0; i < CardViewModels.Num(); ++i)
	{
		if (CardViewModels[i])
		{
			OldIndexMap.Add(CardViewModels[i]->InstanceId, i);
		}
	}
	
	// åˆ›å»ºä¸´æ—¶æ•°ç»„
	TArray<TObjectPtr<USGCardViewModel>> NewViewModels;
	NewViewModels.Reserve(NewHand.Num()); // é¢„åˆ†é…ç©ºé—´
	
	// éå†æ–°æ‰‹ç‰Œ
	for (const FSGCardInstance& Instance : NewHand)
	{
		// æ£€æŸ¥å¡ç‰Œæ•°æ®æœ‰æ•ˆæ€§
		if (!Instance.CardData)
		{
			// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
			UE_LOG(LogSGUI, Warning, TEXT("âš ï¸ å¡ç‰Œå®ä¾‹çš„ CardData ä¸ºç©ºï¼Œè·³è¿‡"));
			continue;
		}
		
		// âœ¨ NEW - å°è¯•å¤ç”¨å·²æœ‰çš„ ViewModel
		USGCardViewModel* ViewModel = nullptr;
		if (int32* OldIndex = OldIndexMap.Find(Instance.InstanceId))
		{
			// å¤ç”¨å·²æœ‰çš„ ViewModel
			ViewModel = CardViewModels[*OldIndex].Get();
			
			// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
			UE_LOG(LogSGUI, Verbose, TEXT("  â™»ï¸ å¤ç”¨ ViewModel - åç§°: %s, ID: %s"), 
				*ViewModel->CardName.ToString(), 
				*ViewModel->InstanceId.ToString());
		}
		else
		{
			// æ–°å»ºè§†å›¾æ¨¡å‹
			ViewModel = NewObject<USGCardViewModel>(this);
			if (!ViewModel)
			{
				// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
				UE_LOG(LogSGUI, Error, TEXT("âŒ åˆ›å»º ViewModel å¤±è´¥"));
				continue;
			}
			
			// åˆå§‹åŒ–è§†å›¾æ¨¡å‹
			ViewModel->InitializeFromInstance(Instance, false, ObservedDeck ? ObservedDeck->CanAct() : true);
			
			// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
			UE_LOG(LogSGUI, Verbose, TEXT("  âœ“ åˆ›å»º ViewModel - åç§°: %s, ID: %s"), 
				*ViewModel->CardName.ToString(), 
				*ViewModel->InstanceId.ToString());
		}
		
		// ä¿å­˜åˆ°ä¸´æ—¶æ•°ç»„
		NewViewModels.Add(ViewModel);
	}
	
	// ä½¿ç”¨ MVVM å®æ›´æ–°å±æ€§ï¼Œè¿™ä¼šè§¦å‘ FieldNotify
	UE_MVVM_SET_PROPERTY_VALUE(CardViewModels, NewViewModels);
	
	// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
	UE_LOG(LogSGUI, Log, TEXT("âœ“ CardViewModels å·²æ›´æ–°ï¼Œæ•°é‡ï¼š%d"), CardViewModels.Num());
	
	// é‡æ–°åº”ç”¨é€‰ä¸­çŠ¶æ€
	if (ObservedDeck)
	{
		HandleSelectionChanged(ObservedDeck->GetSelectedCardId());
	}*/
	 // è¾“å‡ºæ—¥å¿—
    UE_LOG(LogSGUI, Log, TEXT("HandleHandChanged - æ–°æ‰‹ç‰Œæ•°ï¼š%d"), NewHand.Num());
    
    // ğŸ”§ MODIFIED - æ‰¾å‡ºè¢«ç§»é™¤çš„å¡ç‰Œ
    TSet<FGuid> NewHandIds;
    for (const FSGCardInstance& Instance : NewHand)
    {
        NewHandIds.Add(Instance.InstanceId);
    }
    
    // éå†æ—§çš„ ViewModelï¼Œé€šçŸ¥ä¸åœ¨æ–°æ‰‹ç‰Œä¸­çš„å¡
    for (USGCardViewModel* OldVM : CardViewModels)
    {
        if (OldVM && !NewHandIds.Contains(OldVM->InstanceId))
        {
            // é€šçŸ¥å¡ç‰Œè¢«ä½¿ç”¨
            OldVM->NotifyCardUsed();
            // è¾“å‡ºæ—¥å¿—
            UE_LOG(LogSGUI, Log, TEXT("  ğŸ“¢ é€šçŸ¥å¡ç‰Œè¢«ä½¿ç”¨ï¼š%s"), *OldVM->CardName.ToString());
        }
    }
    
    // æ„å»ºæ–°æ—§æ˜ å°„ï¼Œç”¨äºå¤ç”¨å·²æœ‰çš„ ViewModel
    TMap<FGuid, int32> OldIndexMap;
    for (int32 i = 0; i < CardViewModels.Num(); ++i)
    {
        if (CardViewModels[i])
        {
            OldIndexMap.Add(CardViewModels[i]->InstanceId, i);
        }
    }
    
    // åˆ›å»ºä¸´æ—¶æ•°ç»„
    TArray<TObjectPtr<USGCardViewModel>> NewViewModels;
    NewViewModels.Reserve(NewHand.Num());
    
    // éå†æ–°æ‰‹ç‰Œ
    for (const FSGCardInstance& Instance : NewHand)
    {
        // æ£€æŸ¥å¡ç‰Œæ•°æ®æœ‰æ•ˆæ€§
        if (!Instance.CardData)
        {
            UE_LOG(LogSGUI, Warning, TEXT("âš ï¸ å¡ç‰Œå®ä¾‹çš„ CardData ä¸ºç©ºï¼Œè·³è¿‡"));
            continue;
        }
        
        // å°è¯•å¤ç”¨å·²æœ‰çš„ ViewModel
        USGCardViewModel* ViewModel = nullptr;
        if (int32* OldIndex = OldIndexMap.Find(Instance.InstanceId))
        {
            // å¤ç”¨å·²æœ‰çš„ ViewModel
            ViewModel = CardViewModels[*OldIndex].Get();
            UE_LOG(LogSGUI, Verbose, TEXT("  â™»ï¸ å¤ç”¨ ViewModel - åç§°: %s"), 
                *ViewModel->CardName.ToString());
        }
        else
        {
            // æ–°å»ºè§†å›¾æ¨¡å‹
            ViewModel = NewObject<USGCardViewModel>(this);
            if (!ViewModel)
            {
                UE_LOG(LogSGUI, Error, TEXT("âŒ åˆ›å»º ViewModel å¤±è´¥"));
                continue;
            }
            
            // åˆå§‹åŒ–è§†å›¾æ¨¡å‹
            ViewModel->InitializeFromInstance(Instance, false, 
                ObservedDeck ? ObservedDeck->CanAct() : true);
            
            UE_LOG(LogSGUI, Verbose, TEXT("  âœ“ åˆ›å»º ViewModel - åç§°: %s"), 
                *ViewModel->CardName.ToString());
        }
        
        // ä¿å­˜åˆ°ä¸´æ—¶æ•°ç»„
        NewViewModels.Add(ViewModel);
    }
    
    // ä½¿ç”¨ MVVM å®æ›´æ–°å±æ€§
    UE_MVVM_SET_PROPERTY_VALUE(CardViewModels, NewViewModels);
    
    // è¾“å‡ºæ—¥å¿—
    UE_LOG(LogSGUI, Log, TEXT("âœ“ CardViewModels å·²æ›´æ–°ï¼Œæ•°é‡ï¼š%d"), CardViewModels.Num());
    
    // é‡æ–°åº”ç”¨é€‰ä¸­çŠ¶æ€
    if (ObservedDeck)
    {
        HandleSelectionChanged(ObservedDeck->GetSelectedCardId());
    }	
	// ğŸ”§ MODIFIED - ä½¿ç”¨æ–°çš„æ—¥å¿—ç±»åˆ«
	UE_LOG(LogSGUI, Log, TEXT("âœ“ HandChanged å¤„ç†å®Œæˆ"));
}

// å¤„ç†é€‰ä¸­å˜åŒ–
void USGCardHandViewModel::HandleSelectionChanged(const FGuid& SelectedId)
{
	// éå†æ‰€æœ‰è§†å›¾æ¨¡å‹
	for (USGCardViewModel* ViewModel : CardViewModels)
	{
		// è‹¥ä¸ºç©ºåˆ™è·³è¿‡
		if (!ViewModel)
		{
			continue;
		}
		// æ›´æ–°é€‰ä¸­çŠ¶æ€
		ViewModel->SetSelected(ViewModel->InstanceId == SelectedId);
	}
}

// å¤„ç†è¡ŒåŠ¨çŠ¶æ€
void USGCardHandViewModel::HandleActionStateChanged(bool bCanActValue, float CooldownRemaining)
{
	// æ›´æ–°è¡ŒåŠ¨å¯ç”¨æ€§
	// æ›´æ–°å¹¶å¹¿æ’­è¡ŒåŠ¨å¯ç”¨æ€§
	UE_MVVM_SET_PROPERTY_VALUE(bCanAct, bCanActValue);
	// æ›´æ–°å†·å´æ—¶é—´
	UE_MVVM_SET_PROPERTY_VALUE(Cooldown, CooldownRemaining);
	// åŒæ­¥æ¯å¼ è§†å›¾æ¨¡å‹çš„å¯ç”¨æ€§
	for (USGCardViewModel* ViewModel : CardViewModels)
	{
		// è·³è¿‡ç©ºæŒ‡é’ˆ
		if (!ViewModel)
		{
			continue;
		}
		// è®¾ç½®å¯ç”¨æ ‡è®°
		ViewModel->SetPlayable(bCanActValue);
	}
}

TArray<USGCardViewModel*> USGCardHandViewModel::GetCardViewModels() const
{
	// éœ€è¦è½¬æ¢ TObjectPtr æ•°ç»„ä¸ºåŸå§‹æŒ‡é’ˆæ•°ç»„
	// ç”±äº UFUNCTION é™åˆ¶ï¼Œæˆ‘ä»¬éœ€è¦ä½¿ç”¨ä¸€ä¸ªä¸´æ—¶å˜é‡
	static TArray<USGCardViewModel*> TempArray;
	TempArray.Reset();
	for (const TObjectPtr<USGCardViewModel>& VM : CardViewModels)
	{
		TempArray.Add(VM.Get());
	}
	return TempArray;
}


