// ğŸ“„ æ–‡ä»¶ï¼šSource/Sguo/Private/AI/SG_AIControllerBase.cpp
// ğŸ”§ ä¿®æ”¹ - å®Œæ•´ä¿®å¤
// âœ… è¿™æ˜¯å®Œæ•´æ–‡ä»¶

#include "AI/SG_AIControllerBase.h"
#include "AbilitySystem/SG_AttributeSet.h"
#include "BehaviorTree/BehaviorTree.h"
#include "BehaviorTree/BlackboardComponent.h"
#include "BehaviorTree/BehaviorTreeComponent.h"
#include "Units/SG_UnitsBase.h"
#include "Kismet/GameplayStatics.h"
#include "Buildings/SG_MainCityBase.h"
#include "Debug/SG_LogCategories.h"
#include "NavigationSystem.h"
#include "AI/SG_CombatTargetManager.h"
#include "AI/SG_TargetingSubsystem.h"
#include "Components/BoxComponent.h"


// ========== é»‘æ¿é”®åç§°å®šä¹‰ ==========
const FName ASG_AIControllerBase::BB_CurrentTarget = TEXT("CurrentTarget");
const FName ASG_AIControllerBase::BB_IsInAttackRange = TEXT("IsInAttackRange");
const FName ASG_AIControllerBase::BB_IsTargetLocked = TEXT("IsTargetLocked");
const FName ASG_AIControllerBase::BB_IsTargetMainCity = TEXT("IsTargetMainCity");



// ========== æ„é€ å‡½æ•° ==========
ASG_AIControllerBase::ASG_AIControllerBase()
{
    PrimaryActorTick.bCanEverTick = true;
    bWantsPlayerState = false;
    bSetControlRotationFromPawnOrientation = false;
}

// ========== BeginPlay ==========
void ASG_AIControllerBase::BeginPlay()
{
    Super::BeginPlay();
}

/**
 * @brief Tick æ›´æ–°
 * @param DeltaTime å¸§é—´éš”
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - æ›´æ–°ç§»åŠ¨è®¡æ—¶å™¨
 * - å‘¨æœŸæ€§æ¸…ç†ä¸å¯è¾¾åˆ—è¡¨
 * - ç§»åŠ¨ä¸­æ£€æµ‹æ›´å¥½ç›®æ ‡
 * - âœ¨ æ–°å¢ï¼šæ”»å‡»ä¸»åŸæ—¶æ£€æµ‹æ•Œæ–¹å•ä½
 */
void ASG_AIControllerBase::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
    
    // æ›´æ–°ç§»åŠ¨è®¡æ—¶å™¨
    UpdateMovementTimer(DeltaTime);
    
    // å‘¨æœŸæ€§æ¸…ç†ä¸å¯è¾¾åˆ—è¡¨
    UnreachableClearTimer += DeltaTime;
    if (UnreachableClearTimer >= UnreachableClearInterval)
    {
        UnreachableClearTimer = 0.0f;
        ClearUnreachableTargets();
    }

    // âœ¨ æ–°å¢ - æ”»å‡»ä¸»åŸæ—¶æ£€æµ‹æ•Œæ–¹å•ä½
    TargetSwitchCheckTimer += DeltaTime;
    if (TargetSwitchCheckTimer >= TargetSwitchCheckInterval)
    {
        TargetSwitchCheckTimer = 0.0f;
        
        // ç§»åŠ¨ä¸­æˆ–æ”»å‡»ä¸»åŸæ—¶éƒ½æ£€æµ‹æ›´å¥½ç›®æ ‡
        if (TargetEngagementState == ESGTargetEngagementState::Moving)
        {
            CheckForBetterTargetWhileMoving();
        }
        else if (TargetEngagementState == ESGTargetEngagementState::Engaged)
        {
            // åªæœ‰æ”»å‡»ä¸»åŸæ—¶æ‰æ£€æµ‹æ•Œæ–¹å•ä½
            CheckForEnemyUnitsWhileAttackingMainCity();
        }
    }
}

// ========== OnPossess ==========
void ASG_AIControllerBase::OnPossess(APawn* InPawn)
{
    Super::OnPossess(InPawn);
    
    // åˆå§‹åŒ–ä½ç½®è®°å½•
    LastPosition = InPawn->GetActorLocation();
    
    // æ­¥éª¤1ï¼šç¡®å®šè¦ä½¿ç”¨çš„è¡Œä¸ºæ ‘
    UBehaviorTree* BehaviorTreeToUse = nullptr;
    
    ASG_UnitsBase* ControlledUnit = Cast<ASG_UnitsBase>(InPawn);
    if (ControlledUnit)
    {
        BehaviorTreeToUse = ControlledUnit->GetUnitBehaviorTree();
    }
    
    if (!BehaviorTreeToUse && DefaultBehaviorTree)
    {
        BehaviorTreeToUse = DefaultBehaviorTree;
    }
    
    if (!BehaviorTreeToUse)
    {
        UE_LOG(LogSGGameplay, Warning, TEXT("AI: %s æ²¡æœ‰å¯ç”¨çš„è¡Œä¸ºæ ‘"), *InPawn->GetName());
        return;
    }
    
    // æ­¥éª¤2ï¼šå¯åŠ¨è¡Œä¸ºæ ‘
    StartBehaviorTree(BehaviorTreeToUse);
}

// ========== SetupBehaviorTree ==========
bool ASG_AIControllerBase::SetupBehaviorTree(UBehaviorTree* BehaviorTreeToUse)
{
    if (!BehaviorTreeToUse)
    {
        return false;
    }
    
    UBlackboardData* BlackboardAsset = BehaviorTreeToUse->BlackboardAsset;
    if (!BlackboardAsset)
    {
        return false;
    }
    
    UBlackboardComponent* BlackboardComp = nullptr;
    bool bSuccess = UseBlackboard(BlackboardAsset, BlackboardComp);
    
    if (bSuccess && BlackboardComp)
    {
        BlackboardComp->SetValueAsBool(BB_IsTargetLocked, false);
        BlackboardComp->SetValueAsBool(BB_IsInAttackRange, false);
        BlackboardComp->SetValueAsBool(BB_IsTargetMainCity, false);
        return true;
    }
    
    return false;
}

// ========== StartBehaviorTree ==========
bool ASG_AIControllerBase::StartBehaviorTree(UBehaviorTree* BehaviorTreeToRun)
{
    if (!BehaviorTreeToRun)
    {
        return false;
    }
    
    UBehaviorTreeComponent* BTComp = Cast<UBehaviorTreeComponent>(GetBrainComponent());
    
    if (BTComp && BTComp->IsRunning())
    {
        BTComp->StopTree(EBTStopMode::Safe);
    }
    
    if (!SetupBehaviorTree(BehaviorTreeToRun))
    {
        return false;
    }
    
    bool bSuccess = AAIController::RunBehaviorTree(BehaviorTreeToRun);
    
    if (bSuccess)
    {
        CurrentBehaviorTree = BehaviorTreeToRun;
    }
    
    return bSuccess;
}

/**
 * @brief å–æ¶ˆæ§åˆ¶æ—¶è°ƒç”¨
 */
void ASG_AIControllerBase::OnUnPossess()
{
    if (AActor* CurrentTarget = GetCurrentTarget())
    {
        if (ASG_UnitsBase* ControlledUnit = Cast<ASG_UnitsBase>(GetPawn()))
        {
            if (UWorld* World = GetWorld())
            {
                if (USG_TargetingSubsystem* TargetingSys = World->GetSubsystem<USG_TargetingSubsystem>())
                {
                    TargetingSys->UnregisterAttacker(ControlledUnit, CurrentTarget);
                }

                // åªæœ‰éä¸»åŸç›®æ ‡ä¸”éœ€è¦æ§½ä½æ—¶æ‰é‡Šæ”¾æ§½ä½
                if (ShouldOccupyAttackSlot() && !CurrentTarget->IsA(ASG_MainCityBase::StaticClass()))
                {
                    if (USG_CombatTargetManager* CombatManager = World->GetSubsystem<USG_CombatTargetManager>())
                    {
                        CombatManager->ReleaseAttackSlot(ControlledUnit, CurrentTarget);
                    }
                }
            }
        }
    }

    if (CurrentListenedTarget.IsValid())
    {
        UnbindTargetDeathEvent(CurrentListenedTarget.Get());
        CurrentListenedTarget = nullptr;
    }
    
    UBehaviorTreeComponent* BTComp = Cast<UBehaviorTreeComponent>(GetBrainComponent());
    if (BTComp && BTComp->IsRunning())
    {
        BTComp->StopTree(EBTStopMode::Safe);
    }
    
    CurrentBehaviorTree = nullptr;
    UnreachableTargets.Empty();
    TargetEngagementState = ESGTargetEngagementState::Searching;
    
    Super::OnUnPossess();
}

// ========== FreezeAI ==========
void ASG_AIControllerBase::FreezeAI()
{
    UBehaviorTreeComponent* BTComp = Cast<UBehaviorTreeComponent>(GetBrainComponent());
    if (BTComp)
    {
        BTComp->StopTree(EBTStopMode::Safe);
    }
    
    StopMovement();
    
    if (CurrentListenedTarget.IsValid())
    {
        UnbindTargetDeathEvent(CurrentListenedTarget.Get());
        CurrentListenedTarget = nullptr;
    }
    
    SetCurrentTarget(nullptr);
    SetActorTickEnabled(false);
    
    TargetEngagementState = ESGTargetEngagementState::Searching;
}

/**
 * @brief è®¾ç½®ç›®æ ‡é”å®šçŠ¶æ€
 * @param NewState æ–°çŠ¶æ€
 */
void ASG_AIControllerBase::SetTargetEngagementState(ESGTargetEngagementState NewState)
{
    if (TargetEngagementState == NewState)
    {
        return;
    }
    
    TargetEngagementState = NewState;
}

/**
 * @brief æ£€æŸ¥æ˜¯å¦å…è®¸åˆ‡æ¢ç›®æ ‡
 * @return æ˜¯å¦å…è®¸åˆ‡æ¢
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - âœ¨ æ–°å¢ï¼šæ”»å‡»é”å®šæœŸé—´ä¸å…è®¸åˆ‡æ¢ç›®æ ‡
 * - Engaged çŠ¶æ€ä¸‹æ”»å‡»æ•Œæ–¹å•ä½æ—¶ä¸å…è®¸åˆ‡æ¢ï¼ˆé™¤éç›®æ ‡æ­»äº¡ä¸”åŠ¨ç”»ç»“æŸï¼‰
 * - æ”»å‡»ä¸»åŸæ—¶å…è®¸åˆ‡æ¢åˆ°æ•Œæ–¹å•ä½
 */
bool ASG_AIControllerBase::CanSwitchTarget() const
{
    // âœ¨ æ–°å¢ - æ£€æŸ¥å•ä½æ˜¯å¦å¤„äºæ”»å‡»é”å®šçŠ¶æ€
    ASG_UnitsBase* ControlledUnit = Cast<ASG_UnitsBase>(GetPawn());
    if (ControlledUnit && ControlledUnit->IsAttackLocked())
    {
        // æ”»å‡»é”å®šæœŸé—´ç»å¯¹ä¸å…è®¸åˆ‡æ¢ç›®æ ‡
        return false;
        
    }
    // Searchingã€Movingã€Blocked çŠ¶æ€éƒ½å…è®¸åˆ‡æ¢
    if (TargetEngagementState != ESGTargetEngagementState::Engaged)
    {
        return true;
    }
    
    // Engaged çŠ¶æ€ä¸‹ï¼Œæ£€æŸ¥å½“å‰ç›®æ ‡æ˜¯å¦æ˜¯ä¸»åŸ
    AActor* CurrentTarget = GetCurrentTarget();
    if (CurrentTarget && CurrentTarget->IsA(ASG_MainCityBase::StaticClass()))
    {
        // æ”»å‡»ä¸»åŸæ—¶å…è®¸åˆ‡æ¢åˆ°æ•Œæ–¹å•ä½
        return true;
    }
    
    // æ”»å‡»æ•Œæ–¹å•ä½æ—¶ä¸å…è®¸åˆ‡æ¢
    return false;
}

// âœ¨ æ–°å¢ - æ”»å‡»ä¸»åŸæ—¶æ£€æµ‹æ•Œæ–¹å•ä½
/**
 * @brief æ”»å‡»ä¸»åŸæ—¶æ£€æµ‹æ•Œæ–¹å•ä½
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - ä»…åœ¨ Engaged çŠ¶æ€ä¸”ç›®æ ‡æ˜¯ä¸»åŸæ—¶è°ƒç”¨
 * - å¦‚æœè§†é‡å†…æœ‰æ•Œæ–¹å•ä½ï¼Œåˆ‡æ¢ç›®æ ‡
 */
void ASG_AIControllerBase::CheckForEnemyUnitsWhileAttackingMainCity()
{
    // âœ¨ æ–°å¢ - æ”»å‡»é”å®šæ£€æŸ¥
    ASG_UnitsBase* ControlledUnit = Cast<ASG_UnitsBase>(GetPawn());
    if (ControlledUnit && ControlledUnit->IsAttackLocked())
    {
        return;
    }
    
    AActor* CurrentTarget = GetCurrentTarget();
    if (!CurrentTarget)
    {
        return;
    }
    
    // åªæœ‰å½“å‰ç›®æ ‡æ˜¯ä¸»åŸæ—¶æ‰æ£€æµ‹
    if (!CurrentTarget->IsA(ASG_MainCityBase::StaticClass()))
    {
        return;
    }
    
   
    
    UWorld* World = GetWorld();
    if (!World)
    {
        return;
    }
    
    USG_TargetingSubsystem* TargetingSys = World->GetSubsystem<USG_TargetingSubsystem>();
    if (!TargetingSys)
    {
        return;
    }
    
    // æŸ¥æ‰¾æ•Œæ–¹å•ä½ï¼ˆä¸åŒ…æ‹¬ä¸»åŸï¼‰
    TArray<FSGTargetCandidate> Candidates;
    TSet<TWeakObjectPtr<AActor>> IgnoreList = UnreachableTargets;
    
    AActor* EnemyUnit = TargetingSys->FindEnemyUnitsOnly(
        ControlledUnit,
        ControlledUnit->GetDetectionRange(),
        Candidates,
        IgnoreList
    );
    
    if (EnemyUnit)
    {
        // å‘ç°æ•Œæ–¹å•ä½ï¼Œåˆ‡æ¢ç›®æ ‡
        UE_LOG(LogSGGameplay, Log, TEXT("AI: %s å‘ç°æ•Œæ–¹å•ä½ %sï¼Œä»ä¸»åŸåˆ‡æ¢"),
            *ControlledUnit->GetName(), *EnemyUnit->GetName());
        
        SetCurrentTarget(EnemyUnit);
    }
}

/**
 * @brief åœ¨ç§»åŠ¨çŠ¶æ€ä¸‹æ£€æµ‹æ˜¯å¦æœ‰æ›´å¥½çš„ç›®æ ‡
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - âœ¨ æ–°å¢ï¼šæ”»å‡»é”å®šæœŸé—´ä¸æ£€æµ‹
 */
void ASG_AIControllerBase::CheckForBetterTargetWhileMoving()
{
    // âœ¨ æ–°å¢ - æ”»å‡»é”å®šæ£€æŸ¥
    ASG_UnitsBase* ControlledUnit = Cast<ASG_UnitsBase>(GetPawn());
    if (ControlledUnit && ControlledUnit->IsAttackLocked())
    {
        return;
    }
    
    if (TargetEngagementState != ESGTargetEngagementState::Moving)
    {
        return;
    }

  

    AActor* CurrentTarget = GetCurrentTarget();
    if (!CurrentTarget)
    {
        return;
    }

    bool bCurrentTargetIsMainCity = CurrentTarget->IsA(ASG_MainCityBase::StaticClass());

    UWorld* World = GetWorld();
    if (!World)
    {
        return;
    }

    USG_TargetingSubsystem* TargetingSys = World->GetSubsystem<USG_TargetingSubsystem>();
    if (!TargetingSys)
    {
        return;
    }

    FVector MyLocation = ControlledUnit->GetActorLocation();
    float CurrentDistance = FVector::Dist(MyLocation, CurrentTarget->GetActorLocation());

    TArray<FSGTargetCandidate> Candidates;
    TSet<TWeakObjectPtr<AActor>> IgnoreList = UnreachableTargets;
    
    AActor* BetterTarget = TargetingSys->FindEnemyUnitsOnly(
        ControlledUnit,
        ControlledUnit->GetDetectionRange(),
        Candidates,
        IgnoreList
    );

    if (BetterTarget && BetterTarget != CurrentTarget)
    {
        float NewDistance = FVector::Dist(MyLocation, BetterTarget->GetActorLocation());

        bool bShouldSwitch = false;
        
        if (bCurrentTargetIsMainCity)
        {
            // å½“å‰æ”»å‡»ä¸»åŸï¼Œå‘ç°æ•Œæ–¹å•ä½å°±åˆ‡æ¢
            bShouldSwitch = true;
        }
        else if (CurrentDistance - NewDistance > TargetSwitchDistanceThreshold)
        {
            // æ–°ç›®æ ‡æ˜æ˜¾æ›´è¿‘
            bShouldSwitch = true;
        }

        if (bShouldSwitch)
        {
            SetCurrentTarget(BetterTarget);
        }
    }
}

/**
 * @brief æ ‡è®°å½“å‰ç›®æ ‡ä¸ºä¸å¯è¾¾
 */
void ASG_AIControllerBase::MarkCurrentTargetUnreachable()
{
    AActor* CurrentTarget = GetCurrentTarget();
    if (!CurrentTarget)
    {
        return;
    }
    
    // ä¸»åŸä¸æ ‡è®°ä¸ºä¸å¯è¾¾
    if (CurrentTarget->IsA(ASG_MainCityBase::StaticClass()))
    {
        return;
    }
    
    UnreachableTargets.Add(CurrentTarget);
    SetTargetEngagementState(ESGTargetEngagementState::Blocked);
}

/**
 * @brief æ¸…é™¤ä¸å¯è¾¾ç›®æ ‡åˆ—è¡¨
 */
void ASG_AIControllerBase::ClearUnreachableTargets()
{
    for (auto It = UnreachableTargets.CreateIterator(); It; ++It)
    {
        if (!It->IsValid())
        {
            It.RemoveCurrent();
        }
    }
    
    if (UnreachableTargets.Num() > 0)
    {
        UnreachableTargets.Empty();
    }
}

/**
 * @brief æ£€æŸ¥ç›®æ ‡æ˜¯å¦åœ¨ä¸å¯è¾¾åˆ—è¡¨ä¸­
 */
bool ASG_AIControllerBase::IsTargetUnreachable(AActor* Target) const
{
    if (!Target)
    {
        return false;
    }
    
    return UnreachableTargets.Contains(Target);
}

/**
 * @brief æ£€æŸ¥æ˜¯å¦å¡ä½
 */
bool ASG_AIControllerBase::IsStuck() const
{
    return MovementTimer >= StuckThresholdTime;
}

/**
 * @brief é‡ç½®ç§»åŠ¨è®¡æ—¶å™¨
 */
void ASG_AIControllerBase::ResetMovementTimer()
{
    MovementTimer = 0.0f;
    if (APawn* ControlledPawn = GetPawn())
    {
        LastPosition = ControlledPawn->GetActorLocation();
    }
}

/**
 * @brief æ›´æ–°ç§»åŠ¨è®¡æ—¶å™¨
 */
void ASG_AIControllerBase::UpdateMovementTimer(float DeltaTime)
{
    if (TargetEngagementState != ESGTargetEngagementState::Moving)
    {
        MovementTimer = 0.0f;
        return;
    }
    
    APawn* ControlledPawn = GetPawn();
    if (!ControlledPawn)
    {
        return;
    }

    float Speed = ControlledPawn->GetVelocity().Size();
    
    if (Speed < 10.0f)
    {
        MovementTimer += DeltaTime;
    }
    else
    {
        MovementTimer = 0.0f; 
    }

    if (MovementTimer > 0.5f)
    {
        MovementTimer = 0.0f;
        TryFlankingMove();
    }
}


/**
 * @brief å°è¯•ä¾§é¢ç»•è¡Œ
 */
void ASG_AIControllerBase::TryFlankingMove()
{
    ASG_UnitsBase* Unit = Cast<ASG_UnitsBase>(GetPawn());
    AActor* CurrentTarget = GetCurrentTarget();
    
    if (!Unit || !CurrentTarget)
    {
        return;
    }

    // ä¸»åŸä¸éœ€è¦ç»•è¡Œ
    if (CurrentTarget->IsA(ASG_MainCityBase::StaticClass()))
    {
        return;
    }

    // è¿œç¨‹å•ä½ä¸éœ€è¦ç»•è¡Œ
    if (!ShouldOccupyAttackSlot())
    {
        return;
    }

    if (UWorld* World = GetWorld())
    {
        USG_CombatTargetManager* CombatManager = World->GetSubsystem<USG_CombatTargetManager>();
        if (CombatManager)
        {
            CombatManager->ReleaseAttackSlot(Unit, CurrentTarget);
            
            FVector NewSlotPos;
            if (CombatManager->TryReserveAttackSlot(Unit, CurrentTarget, NewSlotPos))
            {
                MoveToLocation(NewSlotPos, -1.0f, true, true, true);
            }
            else
            {
                MarkCurrentTargetUnreachable();
                StopMovement();
            }
        }
    }
}

/**
 * @brief æŸ¥æ‰¾æœ€è¿‘çš„å¯è¾¾ç›®æ ‡
 */
AActor* ASG_AIControllerBase::FindNearestReachableTarget()
{
    ASG_UnitsBase* ControlledUnit = Cast<ASG_UnitsBase>(GetPawn());
    if (!ControlledUnit)
    {
        return nullptr;
    }

    UWorld* World = GetWorld();
    if (!World)
    {
        return nullptr;
    }

    if (USG_TargetingSubsystem* TargetingSys = World->GetSubsystem<USG_TargetingSubsystem>())
    {
        TArray<FSGTargetCandidate> Candidates;

        AActor* BestTarget = TargetingSys->FindBestTarget(
            ControlledUnit,
            ControlledUnit->GetDetectionRange(),
            Candidates,
            UnreachableTargets
        );

        return BestTarget;
    }

    return nullptr;
}

/**
 * @brief æŸ¥æ‰¾æœ€è¿‘çš„ç›®æ ‡
 */
AActor* ASG_AIControllerBase::FindNearestTarget()
{
    ASG_UnitsBase* ControlledUnit = Cast<ASG_UnitsBase>(GetPawn());
    if (!ControlledUnit)
    {
        return nullptr;
    }

    UWorld* World = GetWorld();
    if (!World)
    {
        return nullptr;
    }

    if (USG_TargetingSubsystem* TargetingSys = World->GetSubsystem<USG_TargetingSubsystem>())
    {
        TArray<FSGTargetCandidate> Candidates;
        
        AActor* BestTarget = TargetingSys->FindBestTarget(
            ControlledUnit,
            ControlledUnit->GetDetectionRange(),
            Candidates,
            UnreachableTargets
        );

        if (BestTarget)
        {
            bool bTargetIsMainCity = BestTarget->IsA(ASG_MainCityBase::StaticClass());
            if (UBlackboardComponent* BB = GetBlackboardComponent())
            {
                BB->SetValueAsBool(BB_IsTargetMainCity, bTargetIsMainCity);
            }

            return BestTarget;
        }
    }

    if (USG_CombatTargetManager* CombatManager = World->GetSubsystem<USG_CombatTargetManager>())
    {
        AActor* Target = CombatManager->FindBestTargetWithSlot(ControlledUnit);
        if (Target)
        {
            return Target;
        }
    }

    return nullptr;
}

/**
 * @brief æ£€æµ‹å‘¨è¾¹å¨èƒ
 */
bool ASG_AIControllerBase::DetectNearbyThreats(float DetectionRadius)
{
    if (!CanSwitchTarget())
    {
        return false;
    }
    
    ASG_UnitsBase* ControlledUnit = Cast<ASG_UnitsBase>(GetPawn());
    if (!ControlledUnit)
    {
        return false;
    }
    
    AActor* CurrentTarget = GetCurrentTarget();
    
    // åªæœ‰æ”»å‡»ä¸»åŸæ—¶æ‰æ£€æµ‹å¨èƒ
    UBlackboardComponent* BlackboardComp = GetBlackboardComponent();
    if (BlackboardComp && !BlackboardComp->GetValueAsBool(BB_IsTargetMainCity))
    {
        return false;
    }
    
    FGameplayTag MyFaction = ControlledUnit->FactionTag;
    
    TArray<AActor*> AllUnits;
    UGameplayStatics::GetAllActorsOfClass(GetWorld(), ASG_UnitsBase::StaticClass(), AllUnits);
    
    for (AActor* Actor : AllUnits)
    {
        if (Actor == ControlledUnit || Actor == CurrentTarget)
        {
            continue;
        }
        
        ASG_UnitsBase* Unit = Cast<ASG_UnitsBase>(Actor);
        if (!Unit)
        {
            continue;
        }
        
        if (Unit->FactionTag != MyFaction)
        {
            if (Unit->bIsDead || !Unit->CanBeTargeted())
            {
                continue;
            }
            
            float Distance = FVector::Dist(ControlledUnit->GetActorLocation(), Unit->GetActorLocation());
            
            if (Distance <= DetectionRadius)
            {
                SetCurrentTarget(Unit);
                StopMovement();
                return true;
            }
        }
    }
    
    return false;
}

// ğŸ”§ ä¿®æ”¹ - SetCurrentTarget å‡½æ•°ï¼ˆåœ¨å¼€å¤´æ·»åŠ é”å®šæ£€æŸ¥ï¼‰
/**
 * @brief è®¾ç½®å½“å‰ç›®æ ‡
 * @param NewTarget æ–°ç›®æ ‡
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - âœ¨ æ–°å¢ï¼šæ”»å‡»é”å®šæœŸé—´ä¸å…è®¸åˆ‡æ¢ç›®æ ‡
 */
void ASG_AIControllerBase::SetCurrentTarget(AActor* NewTarget)
{
    // âœ¨ æ–°å¢ - æ”»å‡»é”å®šæ£€æŸ¥
    ASG_UnitsBase* ControlledUnit = Cast<ASG_UnitsBase>(GetPawn());
    if (ControlledUnit && ControlledUnit->IsAttackLocked())
    {
        UE_LOG(LogSGGameplay, Verbose, TEXT("ğŸ”’ AI: %s æ”»å‡»é”å®šä¸­ï¼Œæ‹’ç»åˆ‡æ¢ç›®æ ‡"), 
            *ControlledUnit->GetName());
        return;
    }
    
    
    UBlackboardComponent* BlackboardComp = GetBlackboardComponent();
    if (!BlackboardComp)
    {
        return;
    }

    AActor* OldTarget = GetCurrentTarget();
    
    if (OldTarget == NewTarget)
    {
        return;
    }

    UWorld* World = GetWorld();
    USG_TargetingSubsystem* TargetingSys = World ? World->GetSubsystem<USG_TargetingSubsystem>() : nullptr;
    USG_CombatTargetManager* CombatManager = World ? World->GetSubsystem<USG_CombatTargetManager>() : nullptr;
    bool bShouldOccupySlot = ShouldOccupyAttackSlot();

    // 1. å¤„ç†æ—§ç›®æ ‡æ³¨é”€
    if (OldTarget && ControlledUnit)
    {
        // åªæœ‰éä¸»åŸç›®æ ‡ä¸”éœ€è¦æ§½ä½æ—¶æ‰é‡Šæ”¾æ§½ä½
        if (bShouldOccupySlot && !OldTarget->IsA(ASG_MainCityBase::StaticClass()))
        {
            if (CombatManager)
            {
                CombatManager->ReleaseAttackSlot(ControlledUnit, OldTarget);
            }
        }

        if (TargetingSys)
        {
            TargetingSys->UnregisterAttacker(ControlledUnit, OldTarget);
        }
    }
    
    // è§£ç»‘æ—§ç›®æ ‡æ­»äº¡äº‹ä»¶
    if (CurrentListenedTarget.IsValid())
    {
        UnbindTargetDeathEvent(CurrentListenedTarget.Get());
        CurrentListenedTarget = nullptr;
    }
    
    // æ›´æ–°é»‘æ¿
    BlackboardComp->SetValueAsObject(BB_CurrentTarget, NewTarget);
    
    // æ£€æŸ¥æ–°ç›®æ ‡æ˜¯å¦æ˜¯ä¸»åŸ
    bool bTargetIsMainCity = false;
    ASG_MainCityBase* TargetMainCity = nullptr;
    if (NewTarget)
    {
        TargetMainCity = Cast<ASG_MainCityBase>(NewTarget);
        bTargetIsMainCity = (TargetMainCity != nullptr);
    }
    
    BlackboardComp->SetValueAsBool(BB_IsTargetMainCity, bTargetIsMainCity);
    BlackboardComp->SetValueAsBool(BB_IsTargetLocked, NewTarget != nullptr);
    
    // æ›´æ–°å•ä½çš„ç›®æ ‡
    if (ControlledUnit)
    {
        ControlledUnit->SetTarget(NewTarget);
    }
    
    // 2. å¤„ç†æ–°ç›®æ ‡æ³¨å†Œå’Œç§»åŠ¨
    if (NewTarget && ControlledUnit)
    {
        // ç»‘å®šå•ä½æ­»äº¡äº‹ä»¶ï¼ˆä¸»åŸæ²¡æœ‰æ­»äº¡äº‹ä»¶ï¼‰
        if (ASG_UnitsBase* TargetUnit = Cast<ASG_UnitsBase>(NewTarget))
        {
            BindTargetDeathEvent(TargetUnit);
            CurrentListenedTarget = TargetUnit;
        }

        // æ³¨å†Œæ”»å‡»è€…
        if (TargetingSys)
        {
            TargetingSys->RegisterAttacker(ControlledUnit, NewTarget);
        }
        
        // æ ¹æ®ç›®æ ‡ç±»å‹è®¡ç®—ç§»åŠ¨ä½ç½®
        FVector MoveDestination;
        float AcceptanceRadius;
        float AttackRange = ControlledUnit->GetAttackRangeForAI();
        
        if (bTargetIsMainCity && TargetMainCity)
        {
            // ========== ä¸»åŸç›®æ ‡ - ä¸ä½¿ç”¨æ§½ä½ç³»ç»Ÿ ==========
            FVector CityLocation = TargetMainCity->GetActorLocation();
            FVector UnitLocation = ControlledUnit->GetActorLocation();
            
            FVector DirectionToUnit = (UnitLocation - CityLocation);
            DirectionToUnit.Z = 0.0f;
            DirectionToUnit.Normalize();
            
            if (DirectionToUnit.IsNearlyZero())
            {
                DirectionToUnit = FVector(1.0f, 0.0f, 0.0f);
            }
            
            float CityRadius = 800.0f;
            if (TargetMainCity->GetAttackDetectionBox())
            {
                FVector BoxExtent = TargetMainCity->GetAttackDetectionBox()->GetScaledBoxExtent();
                CityRadius = FMath::Max(BoxExtent.X, BoxExtent.Y);
            }
            
            float StandDistance = CityRadius + (AttackRange * 0.7f);
            
            MoveDestination = CityLocation + (DirectionToUnit * StandDistance);
            MoveDestination.Z = UnitLocation.Z;
            
            AcceptanceRadius = AttackRange * 0.5f;
        }
        else
        {
            // ========== æ™®é€šå•ä½ç›®æ ‡ ==========
            MoveDestination = NewTarget->GetActorLocation();
            AcceptanceRadius = AttackRange * 0.8f;
            
            // åªæœ‰éœ€è¦å ç”¨æ§½ä½çš„å•ä½æ‰é¢„çº¦æ§½ä½
            if (bShouldOccupySlot && CombatManager)
            {
                FVector SlotPosition;
                if (CombatManager->TryReserveAttackSlot(ControlledUnit, NewTarget, SlotPosition))
                {
                    MoveDestination = SlotPosition;
                    AcceptanceRadius = 30.0f;
                }
            }
        }
        
        // è®¾ç½®çŠ¶æ€ä¸ºç§»åŠ¨ä¸­å¹¶ç«‹å³å¼€å§‹ç§»åŠ¨
        SetTargetEngagementState(ESGTargetEngagementState::Moving);
        ResetMovementTimer();
        
        // ç«‹å³å¼€å§‹ç§»åŠ¨
        MoveToLocation(MoveDestination, AcceptanceRadius, true, true, true);
    }
    else
    {
        SetTargetEngagementState(ESGTargetEngagementState::Searching);
    }
}

// ========== GetCurrentTarget ==========
AActor* ASG_AIControllerBase::GetCurrentTarget() const
{
    const UBlackboardComponent* BlackboardComp = GetBlackboardComponent();
    if (!BlackboardComp)
    {
        return nullptr;
    }
    
    return Cast<AActor>(BlackboardComp->GetValueAsObject(BB_CurrentTarget));
}

// ========== IsTargetValid ==========
bool ASG_AIControllerBase::IsTargetValid() const
{
    AActor* CurrentTarget = GetCurrentTarget();
    if (!CurrentTarget)
    {
        return false;
    }
    
    ASG_UnitsBase* TargetUnit = Cast<ASG_UnitsBase>(CurrentTarget);
    if (TargetUnit)
    {
        if (TargetUnit->bIsDead)
        {
            return false;
        }
        
        if (TargetUnit->AttributeSet && TargetUnit->AttributeSet->GetHealth() <= 0.0f)
        {
            return false;
        }
        
        if (!TargetUnit->CanBeTargeted())
        {
            return false;
        }
    }
    
    ASG_MainCityBase* TargetMainCity = Cast<ASG_MainCityBase>(CurrentTarget);
    if (TargetMainCity)
    {
        if (!TargetMainCity->IsAlive())
        {
            return false;
        }
    }
    
    return true;
}

/**
 * @brief æ£€æŸ¥å½“å‰æ§åˆ¶çš„å•ä½æ˜¯å¦éœ€è¦å ç”¨æ”»å‡»æ§½ä½
 */
bool ASG_AIControllerBase::ShouldOccupyAttackSlot() const
{
    ASG_UnitsBase* ControlledUnit = Cast<ASG_UnitsBase>(GetPawn());
    return ShouldUnitOccupyAttackSlot(ControlledUnit);
}

/**
 * @brief æ£€æŸ¥æŒ‡å®šå•ä½æ˜¯å¦éœ€è¦å ç”¨æ”»å‡»æ§½ä½
 */
bool ASG_AIControllerBase::ShouldUnitOccupyAttackSlot(const ASG_UnitsBase* Unit) const
{
    if (!Unit)
    {
        return false;
    }

    if (SlotOccupyingUnitTypes.IsEmpty())
    {
        return true;
    }

    return SlotOccupyingUnitTypes.HasTag(Unit->UnitTypeTag);
}

// ========== InterruptAttack ==========
void ASG_AIControllerBase::InterruptAttack()
{
    if (!bIsMainCity)
    {
        return;
    }
    
    bAttackInterrupted = true;
    
    UBlackboardComponent* BlackboardComp = GetBlackboardComponent();
    if (BlackboardComp)
    {
        BlackboardComp->SetValueAsBool(TEXT("AttackInterrupted"), true);
    }
}

// ========== ResumeAttack ==========
void ASG_AIControllerBase::ResumeAttack()
{
    if (!bIsMainCity)
    {
        return;
    }
    
    bAttackInterrupted = false;
    
    UBlackboardComponent* BlackboardComp = GetBlackboardComponent();
    if (BlackboardComp)
    {
        BlackboardComp->SetValueAsBool(TEXT("AttackInterrupted"), false);
    }
}

/**
 * @brief ç›®æ ‡æ­»äº¡å›è°ƒ
 * @param DeadUnit æ­»äº¡çš„å•ä½
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - âœ¨ æ–°å¢ï¼šå¦‚æœæ”»å‡»é”å®šä¸­ï¼Œä¸ç«‹å³å¤„ç†ï¼Œç­‰æ”»å‡»åŠ¨ç”»ç»“æŸåç”± CheckAndFindNewTargetAfterAttack å¤„ç†
 */
void ASG_AIControllerBase::OnTargetDeath(ASG_UnitsBase* DeadUnit)
{
    AActor* CurrentTarget = GetCurrentTarget();
    if (CurrentTarget != DeadUnit)
    {
        return;
    }


    // âœ¨ Test --- æ–°å¢ - æ”»å‡»é”å®šæ£€æŸ¥
    ASG_UnitsBase* ControlledUnit = Cast<ASG_UnitsBase>(GetPawn());
    if (ControlledUnit && ControlledUnit->IsAttackLocked())
    {
        // æ”»å‡»é”å®šæœŸé—´ï¼Œåªè®°å½•æ—¥å¿—ï¼Œä¸ç«‹å³åˆ‡æ¢ç›®æ ‡
        // ç›®æ ‡åˆ‡æ¢ä¼šåœ¨æ”»å‡»åŠ¨ç”»ç»“æŸåç”± UpdateTarget æœåŠ¡å¤„ç†
        UE_LOG(LogSGGameplay, Log, TEXT("ğŸ”’ AI: %s çš„ç›®æ ‡ %s æ­»äº¡ï¼Œä½†æ”»å‡»é”å®šä¸­ï¼Œå»¶è¿Ÿå¤„ç†"),
            *ControlledUnit->GetName(), *DeadUnit->GetName());
        return;
    }
    
    CurrentListenedTarget = nullptr;
    
    SetTargetEngagementState(ESGTargetEngagementState::Searching);
    
    UBlackboardComponent* BlackboardComp = GetBlackboardComponent();
    if (BlackboardComp)
    {
        BlackboardComp->SetValueAsObject(BB_CurrentTarget, nullptr);
        BlackboardComp->SetValueAsBool(BB_IsTargetLocked, false);
        BlackboardComp->SetValueAsBool(BB_IsTargetMainCity, false);
    }
    
    if (ASG_UnitsBase* AControlledUnit = Cast<ASG_UnitsBase>(GetPawn()))
    {
        AControlledUnit->SetTarget(nullptr);
    }
    
    UnreachableTargets.Remove(DeadUnit);
    
    AActor* NewTarget = FindNearestTarget();
    if (NewTarget)
    {
        SetCurrentTarget(NewTarget);
    }
}

// ========== BindTargetDeathEvent ==========
void ASG_AIControllerBase::BindTargetDeathEvent(ASG_UnitsBase* Target)
{
    if (!Target)
    {
        return;
    }
    
    Target->OnUnitDeathEvent.AddDynamic(this, &ASG_AIControllerBase::OnTargetDeath);
}

// ========== UnbindTargetDeathEvent ==========
void ASG_AIControllerBase::UnbindTargetDeathEvent(ASG_UnitsBase* Target)
{
    if (!Target)
    {
        return;
    }
    
    Target->OnUnitDeathEvent.RemoveDynamic(this, &ASG_AIControllerBase::OnTargetDeath);
}
