// ğŸ“„ æ–‡ä»¶ï¼šSource/Sguo/Private/Player/SG_PlayerController.cpp
// ğŸ”§ ä¿®æ”¹ - ä½è€¦åˆè®¡è°‹å¡å¤„ç†å®ç°

#include "Player/SG_PlayerController.h"
#include "EnhancedInputSubsystems.h"
#include "Debug/SG_LogCategories.h"
#include "Engine/LocalPlayer.h"
#include "CardsAndUnits/SG_CardDeckComponent.h"
#include "UIHud/SG_CardHandWidget.h"
#include "Blueprint/UserWidget.h"
#include "Actors/SG_PlacementPreview.h"
#include "Data/SG_CardDataBase.h"
#include "Data/SG_CharacterCardData.h"
#include "Data/SG_StrategyCardData.h"
#include "Units/SG_UnitsBase.h"
#include "Player/SG_Player.h"
#include "Buildings/SG_MainCityBase.h"
#include "Kismet/GameplayStatics.h"
// âœ¨ æ–°å¢ - è®¡è°‹æ•ˆæœåŸºç±»
#include "Strategies/SG_StrategyEffectBase.h"
#include "Strategies/SG_StrategyEffect_RollingLog.h"  // âœ¨ æ–°å¢

ASG_PlayerController::ASG_PlayerController()
{
	CardDeckComponent = CreateDefaultSubobject<USG_CardDeckComponent>(TEXT("CardDeckComponent"));
	bShowMouseCursor = true;
	DefaultMouseCursor = EMouseCursor::Default;
}

void ASG_PlayerController::BeginPlay()
{
	Super::BeginPlay();
	
	if (UEnhancedInputLocalPlayerSubsystem* Subsystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(GetLocalPlayer()))
	{
		if (DefaultMappingContext)
		{
			Subsystem->AddMappingContext(DefaultMappingContext, MappingContextPriority);
		}
	}
	
	if (CardHandWidgetClass && CardDeckComponent)
	{
		CardHandWidget = CreateWidget<USG_CardHandWidget>(this, CardHandWidgetClass);
		if (CardHandWidget)
		{
			CardHandWidget->InitializeCardHand(CardDeckComponent);
			CardHandWidget->AddToViewport();
		}
	}
	
	if (CardDeckComponent)
	{
		UE_LOG(LogTemp, Log, TEXT("PlayerController å‡†å¤‡åˆå§‹åŒ–å¡ç»„..."));
		CardDeckComponent->OnSelectionChanged.AddDynamic(this, &ASG_PlayerController::OnCardSelectionChanged);
		CardDeckComponent->InitializeDeck();
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ CardDeckComponent ä¸å­˜åœ¨ï¼"));
	}
	
	if (GetPawn())
	{
		UE_LOG(LogTemp, Log, TEXT("Pawn å·²å°±ç»ªï¼Œç«‹å³ç»‘å®šè¾“å…¥äº‹ä»¶"));
		BindPawnInputEvents();
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("âš ï¸ Pawn å°šæœªå°±ç»ªï¼Œç­‰å¾… OnPossess å›è°ƒ"));
	}
	
	UE_LOG(LogTemp, Log, TEXT("========================================"));
}

void ASG_PlayerController::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	// âœ¨ æ–°å¢ - æ ¹æ®å½“å‰æ¨¡å¼æ›´æ–°é¢„è§ˆ
	if (CurrentPlacementMode == ESGPlacementMode::StrategyTarget && ActiveStrategyEffect)
	{
		// æ›´æ–°è®¡è°‹æ•ˆæœé¢„è§ˆä½ç½®
		FVector MouseLocation;
		if (GetMouseGroundLocation(MouseLocation))
		{
			ActiveStrategyEffect->UpdateTargetLocation(MouseLocation);
		}
	}
	// CardPlacement æ¨¡å¼ç”± PlacementPreview Actor è‡ªå·±çš„ Tick å¤„ç†
}

void ASG_PlayerController::SetupInputComponent()
{
	Super::SetupInputComponent();
	UE_LOG(LogTemp, Log, TEXT("SetupInputComponent è¢«è°ƒç”¨"));
}

void ASG_PlayerController::OnPossess(APawn* InPawn)
{
	Super::OnPossess(InPawn);
	
	UE_LOG(LogTemp, Log, TEXT("========== OnPossess è¢«è°ƒç”¨ =========="));
	UE_LOG(LogTemp, Log, TEXT("Pawn: %s"), InPawn ? *InPawn->GetName() : TEXT("nullptr"));
	
	BindPawnInputEvents();
	
	UE_LOG(LogTemp, Log, TEXT("========================================"));
}

void ASG_PlayerController::BindPawnInputEvents()
{
	if (bPawnInputBound)
	{
		UE_LOG(LogTemp, Warning, TEXT("Pawn è¾“å…¥äº‹ä»¶å·²ç»‘å®šï¼Œè·³è¿‡"));
		return;
	}
	
	UE_LOG(LogTemp, Log, TEXT("========== ç»‘å®š Pawn è¾“å…¥äº‹ä»¶ =========="));
	
	ASG_Player* PlayerPawn = Cast<ASG_Player>(GetPawn());
	if (!PlayerPawn)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ æœªæ‰¾åˆ° PlayerPawnï¼"));
		return;
	}
	
	UE_LOG(LogTemp, Log, TEXT("æ‰¾åˆ° PlayerPawn: %s"), *PlayerPawn->GetName());
	
	PlayerPawn->OnConfirmInput.AddDynamic(this, &ASG_PlayerController::OnConfirmInput);
	UE_LOG(LogTemp, Log, TEXT("  âœ“ å·²ç»‘å®šç¡®è®¤è¾“å…¥ï¼ˆå·¦é”®ï¼‰"));
	
	PlayerPawn->OnCancelInput.AddDynamic(this, &ASG_PlayerController::OnCancelInput);
	UE_LOG(LogTemp, Log, TEXT("  âœ“ å·²ç»‘å®šå–æ¶ˆè¾“å…¥ï¼ˆå³é”®ï¼‰"));
	
	bPawnInputBound = true;
	
	UE_LOG(LogTemp, Log, TEXT("âœ“ Pawn è¾“å…¥äº‹ä»¶ç»‘å®šå®Œæˆ"));
	UE_LOG(LogTemp, Log, TEXT("========================================"));
}

USG_CardDeckComponent* ASG_PlayerController::GetCardDeckComponent() const
{
	return CardDeckComponent;
}

// ğŸ”§ ä¿®æ”¹ - StartCardPlacement ä½¿ç”¨é€šç”¨è®¡è°‹å¡å¤„ç†
void ASG_PlayerController::StartCardPlacement(USG_CardDataBase* CardData, const FGuid& CardInstanceId)
{
	if (!CardData)
	{
		UE_LOG(LogTemp, Error, TEXT("StartCardPlacement å¤±è´¥ï¼šCardData ä¸ºç©º"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("========== å¼€å§‹æ”¾ç½®å¡ç‰Œï¼š%s =========="), *CardData->CardName.ToString());

	// å–æ¶ˆä¹‹å‰çš„ä»»ä½•æ”¾ç½®æ¨¡å¼
	if (CurrentPlacementMode != ESGPlacementMode::None)
	{
		CancelPlacement();
	}

	// âœ¨ æ–°å¢ - æ£€æŸ¥æ˜¯å¦æ˜¯è®¡è°‹å¡
	USG_StrategyCardData* StrategyCard = Cast<USG_StrategyCardData>(CardData);
	if (StrategyCard)
	{
		// æ£€æŸ¥æ˜¯å¦éœ€è¦ç›®æ ‡é€‰æ‹©
		if (!DoesCardRequirePreview(CardData))
		{
			// å…¨å±€æ•ˆæœï¼Œç›´æ¥ä½¿ç”¨
			UE_LOG(LogSGGameplay, Log, TEXT("  å…¨å±€æ•ˆæœå¡ç‰Œï¼Œç›´æ¥ä½¿ç”¨"));
			UseStrategyCardDirectly(StrategyCard, CardInstanceId);
			
			if (CardDeckComponent)
			{
				CardDeckComponent->SelectCard(FGuid());
			}
			return;
		}
		else
		{
			// éœ€è¦ç›®æ ‡é€‰æ‹©çš„è®¡è°‹å¡
			UE_LOG(LogSGGameplay, Log, TEXT("  è®¡è°‹å¡éœ€è¦ç›®æ ‡é€‰æ‹©"));
			StartStrategyTargetSelection(StrategyCard, CardInstanceId);
			return;
		}
	}

	// è§’è‰²å¡ï¼Œä½¿ç”¨æ™®é€šæ”¾ç½®é¢„è§ˆ
	if (!PlacementPreviewClass)
	{
		UE_LOG(LogTemp, Error, TEXT("StartCardPlacement å¤±è´¥ï¼šPlacementPreviewClass æœªè®¾ç½®"));
		return;
	}

	CurrentSelectedCardData = CardData;
	CurrentSelectedCardInstanceId = CardInstanceId;
	CurrentPlacementMode = ESGPlacementMode::CardPlacement;

	FActorSpawnParameters SpawnParams;
	SpawnParams.Owner = this;
	SpawnParams.Instigator = GetPawn();

	CurrentPreviewActor = GetWorld()->SpawnActor<ASG_PlacementPreview>(
		PlacementPreviewClass,
		FVector::ZeroVector,
		FRotator::ZeroRotator,
		SpawnParams
	);

	if (CurrentPreviewActor)
	{
		CurrentPreviewActor->InitializePreview(CardData, this);
		UE_LOG(LogTemp, Log, TEXT("âœ“ é¢„è§ˆ Actor å·²ç”Ÿæˆ"));
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ é¢„è§ˆ Actor ç”Ÿæˆå¤±è´¥"));
		CurrentPlacementMode = ESGPlacementMode::None;
	}
}

// ğŸ”§ ä¿®æ”¹ - ConfirmPlacement æ ¹æ®æ¨¡å¼å¤„ç†
void ASG_PlayerController::ConfirmPlacement()
{
	UE_LOG(LogTemp, Log, TEXT("========== ç¡®è®¤æ”¾ç½® =========="));

	switch (CurrentPlacementMode)
	{
	case ESGPlacementMode::StrategyTarget:
		// è®¡è°‹å¡ç›®æ ‡é€‰æ‹©æ¨¡å¼
		ConfirmStrategyTarget();
		return;

	case ESGPlacementMode::CardPlacement:
		// æ™®é€šå¡ç‰Œæ”¾ç½®æ¨¡å¼ï¼Œç»§ç»­åŸæœ‰é€»è¾‘
		break;

	default:
		UE_LOG(LogTemp, Warning, TEXT("ConfirmPlacement å¤±è´¥ï¼šæ— æ”¾ç½®æ¨¡å¼"));
		return;
	}

	// æ™®é€šå¡ç‰Œæ”¾ç½®é€»è¾‘
	if (!CurrentPreviewActor)
	{
		UE_LOG(LogTemp, Warning, TEXT("ConfirmPlacement å¤±è´¥ï¼šæ— é¢„è§ˆ Actor"));
		return;
	}

	if (!CurrentPreviewActor->CanPlaceAtCurrentLocation())
	{
		UE_LOG(LogTemp, Warning, TEXT("ConfirmPlacement å¤±è´¥ï¼šå½“å‰ä½ç½®ä¸å¯æ”¾ç½®"));
		return;
	}

	if (!CurrentSelectedCardData)
	{
		UE_LOG(LogTemp, Error, TEXT("ConfirmPlacement å¤±è´¥ï¼šå¡ç‰Œæ•°æ®ä¸ºç©º"));
		CancelPlacement();
		return;
	}

	FVector UnitSpawnLocation = CurrentPreviewActor->GetPreviewLocation();
	FRotator UnitSpawnRotation = CalculateUnitSpawnRotation(UnitSpawnLocation);

	UE_LOG(LogSGGameplay, Log, TEXT("æ”¾ç½®ä½ç½®ï¼š%s"), *UnitSpawnLocation.ToString());
	UE_LOG(LogSGGameplay, Log, TEXT("æ”¾ç½®æ—‹è½¬ï¼š%s"), *UnitSpawnRotation.ToString());

	// ç”Ÿæˆå•ä½
	SpawnUnitFromCard(CurrentSelectedCardData, UnitSpawnLocation, UnitSpawnRotation);

	// ä½¿ç”¨å¡ç‰Œ
	if (CardDeckComponent)
	{
		bool bSuccess = CardDeckComponent->UseCard(CurrentSelectedCardInstanceId);
		if (bSuccess)
		{
			UE_LOG(LogTemp, Log, TEXT("âœ“ å¡ç‰Œä½¿ç”¨æˆåŠŸï¼Œè¿›å…¥å†·å´"));
		}
		else
		{
			UE_LOG(LogTemp, Error, TEXT("âŒ å¡ç‰Œä½¿ç”¨å¤±è´¥"));
		}
	}

	// æ¸…ç†
	if (CurrentPreviewActor)
	{
		CurrentPreviewActor->Destroy();
		CurrentPreviewActor = nullptr;
	}

	CurrentSelectedCardData = nullptr;
	CurrentSelectedCardInstanceId.Invalidate();
	CurrentPlacementMode = ESGPlacementMode::None;

	UE_LOG(LogTemp, Log, TEXT("âœ“ æ”¾ç½®å®Œæˆ"));
	UE_LOG(LogTemp, Log, TEXT("========================================"));
}

// ğŸ”§ ä¿®æ”¹ - CancelPlacement æ ¹æ®æ¨¡å¼å¤„ç†
void ASG_PlayerController::CancelPlacement()
{
	UE_LOG(LogTemp, Log, TEXT("========== å–æ¶ˆæ”¾ç½® =========="));

	// 1. å¦‚æœæ˜¯è®¡è°‹æ¨¡å¼ï¼Œè½¬äº¤ç»™ä¸“ç”¨å‡½æ•°ï¼ˆè¯¥å‡½æ•°å†…éƒ¨å·²æ­£ç¡®å¤„ç†ï¼‰
	if (CurrentPlacementMode == ESGPlacementMode::StrategyTarget)
	{
		CancelStrategyTargetSelection();
		return;
	}

	// 2. å¦‚æœå½“å‰æœ¬æ¥å°±æ²¡åœ¨æ”¾ç½®ï¼Œç›´æ¥è¿”å›
	if (CurrentPlacementMode == ESGPlacementMode::None)
	{
		return;
	}

	// 3. ã€å…³é”®ä¿®å¤ã€‘å…ˆé‡ç½®çŠ¶æ€ï¼Œå†æ‰§è¡Œå¯èƒ½ä¼šè§¦å‘å›è°ƒçš„æ“ä½œ
	// ä¿å­˜éœ€è¦æ¸…ç†çš„å˜é‡
	FGuid InstanceIdToDeselect = CurrentSelectedCardInstanceId;
	
	// ç«‹å³é‡ç½®çŠ¶æ€ï¼Œæ‰“æ–­ SelectCard -> OnSelectionChanged -> CancelPlacement çš„é—­ç¯
	CurrentSelectedCardData = nullptr;
	CurrentSelectedCardInstanceId.Invalidate();
	CurrentPlacementMode = ESGPlacementMode::None;

	// 4. é”€æ¯é¢„è§ˆ Actor
	if (CurrentPreviewActor)
	{
		CurrentPreviewActor->Destroy();
		CurrentPreviewActor = nullptr;
		UE_LOG(LogTemp, Log, TEXT("âœ“ é¢„è§ˆ Actor å·²é”€æ¯"));
	}

	// 5. è°ƒç”¨å¤–éƒ¨ç»„ä»¶æ–¹æ³•ï¼ˆè¿™ä¼šè§¦å‘ OnSelectionChangedï¼Œä½†æ­¤æ—¶ Mode å·²ç»æ˜¯ Noneï¼Œä¸ä¼šå¯¼è‡´é€’å½’ï¼‰
	if (CardDeckComponent && InstanceIdToDeselect.IsValid())
	{
		CardDeckComponent->SelectCard(FGuid());
		UE_LOG(LogTemp, Log, TEXT("âœ“ å·²å–æ¶ˆé€‰ä¸­å¡ç‰Œ"));
	}

	UE_LOG(LogTemp, Log, TEXT("========================================"));
}

// ========== âœ¨ æ–°å¢ - é€šç”¨è®¡è°‹å¡æ¥å£å®ç° ==========

bool ASG_PlayerController::StartStrategyTargetSelection(USG_StrategyCardData* StrategyCardData, const FGuid& CardInstanceId)
{
	UE_LOG(LogSGGameplay, Log, TEXT("========== å¼€å§‹è®¡è°‹ç›®æ ‡é€‰æ‹© =========="));

	if (!StrategyCardData)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("  âŒ è®¡è°‹å¡æ•°æ®ä¸ºç©º"));
		return false;
	}

	// æ£€æŸ¥æ•ˆæœç±»æ˜¯å¦è®¾ç½®
	if (!StrategyCardData->EffectActorClass)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("  âŒ EffectActorClass æœªè®¾ç½®ï¼"));
		return false;
	}

	// è·å–é¼ æ ‡åˆå§‹ä½ç½®
	FVector InitialLocation;
	if (!GetMouseGroundLocation(InitialLocation))
	{
		UE_LOG(LogSGGameplay, Warning, TEXT("  âš ï¸ æ— æ³•è·å–é¼ æ ‡ä½ç½®ï¼Œä½¿ç”¨åŸç‚¹"));
		InitialLocation = FVector::ZeroVector;
	}

	// ç”Ÿæˆæ•ˆæœ Actor
	FActorSpawnParameters SpawnParams;
	SpawnParams.Owner = this;
	SpawnParams.Instigator = GetPawn();

	ActiveStrategyEffect = GetWorld()->SpawnActor<ASG_StrategyEffectBase>(
		StrategyCardData->EffectActorClass,
		InitialLocation,
		FRotator::ZeroRotator,
		SpawnParams
	);

	if (!ActiveStrategyEffect)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("  âŒ æ•ˆæœ Actor ç”Ÿæˆå¤±è´¥"));
		return false;
	}

	// åˆå§‹åŒ–æ•ˆæœ
	ActiveStrategyEffect->InitializeEffect(
		StrategyCardData,
		GetPawn(),
		InitialLocation
	);

	// ç»‘å®šå®Œæˆå›è°ƒ
	ActiveStrategyEffect->OnEffectFinished.AddDynamic(this, &ASG_PlayerController::OnStrategyEffectFinished);

	// å¼€å§‹ç›®æ ‡é€‰æ‹©ï¼ˆæ•ˆæœç±»è‡ªå·±è´Ÿè´£é¢„è§ˆæ˜¾ç¤ºï¼‰
	if (!ActiveStrategyEffect->StartTargetSelection())
	{
		// å¼€å§‹å¤±è´¥ï¼ˆå¯èƒ½æ˜¯æ¡ä»¶ä¸æ»¡è¶³ï¼‰
		FText Reason = ActiveStrategyEffect->GetCannotExecuteReason();
		UE_LOG(LogSGGameplay, Warning, TEXT("  âš ï¸ æ— æ³•å¼€å§‹ç›®æ ‡é€‰æ‹©ï¼š%s"), *Reason.ToString());
		
		// æ¸…ç†
		ActiveStrategyEffect->Destroy();
		ActiveStrategyEffect = nullptr;
		
		// å–æ¶ˆå¡ç‰Œé€‰ä¸­
		if (CardDeckComponent)
		{
			CardDeckComponent->SelectCard(FGuid());
		}
		
		return false;
	}

	// ä¿å­˜å¡ç‰Œå®ä¾‹ ID
	StrategyCardInstanceId = CardInstanceId;

	// è®¾ç½®å½“å‰æ¨¡å¼
	CurrentPlacementMode = ESGPlacementMode::StrategyTarget;

	UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ è®¡è°‹ç›®æ ‡é€‰æ‹©å·²å¼€å§‹"));
	UE_LOG(LogSGGameplay, Log, TEXT("    æ•ˆæœç±»ï¼š%s"), *StrategyCardData->EffectActorClass->GetName());
	UE_LOG(LogSGGameplay, Log, TEXT("========================================"));

	return true;
}

bool ASG_PlayerController::ConfirmStrategyTarget()
{
	UE_LOG(LogSGGameplay, Log, TEXT("========== ç¡®è®¤è®¡è°‹ç›®æ ‡ =========="));

	if (CurrentPlacementMode != ESGPlacementMode::StrategyTarget)
	{
		UE_LOG(LogSGGameplay, Warning, TEXT("  âš ï¸ å½“å‰ä¸åœ¨è®¡è°‹ç›®æ ‡é€‰æ‹©æ¨¡å¼"));
		return false;
	}

	if (!ActiveStrategyEffect)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("  âŒ æ•ˆæœ Actor ä¸ºç©º"));
		CancelStrategyTargetSelection();
		return false;
	}

	// ğŸ”§ ä¿®æ”¹ - å…ˆä¿å­˜éœ€è¦çš„æ•°æ®
	FGuid CardIdToUse = StrategyCardInstanceId;
	
	// è°ƒç”¨æ•ˆæœçš„ç¡®è®¤æ–¹æ³•ï¼ˆæ•ˆæœç±»è‡ªå·±è´Ÿè´£éªŒè¯å’Œæ‰§è¡Œï¼‰
	bool bSuccess = ActiveStrategyEffect->ConfirmTarget();

	if (bSuccess)
	{
		UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ è®¡è°‹ç›®æ ‡ç¡®è®¤æˆåŠŸ"));

		// ğŸ”§ ä¿®æ”¹ - å…ˆæ¸…ç†çŠ¶æ€ï¼Œé˜²æ­¢ UseCard è§¦å‘çš„ OnSelectionChanged å›è°ƒå¯¼è‡´å–æ¶ˆ
		ActiveStrategyEffect = nullptr;
		StrategyCardInstanceId.Invalidate();
		CurrentPlacementMode = ESGPlacementMode::None;

		// ä½¿ç”¨å¡ç‰Œï¼ˆè¿™ä¼šè§¦å‘ OnSelectionChangedï¼Œä½†æ­¤æ—¶ CurrentPlacementMode å·²ç»æ˜¯ Noneï¼‰
		if (CardDeckComponent && CardIdToUse.IsValid())
		{
			bool bCardUsed = CardDeckComponent->UseCard(CardIdToUse);
			if (bCardUsed)
			{
				UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ å¡ç‰Œä½¿ç”¨æˆåŠŸï¼Œè¿›å…¥å†·å´"));
			}
			else
			{
				UE_LOG(LogSGGameplay, Error, TEXT("  âŒ å¡ç‰Œä½¿ç”¨å¤±è´¥"));
			}
		}
	}
	else
	{
		UE_LOG(LogSGGameplay, Warning, TEXT("  âš ï¸ è®¡è°‹ç›®æ ‡ç¡®è®¤å¤±è´¥"));
	}

	UE_LOG(LogSGGameplay, Log, TEXT("========================================"));
	return bSuccess;
}

void ASG_PlayerController::CancelStrategyTargetSelection()
{
	UE_LOG(LogSGGameplay, Log, TEXT("========== å–æ¶ˆè®¡è°‹ç›®æ ‡é€‰æ‹© =========="));

	// å–æ¶ˆæ•ˆæœ
	if (ActiveStrategyEffect)
	{
		// è§£ç»‘å›è°ƒï¼ˆé˜²æ­¢é”€æ¯æ—¶è§¦å‘ï¼‰
		ActiveStrategyEffect->OnEffectFinished.RemoveDynamic(this, &ASG_PlayerController::OnStrategyEffectFinished);
		ActiveStrategyEffect->CancelEffect();
		ActiveStrategyEffect = nullptr;
		UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ æ•ˆæœ Actor å·²å–æ¶ˆ"));
	}

	// æ¸…ç†çŠ¶æ€
	StrategyCardInstanceId.Invalidate();
	CurrentPlacementMode = ESGPlacementMode::None;

	// å–æ¶ˆå¡ç‰Œé€‰ä¸­
	if (CardDeckComponent)
	{
		CardDeckComponent->SelectCard(FGuid());
		UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ å·²å–æ¶ˆé€‰ä¸­å¡ç‰Œ"));
	}

	UE_LOG(LogSGGameplay, Log, TEXT("========================================"));
}

void ASG_PlayerController::UseStrategyCardDirectly(USG_StrategyCardData* StrategyCardData, const FGuid& CardInstanceId)
{
	if (!StrategyCardData)
	{
		UE_LOG(LogTemp, Error, TEXT("UseStrategyCardDirectly å¤±è´¥ï¼šStrategyCardData ä¸ºç©º"));
		return;
	}
    
	UE_LOG(LogSGGameplay, Log, TEXT("========== ç›´æ¥ä½¿ç”¨è®¡è°‹å¡ï¼š%s =========="), 
		*StrategyCardData->CardName.ToString());
    
	// æ£€æŸ¥æ•ˆæœç±»æ˜¯å¦è®¾ç½®
	if (!StrategyCardData->EffectActorClass)
	{
		// å¦‚æœæ²¡æœ‰æ•ˆæœç±»ï¼Œå°è¯•ä½¿ç”¨çº¯ GE æ¨¡å¼
		if (StrategyCardData->GameplayEffectClass)
		{
			UE_LOG(LogSGGameplay, Log, TEXT("  ä½¿ç”¨çº¯ GE æ¨¡å¼"));
			
			// è·å–æ–½æ”¾è€…é˜µè¥
			FGameplayTag PlayerFactionTag = FGameplayTag::RequestGameplayTag(FName("Unit.Faction.Player"), false);
			
			// è·å–æ‰€æœ‰å‹æ–¹å•ä½
			TArray<AActor*> FriendlyUnits;
			TArray<AActor*> AllUnits;
			UGameplayStatics::GetAllActorsOfClass(GetWorld(), ASG_UnitsBase::StaticClass(), AllUnits);
			
			for (AActor* Actor : AllUnits)
			{
				ASG_UnitsBase* Unit = Cast<ASG_UnitsBase>(Actor);
				if (Unit && !Unit->bIsDead && Unit->FactionTag.MatchesTag(PlayerFactionTag))
				{
					FriendlyUnits.Add(Unit);
				}
			}
			
			UE_LOG(LogSGGameplay, Log, TEXT("  æ‰¾åˆ° %d ä¸ªå‹æ–¹å•ä½"), FriendlyUnits.Num());
			
			FGameplayTag DurationTag = FGameplayTag::RequestGameplayTag(FName("Data.Duration"), false);
			
			int32 SuccessCount = 0;
			for (AActor* Actor : FriendlyUnits)
			{
				ASG_UnitsBase* Unit = Cast<ASG_UnitsBase>(Actor);
				if (!Unit) continue;
				
				UAbilitySystemComponent* UnitASC = Unit->GetAbilitySystemComponent();
				if (!UnitASC) continue;
				
				FGameplayEffectContextHandle ContextHandle = UnitASC->MakeEffectContext();
				ContextHandle.AddInstigator(GetPawn(), GetPawn());
				
				FGameplayEffectSpecHandle SpecHandle = UnitASC->MakeOutgoingSpec(
					StrategyCardData->GameplayEffectClass, 
					1.0f, 
					ContextHandle
				);
				
				if (!SpecHandle.IsValid()) continue;
				
				if (DurationTag.IsValid())
				{
					SpecHandle.Data->SetSetByCallerMagnitude(DurationTag, StrategyCardData->Duration);
				}
				
				FActiveGameplayEffectHandle ActiveHandle = UnitASC->ApplyGameplayEffectSpecToSelf(*SpecHandle.Data.Get());
				
				if (ActiveHandle.IsValid())
				{
					SuccessCount++;
				}
			}
			
			UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ æˆåŠŸå¯¹ %d/%d ä¸ªå•ä½åº”ç”¨æ•ˆæœ"), 
				SuccessCount, FriendlyUnits.Num());
		}
		else
		{
			UE_LOG(LogSGGameplay, Error, TEXT("  âŒ GameplayEffectClass å’Œ EffectActorClass éƒ½æœªè®¾ç½®ï¼"));
			return;
		}
	}
	else
	{
		// ä½¿ç”¨æ•ˆæœ Actor æ¨¡å¼
		UE_LOG(LogSGGameplay, Log, TEXT("  ä½¿ç”¨æ•ˆæœ Actor æ¨¡å¼"));
		
		FVector EffectLocation = GetPawn() ? GetPawn()->GetActorLocation() : FVector::ZeroVector;
		
		FActorSpawnParameters SpawnParams;
		SpawnParams.Owner = this;
		SpawnParams.Instigator = GetPawn();
		
		ASG_StrategyEffectBase* EffectActor = GetWorld()->SpawnActor<ASG_StrategyEffectBase>(
			StrategyCardData->EffectActorClass,
			EffectLocation,
			FRotator::ZeroRotator,
			SpawnParams
		);
		
		if (EffectActor)
		{
			EffectActor->InitializeEffect(StrategyCardData, GetPawn(), EffectLocation);
			EffectActor->ExecuteEffect();
			UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ æ•ˆæœ Actor å·²ç”Ÿæˆå¹¶æ‰§è¡Œ"));
		}
		else
		{
			UE_LOG(LogSGGameplay, Error, TEXT("  âŒ æ•ˆæœ Actor ç”Ÿæˆå¤±è´¥"));
			return;
		}
	}
    
	// ä½¿ç”¨å¡ç‰Œ
	if (CardDeckComponent)
	{
		bool bSuccess = CardDeckComponent->UseCard(CardInstanceId);
		if (bSuccess)
		{
			UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ å¡ç‰Œä½¿ç”¨æˆåŠŸï¼Œè¿›å…¥å†·å´"));
		}
		else
		{
			UE_LOG(LogSGGameplay, Error, TEXT("  âŒ å¡ç‰Œä½¿ç”¨å¤±è´¥"));
		}
	}
    
	UE_LOG(LogSGGameplay, Log, TEXT("========================================"));
}

void ASG_PlayerController::OnStrategyEffectFinished(ASG_StrategyEffectBase* Effect, bool bSuccess)
{
	UE_LOG(LogSGGameplay, Log, TEXT("è®¡è°‹æ•ˆæœå®Œæˆå›è°ƒï¼š%s"), bSuccess ? TEXT("æˆåŠŸ") : TEXT("å¤±è´¥"));
	
	// å¦‚æœå½“å‰æ•ˆæœå°±æ˜¯å®Œæˆçš„æ•ˆæœï¼Œæ¸…ç†å¼•ç”¨
	if (ActiveStrategyEffect == Effect)
	{
		ActiveStrategyEffect = nullptr;
		StrategyCardInstanceId.Invalidate();
		CurrentPlacementMode = ESGPlacementMode::None;
	}
}

bool ASG_PlayerController::DoesCardRequirePreview(USG_CardDataBase* CardData) const
{
	if (!CardData)
	{
		return false;
	}
    
	// æ ¹æ®æ”¾ç½®ç±»å‹åˆ¤æ–­
	if (CardData->PlacementType == ESGPlacementType::Global)
	{
		UE_LOG(LogSGGameplay, Log, TEXT("  å¡ç‰Œ [%s] æ˜¯å…¨å±€æ•ˆæœï¼Œä¸éœ€è¦é¢„è§ˆ"), 
			*CardData->CardName.ToString());
		return false;
	}
    
	// Area å’Œ Single ç±»å‹éœ€è¦é¢„è§ˆ
	UE_LOG(LogSGGameplay, Log, TEXT("  å¡ç‰Œ [%s] éœ€è¦é€‰æ‹©ç›®æ ‡ä½ç½®"), 
		*CardData->CardName.ToString());
	return true;
}

bool ASG_PlayerController::GetMouseGroundLocation(FVector& OutLocation) const
{
	FVector WorldLocation, WorldDirection;
	if (!DeprojectMousePositionToWorld(WorldLocation, WorldDirection))
	{
		return false;
	}

	FHitResult HitResult;
	FVector TraceEnd = WorldLocation + WorldDirection * 50000.0f;
	
	FCollisionQueryParams QueryParams;
	QueryParams.AddIgnoredActor(GetPawn());
	
	if (GetWorld()->LineTraceSingleByChannel(HitResult, WorldLocation, TraceEnd, ECC_Visibility, QueryParams))
	{
		OutLocation = HitResult.ImpactPoint;
		return true;
	}

	return false;
}

// ========== è¾“å…¥å¤„ç† ==========

void ASG_PlayerController::OnConfirmInput()
{
	UE_LOG(LogTemp, Log, TEXT("ğŸ–±ï¸ æ”¶åˆ°ç¡®è®¤è¾“å…¥ï¼ˆå·¦é”®ç‚¹å‡»ï¼‰"));

	if (CurrentPlacementMode != ESGPlacementMode::None)
	{
		UE_LOG(LogTemp, Log, TEXT("  æ£€æµ‹åˆ°æ”¾ç½®æ¨¡å¼ï¼š%dï¼Œæ‰§è¡Œç¡®è®¤"), static_cast<int32>(CurrentPlacementMode));
		ConfirmPlacement();
	}
	else
	{
		UE_LOG(LogTemp, Verbose, TEXT("  æ— æ”¾ç½®æ¨¡å¼ï¼Œå¿½ç•¥è¾“å…¥"));
	}
}

void ASG_PlayerController::OnCancelInput()
{
	UE_LOG(LogTemp, Log, TEXT("ğŸ–±ï¸ æ”¶åˆ°å–æ¶ˆè¾“å…¥ï¼ˆå³é”®ç‚¹å‡»ï¼‰"));

	if (CurrentPlacementMode != ESGPlacementMode::None)
	{
		UE_LOG(LogTemp, Log, TEXT("  æ£€æµ‹åˆ°æ”¾ç½®æ¨¡å¼ï¼š%dï¼Œæ‰§è¡Œå–æ¶ˆ"), static_cast<int32>(CurrentPlacementMode));
		CancelPlacement();
	}
	else
	{
		UE_LOG(LogTemp, Verbose, TEXT("  æ— æ”¾ç½®æ¨¡å¼ï¼Œå¿½ç•¥è¾“å…¥"));
	}
}

void ASG_PlayerController::OnCardSelectionChanged(const FGuid& SelectedId)
{
	UE_LOG(LogTemp, Log, TEXT("OnCardSelectionChanged - ID: %s"), *SelectedId.ToString());

	if (SelectedId.IsValid())
	{
		if (CardDeckComponent)
		{
			const TArray<FSGCardInstance>& Hand = CardDeckComponent->GetHand();
			
			for (const FSGCardInstance& Card : Hand)
			{
				if (Card.InstanceId == SelectedId)
				{
					UE_LOG(LogTemp, Log, TEXT("æ‰¾åˆ°é€‰ä¸­çš„å¡ç‰Œï¼š%s"), *Card.CardData->CardName.ToString());
					StartCardPlacement(Card.CardData, Card.InstanceId);
					return;
				}
			}

			UE_LOG(LogTemp, Warning, TEXT("âš ï¸ æœªæ‰¾åˆ°é€‰ä¸­çš„å¡ç‰Œ"));
		}
	}
	else
	{
		// âœ¨ æ–°å¢ - åªæœ‰åœ¨æœ‰æ”¾ç½®æ¨¡å¼æ—¶æ‰å–æ¶ˆ
		// é˜²æ­¢ä½¿ç”¨å¡ç‰Œåè§¦å‘çš„é€‰ä¸­æ¸…é™¤å¯¼è‡´æ•ˆæœè¢«å–æ¶ˆ
		if (CurrentPlacementMode != ESGPlacementMode::None)
		{
			UE_LOG(LogTemp, Log, TEXT("å¡ç‰Œè¢«å–æ¶ˆé€‰ä¸­ï¼Œå–æ¶ˆæ”¾ç½®"));
			CancelPlacement();
		}
		else
		{
			UE_LOG(LogTemp, Verbose, TEXT("å¡ç‰Œè¢«å–æ¶ˆé€‰ä¸­ï¼Œä½†æ— æ”¾ç½®æ¨¡å¼ï¼Œå¿½ç•¥"));
		}
	}
}



void ASG_PlayerController::SpawnUnitFromCard(USG_CardDataBase* CardData, const FVector& UnitSpawnLocation, const FRotator& UnitSpawnRotation)
{
	
	if (!CardData)
	{
		UE_LOG(LogTemp, Error, TEXT("SpawnUnitFromCard å¤±è´¥ï¼šCardData ä¸ºç©º"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("========== ç”Ÿæˆå•ä½ï¼š%s =========="), *CardData->CardName.ToString());

	if (USG_CharacterCardData* CharacterCard = Cast<USG_CharacterCardData>(CardData))
	{
		if (!CharacterCard->CharacterClass)
		{
			UE_LOG(LogTemp, Error, TEXT("âŒ è§’è‰²å¡æ²¡æœ‰è®¾ç½® CharacterClass"));
			return;
		}

		UE_LOG(LogSGGameplay, Log, TEXT("å¡ç‰Œå€ç‡é…ç½®ï¼š"));
		UE_LOG(LogSGGameplay, Log, TEXT("  ç”Ÿå‘½å€¼å€ç‡ï¼š%.2f"), CharacterCard->HealthMultiplier);
		UE_LOG(LogSGGameplay, Log, TEXT("  ä¼¤å®³å€ç‡ï¼š%.2f"), CharacterCard->DamageMultiplier);
		UE_LOG(LogSGGameplay, Log, TEXT("  é€Ÿåº¦å€ç‡ï¼š%.2f"), CharacterCard->SpeedMultiplier);

		if (CharacterCard->bIsTroopCard)
		{
			UE_LOG(LogTemp, Log, TEXT("ç”Ÿæˆå…µå›¢ - é˜µå‹: %dx%d, é—´è·: %.0f"), 
				CharacterCard->TroopFormation.X, 
				CharacterCard->TroopFormation.Y,
				CharacterCard->TroopSpacing);

			int32 Rows = CharacterCard->TroopFormation.Y;
			int32 Cols = CharacterCard->TroopFormation.X;
			float Spacing = CharacterCard->TroopSpacing;

			FVector StartOffset = FVector(
				-(Cols - 1) * Spacing / 2.0f,
				-(Rows - 1) * Spacing / 2.0f,
				0.0f
			);

			for (int32 Row = 0; Row < Rows; ++Row)
			{
				for (int32 Col = 0; Col < Cols; ++Col)
				{
					FVector UnitOffset = FVector(
						Col * Spacing,
						Row * Spacing,
						0.0f
					);

					FVector FinalUnitLocation = UnitSpawnLocation + StartOffset + UnitOffset;

					FActorSpawnParameters SpawnParams;
					SpawnParams.Owner = this;
					SpawnParams.Instigator = GetPawn();
					SpawnParams.bDeferConstruction = true;

					AActor* SpawnedUnit = GetWorld()->SpawnActor<AActor>(
						CharacterCard->CharacterClass,
						FinalUnitLocation,
						UnitSpawnRotation,
						SpawnParams
					);

					if (SpawnedUnit)
					{
						if (ASG_UnitsBase* Unit = Cast<ASG_UnitsBase>(SpawnedUnit))
						{
							Unit->SourceCardData = CharacterCard;
							Unit->FinishSpawning(FTransform(UnitSpawnRotation, FinalUnitLocation));
						}
						else
						{
							SpawnedUnit->FinishSpawning(FTransform(UnitSpawnRotation, FinalUnitLocation));
						}
					}
				}
			}

			UE_LOG(LogTemp, Log, TEXT("âœ“ å…µå›¢ç”Ÿæˆå®Œæˆï¼Œå…± %d ä¸ªå•ä½"), Rows * Cols);
		}
		else
		{
			UE_LOG(LogTemp, Log, TEXT("ç”Ÿæˆè‹±é›„"));

			FActorSpawnParameters SpawnParams;
			SpawnParams.Owner = this;
			SpawnParams.Instigator = GetPawn();
			SpawnParams.bDeferConstruction = true;

			AActor* SpawnedUnit = GetWorld()->SpawnActor<AActor>(
				CharacterCard->CharacterClass,
				UnitSpawnLocation,
				UnitSpawnRotation,
				SpawnParams
			);

			if (SpawnedUnit)
			{
				if (ASG_UnitsBase* Unit = Cast<ASG_UnitsBase>(SpawnedUnit))
				{
					Unit->SourceCardData = CharacterCard;
					Unit->FinishSpawning(FTransform(UnitSpawnRotation, UnitSpawnLocation));
				}
				else
				{
					SpawnedUnit->FinishSpawning(FTransform(UnitSpawnRotation, UnitSpawnLocation));
				}
			}
		}
	}

	UE_LOG(LogTemp, Log, TEXT("========================================"));
}

ASG_MainCityBase* ASG_PlayerController::FindEnemyMainCity()
{
	if (CachedEnemyMainCity && IsValid(CachedEnemyMainCity))
	{
		return CachedEnemyMainCity;
	}
	
	TArray<AActor*> FoundMainCities;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), ASG_MainCityBase::StaticClass(), FoundMainCities);
	
	FGameplayTag EnemyFactionTag = FGameplayTag::RequestGameplayTag(TEXT("Unit.Faction.Enemy"));
	
	for (AActor* Actor : FoundMainCities)
	{
		ASG_MainCityBase* MainCity = Cast<ASG_MainCityBase>(Actor);
		if (MainCity && MainCity->FactionTag.MatchesTag(EnemyFactionTag))
		{
			CachedEnemyMainCity = MainCity;
			return CachedEnemyMainCity;
		}
	}
	
	return nullptr;
}

FRotator ASG_PlayerController::CalculateUnitSpawnRotation(const FVector& UnitLocation)
{
	ASG_MainCityBase* EnemyCity = FindEnemyMainCity();
	
	if (EnemyCity)
	{
		FVector DirectionToEnemy = EnemyCity->GetActorLocation() - UnitLocation;
		DirectionToEnemy.Z = 0.0f;
		DirectionToEnemy.Normalize();
		return DirectionToEnemy.Rotation();
	}
	
	return FRotator(0.0f, 0.0f, 0.0f);
}

