// ğŸ“„ æ–‡ä»¶ï¼šGameplayMechanics/SG_FrontLineManager.cpp

#include "Actors/SG_FrontLineManager.h"
#include "Components/SplineComponent.h"
#include "Components/BillboardComponent.h"
// âœ¨ æ–°å¢ - é™æ€ç½‘æ ¼ä½“ç»„ä»¶å¤´æ–‡ä»¶
#include "Components/StaticMeshComponent.h"
#include "Units/SG_UnitsBase.h"
#include "Buildings/SG_MainCityBase.h"
#include "Kismet/GameplayStatics.h"
#include "DrawDebugHelpers.h"
#include "Debug/SG_LogCategories.h"

/**
 * @brief æ„é€ å‡½æ•°
 * @details 
 * åˆå§‹åŒ–æµç¨‹ï¼š
 * 1. å¯ç”¨ Tick åŠŸèƒ½ï¼Œç”¨äºæ¯å¸§æ›´æ–°å‰çº¿ä½ç½®
 * 2. åˆ›å»ºæ ¹ç»„ä»¶
 * 3. åˆ›å»ºåŒæ–¹å‰çº¿æ ·æ¡çº¿ç»„ä»¶
 * 4. âœ¨ æ–°å¢ - åˆ›å»ºç©å®¶å‰çº¿å¯è§†åŒ–ç½‘æ ¼ä½“ç»„ä»¶
 * 5. åˆ›å»ºç¼–è¾‘å™¨å›¾æ ‡ç»„ä»¶
 * 6. è®¾ç½®æ ·æ¡çº¿åˆå§‹ç‚¹ä½
 */
ASG_FrontLineManager::ASG_FrontLineManager()
{
    // å¯ç”¨ Tickï¼Œæ¯å¸§æ›´æ–°å‰çº¿ä½ç½®
    // ç”¨äºå®æ—¶è¯»å–æœ€å‰æ–¹å•ä½ä½ç½®ï¼Œå®ç°é›¶å»¶è¿Ÿè·Ÿéš
    PrimaryActorTick.bCanEverTick = true;

    // åˆ›å»ºæ ¹ç»„ä»¶
    // ä½œä¸ºæ‰€æœ‰å­ç»„ä»¶çš„çˆ¶çº§ï¼Œæä¾›ç»Ÿä¸€çš„åæ ‡ç³»
    RootComp = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
    RootComponent = RootComp;

    // åˆ›å»ºç©å®¶å‰çº¿æ ·æ¡çº¿
    // ç”¨äºåœ¨ç¼–è¾‘å™¨å’Œè¿è¡Œæ—¶å¯è§†åŒ–ç©å®¶å‰çº¿ä½ç½®
    PlayerFrontLineSpline = CreateDefaultSubobject<USplineComponent>(TEXT("PlayerFrontLineSpline"));
    PlayerFrontLineSpline->SetupAttachment(RootComp);
    // æ¸…ç©ºé»˜è®¤ç‚¹
    PlayerFrontLineSpline->ClearSplinePoints();
    // æ·»åŠ åˆå§‹çš„ä¸¤ä¸ªç«¯ç‚¹ï¼ˆå½¢æˆä¸€æ¡ç«–çº¿ï¼‰
    // å·¦ç«¯ç‚¹ï¼šY = -2500
    PlayerFrontLineSpline->AddSplinePoint(FVector(0.0f, -2500.0f, 10.0f), ESplineCoordinateSpace::Local);
    // å³ç«¯ç‚¹ï¼šY = 2500
    PlayerFrontLineSpline->AddSplinePoint(FVector(0.0f, 2500.0f, 10.0f), ESplineCoordinateSpace::Local);

    // åˆ›å»ºæ•Œäººå‰çº¿æ ·æ¡çº¿
    // ç”¨äºåœ¨ç¼–è¾‘å™¨å’Œè¿è¡Œæ—¶å¯è§†åŒ–æ•Œäººå‰çº¿ä½ç½®
    EnemyFrontLineSpline = CreateDefaultSubobject<USplineComponent>(TEXT("EnemyFrontLineSpline"));
    EnemyFrontLineSpline->SetupAttachment(RootComp);
    // æ¸…ç©ºé»˜è®¤ç‚¹
    EnemyFrontLineSpline->ClearSplinePoints();
    // æ·»åŠ åˆå§‹çš„ä¸¤ä¸ªç«¯ç‚¹ï¼ˆå½¢æˆä¸€æ¡ç«–çº¿ï¼‰
    // å·¦ç«¯ç‚¹ï¼šY = -2500
    EnemyFrontLineSpline->AddSplinePoint(FVector(0.0f, -2500.0f, 10.0f), ESplineCoordinateSpace::Local);
    // å³ç«¯ç‚¹ï¼šY = 2500
    EnemyFrontLineSpline->AddSplinePoint(FVector(0.0f, 2500.0f, 10.0f), ESplineCoordinateSpace::Local);

    // âœ¨ æ–°å¢ - åˆ›å»ºç©å®¶å‰çº¿å¯è§†åŒ–ç½‘æ ¼ä½“
    // ç”¨äºåœ¨æ¸¸æˆè¿è¡Œæ—¶æ˜¾ç¤ºç©å®¶å‰çº¿çš„3Dæ¨¡å‹
    PlayerFrontLineMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("PlayerFrontLineMesh"));
    PlayerFrontLineMesh->SetupAttachment(RootComp);
    // è®¾ç½®åˆå§‹ä½ç½®ï¼ˆåœ¨æ ¹ç»„ä»¶ä½ç½®ï¼‰
    PlayerFrontLineMesh->SetRelativeLocation(FVector(0.0f, 0.0f, 0.0f));
    // è®¾ç½®åˆå§‹æ—‹è½¬ï¼ˆé¢å‘ Y è½´ï¼‰
    PlayerFrontLineMesh->SetRelativeRotation(FRotator(0.0f, 0.0f, 0.0f));
    // è®¾ç½®ç¢°æ’ï¼ˆä¸å‚ä¸ç¢°æ’ï¼‰
    PlayerFrontLineMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    // è®¾ç½®ä¸ºå¯è§
    PlayerFrontLineMesh->SetVisibility(true);
    // é»˜è®¤ä¸æŠ•å°„é˜´å½±ï¼ˆå¯æ ¹æ®éœ€è¦è°ƒæ•´ï¼‰
    PlayerFrontLineMesh->SetCastShadow(false);

    // åˆ›å»º Actor å¹¿å‘Šç‰Œ
    // åœ¨ç¼–è¾‘å™¨ä¸­æ˜¾ç¤ºå›¾æ ‡ï¼Œæ–¹ä¾¿åœ¨åœºæ™¯ä¸­å®šä½è¯¥ Actor
    ActorBillboard = CreateDefaultSubobject<UBillboardComponent>(TEXT("ActorBillboard"));
    ActorBillboard->SetupAttachment(RootComp);
    // è®¾ç½®å›¾æ ‡ä½ç½®ï¼ˆåœ¨æ ¹ç»„ä»¶ä¸Šæ–¹ 300 å•ä½ï¼‰
    ActorBillboard->SetRelativeLocation(FVector(0.0f, 0.0f, 300.0f));
    // è®¾ç½®å›¾æ ‡ç¼©æ”¾ï¼ˆ3å€å¤§å°ï¼Œæ›´å®¹æ˜“çœ‹åˆ°ï¼‰
    ActorBillboard->SetRelativeScale3D(FVector(3.0f, 3.0f, 3.0f));
    // ä»…åœ¨ç¼–è¾‘å™¨ä¸­æ˜¾ç¤º
    ActorBillboard->bIsEditorOnly = true;
    
    // åˆå§‹åŒ–å‰çº¿ä½ç½®ä¸ºåˆå§‹å€¼
    CurrentPlayerFrontLineX = InitialFrontLineX;
    CurrentEnemyFrontLineX = InitialFrontLineX;
}

/**
 * @brief BeginPlay ç”Ÿå‘½å‘¨æœŸå‡½æ•°
 * @details 
 * åˆå§‹åŒ–æµç¨‹ï¼š
 * 1. æŸ¥æ‰¾å¹¶ç¼“å­˜åŒæ–¹ä¸»åŸä½ç½®
 * 2. ç¡®å®šç©å®¶å’Œæ•Œäººçš„æ–¹å‘ï¼ˆå·¦/å³ï¼‰
 * 3. æ‰“å°åˆå§‹åŒ–æ—¥å¿—
 * 4. è®¾ç½®å‰çº¿åˆå§‹ä½ç½®
 * 5. ç«‹å³æ‰«æä¸€æ¬¡æœ€å‰æ–¹å•ä½
 * 6. æ›´æ–°å¯è§†åŒ–ï¼ˆæ ·æ¡çº¿ + ç½‘æ ¼ä½“ï¼‰
 * 7. å¯åŠ¨å®šæ—¶é‡æ–°æ‰«æ
 */
void ASG_FrontLineManager::BeginPlay()
{
    Super::BeginPlay();
    
    // æŸ¥æ‰¾å¹¶ç¼“å­˜ä¸»åŸä½ç½®
    // è¿™ä¸€æ­¥å¿…é¡»æœ€å…ˆæ‰§è¡Œï¼Œå› ä¸ºéœ€è¦æ ¹æ®ä¸»åŸä½ç½®ç¡®å®šç©å®¶æ–¹å‘
    FindAndCacheMainCities();
    
    // æ‰“å°åˆå§‹åŒ–ä¿¡æ¯åˆ°æ—¥å¿—
    UE_LOG(LogSGGameplay, Log, TEXT("========== å‰çº¿ç®¡ç†å™¨åˆå§‹åŒ– =========="));
    UE_LOG(LogSGGameplay, Log, TEXT("  ç©å®¶ä¸»åŸï¼šX = %.0f"), PlayerMainCityX);
    UE_LOG(LogSGGameplay, Log, TEXT("  æ•Œäººä¸»åŸï¼šX = %.0f"), EnemyMainCityX);
    UE_LOG(LogSGGameplay, Log, TEXT("  ç©å®¶åœ¨å·¦ä¾§ï¼š%s"), bPlayerOnLeftSide ? TEXT("æ˜¯") : TEXT("å¦"));
    UE_LOG(LogSGGameplay, Log, TEXT("  é‡æ–°æ‰«æé—´éš”ï¼š%.2f ç§’"), RescanInterval);
    UE_LOG(LogSGGameplay, Log, TEXT("  æ˜¾ç¤ºå‰çº¿ç½‘æ ¼ä½“ï¼š%s"), bShowPlayerFrontLineMesh ? TEXT("æ˜¯") : TEXT("å¦"));
    UE_LOG(LogSGGameplay, Log, TEXT("========================================"));
    
    // è®¾ç½®åˆå§‹ä½ç½®
    // æ¸¸æˆå¼€å§‹æ—¶ï¼ŒåŒæ–¹å‰çº¿éƒ½åœ¨ä¸­é—´ä½ç½®
    CurrentPlayerFrontLineX = InitialFrontLineX;
    CurrentEnemyFrontLineX = InitialFrontLineX;
    
    // ç«‹å³æ‰«æä¸€æ¬¡ï¼Œæ‰¾åˆ°åˆå§‹çš„æœ€å‰æ–¹å•ä½
    // è¿™æ ·å¯ä»¥ç¡®ä¿æ¸¸æˆå¼€å§‹æ—¶å°±æœ‰æ­£ç¡®çš„å‰çº¿ä½ç½®
    RescanFrontmostUnits();
    
    // æ›´æ–°å¯è§†åŒ–
    // æ ¹æ®å½“å‰å‰çº¿ä½ç½®æ›´æ–°æ ·æ¡çº¿å’Œç½‘æ ¼ä½“
    UpdateFrontLineVisualization();
    
    // å¯åŠ¨å®šæ—¶é‡æ–°æ‰«æï¼ˆå®šæœŸæŸ¥æ‰¾æ–°çš„æœ€å‰æ–¹å•ä½ï¼‰
    // ä½¿ç”¨å®šæ—¶å™¨ï¼Œæ¯éš” RescanInterval ç§’æ‰§è¡Œä¸€æ¬¡ RescanFrontmostUnits
    GetWorld()->GetTimerManager().SetTimer(
        RescanTimerHandle,                          // å®šæ—¶å™¨å¥æŸ„
        this,                                       // è°ƒç”¨å¯¹è±¡
        &ASG_FrontLineManager::RescanFrontmostUnits,// å›è°ƒå‡½æ•°
        RescanInterval,                             // é—´éš”æ—¶é—´
        true                                        // æ˜¯å¦å¾ªç¯
    );
}

/**
 * @brief æ¯å¸§æ›´æ–°ï¼ˆå®æ—¶è·Ÿéšç‰ˆï¼‰
 * @param DeltaTime è·ç¦»ä¸Šä¸€å¸§çš„æ—¶é—´é—´éš”ï¼ˆç§’ï¼‰
 * @details 
 * æ‰§è¡Œæµç¨‹ï¼š
 * 1. è°ƒç”¨çˆ¶ç±» Tick
 * 2. æ›´æ–°å‰çº¿ä½ç½®ï¼ˆä»ç¼“å­˜å•ä½è¯»å–å®æ—¶ä½ç½®ï¼‰
 * 3. ç»˜åˆ¶è°ƒè¯•ä¿¡æ¯
 * 
 * æ€§èƒ½è¯´æ˜ï¼š
 * - æ¯å¸§åªè¯»å–2ä¸ªå•ä½çš„ä½ç½®ï¼Œæ€§èƒ½å¼€é”€æå°
 * - ä¸éœ€è¦éå†æ‰€æœ‰å•ä½ï¼Œå¤æ‚åº¦ä¸º O(1)
 */
void ASG_FrontLineManager::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
    
    // æ¯å¸§æ›´æ–°å‰çº¿ä½ç½®ï¼ˆå®æ—¶è·Ÿéšå•ä½ï¼‰
    // ç›´æ¥ä»ç¼“å­˜çš„æœ€å‰æ–¹å•ä½è¯»å–ä½ç½®ï¼Œå®ç°é›¶å»¶è¿Ÿè·Ÿéš
    UpdateFrontLinePositionRealtime();
    
    // ç»˜åˆ¶è°ƒè¯•ä¿¡æ¯
    // å¦‚æœå¯ç”¨äº†è°ƒè¯•ç»˜åˆ¶ï¼Œæ˜¾ç¤ºå‰çº¿ã€åŒºåŸŸå’Œå•ä½æ ‡è®°
    if (bEnableDebugDraw)
    {
        DrawDebugInfo();
    }
}

/**
 * @brief æ›´æ–°å‰çº¿ä½ç½®ï¼ˆæ¯å¸§è°ƒç”¨ï¼Œå®æ—¶è·Ÿéšï¼‰
 * @details 
 * æ ¸å¿ƒé€»è¾‘ï¼š
 * 1. ä»ç¼“å­˜çš„æœ€å‰æ–¹å•ä½è¯»å–å®æ—¶ä½ç½®ï¼ˆæ— éœ€éå†æ‰€æœ‰å•ä½ï¼‰
 * 2. æ£€æŸ¥å•ä½æ˜¯å¦è¶Šè¿‡åˆå§‹çº¿ï¼ˆæ ¹æ® bOnlyTrackCrossedUnits é…ç½®ï¼‰
 * 3. è®¡ç®—æ–°çš„å‰çº¿ä½ç½®ï¼ˆå•ä½ä½ç½® + åç§»é‡ï¼‰
 * 4. ç›´æ¥è®¾ç½®å‰çº¿ä½ç½®ï¼ˆæ— æ’å€¼ï¼Œé›¶å»¶è¿Ÿï¼‰
 * 5. è°ƒæ•´å‰çº¿é—´è·ï¼Œé˜²æ­¢é‡å 
 * 6. æ›´æ–°å¯è§†åŒ–ï¼ˆæ ·æ¡çº¿ + ç½‘æ ¼ä½“ï¼‰
 * 
 * æ€§èƒ½ä¼˜åŒ–ï¼š
 * - åªè¯»å–2ä¸ªå•ä½çš„ä½ç½®ï¼ŒO(1) å¤æ‚åº¦
 * - æ— æ’å€¼è®¡ç®—ï¼Œç›´æ¥èµ‹å€¼
 * - åªåœ¨ä½ç½®æ”¹å˜æ—¶æ›´æ–°å¯è§†åŒ–
 * 
 * æ³¨æ„äº‹é¡¹ï¼š
 * - éœ€è¦ç¡®ä¿ç¼“å­˜çš„å•ä½æœ‰æ•ˆä¸”æœªæ­»äº¡
 * - æ ¹æ®ç©å®¶æ–¹å‘ï¼ˆå·¦/å³ï¼‰è®¡ç®—å‰çº¿ä½ç½®
 */
void ASG_FrontLineManager::UpdateFrontLinePositionRealtime()
{
    // è®°å½•æ˜¯å¦æœ‰å˜åŒ–
    // åªæœ‰åœ¨å‰çº¿ä½ç½®æ”¹å˜æ—¶æ‰æ›´æ–°å¯è§†åŒ–ï¼Œé¿å…ä¸å¿…è¦çš„è®¡ç®—
    bool bChanged = false;
    
    // ========== æ›´æ–°ç©å®¶å‰çº¿ ==========
    
    // é»˜è®¤å‰çº¿ä½ç½®ä¸ºåˆå§‹å€¼
    float NewPlayerFrontLineX = InitialFrontLineX;
    
    // æ£€æŸ¥ç¼“å­˜çš„ç©å®¶æœ€å‰æ–¹å•ä½æ˜¯å¦æœ‰æ•ˆ
    if (CachedPlayerFrontmostUnit &&          // å•ä½å­˜åœ¨
        !CachedPlayerFrontmostUnit->bIsDead &&// å•ä½æœªæ­»äº¡
        IsValid(CachedPlayerFrontmostUnit))   // å•ä½å¯¹è±¡æœ‰æ•ˆ
    {
        // è·å–å•ä½å½“å‰ä½ç½®çš„ X åæ ‡
        float UnitX = CachedPlayerFrontmostUnit->GetActorLocation().X;
        
        // æ£€æŸ¥æ˜¯å¦è¶Šè¿‡åˆå§‹çº¿
        // æ ¹æ®ç©å®¶æ–¹å‘åˆ¤æ–­ï¼š
        // - ç©å®¶åœ¨å·¦ä¾§ï¼šå•ä½ X > åˆå§‹çº¿ X è¡¨ç¤ºè¶Šçº¿
        // - ç©å®¶åœ¨å³ä¾§ï¼šå•ä½ X < åˆå§‹çº¿ X è¡¨ç¤ºè¶Šçº¿
        bool bCrossedLine = bPlayerOnLeftSide ? 
            (UnitX > InitialFrontLineX) : 
            (UnitX < InitialFrontLineX);
        
        // å¦‚æœå•ä½è¶Šè¿‡åˆå§‹çº¿ï¼Œæ›´æ–°å‰çº¿ä½ç½®
        if (bCrossedLine)
        {
            // è®¡ç®—å‰çº¿ä½ç½®
            if (bPlayerOnLeftSide)
            {
                // ç©å®¶åœ¨å·¦ä¾§ï¼Œå‰çº¿åœ¨å•ä½å³ä¾§
                // å‰çº¿ä½ç½® = å•ä½ä½ç½® + åç§»é‡
                NewPlayerFrontLineX = UnitX + FrontLineOffset;
            }
            else
            {
                // ç©å®¶åœ¨å³ä¾§ï¼Œå‰çº¿åœ¨å•ä½å·¦ä¾§
                // å‰çº¿ä½ç½® = å•ä½ä½ç½® - åç§»é‡
                NewPlayerFrontLineX = UnitX - FrontLineOffset;
            }
        }
    }

    // ========== æ›´æ–°æ•Œäººå‰çº¿ ==========
    
    // é»˜è®¤å‰çº¿ä½ç½®ä¸ºåˆå§‹å€¼
    float NewEnemyFrontLineX = InitialFrontLineX;
    
    // æ£€æŸ¥ç¼“å­˜çš„æ•Œäººæœ€å‰æ–¹å•ä½æ˜¯å¦æœ‰æ•ˆ
    if (CachedEnemyFrontmostUnit &&          // å•ä½å­˜åœ¨
        !CachedEnemyFrontmostUnit->bIsDead &&// å•ä½æœªæ­»äº¡
        IsValid(CachedEnemyFrontmostUnit))   // å•ä½å¯¹è±¡æœ‰æ•ˆ
    {
        // è·å–å•ä½å½“å‰ä½ç½®çš„ X åæ ‡
        float UnitX = CachedEnemyFrontmostUnit->GetActorLocation().X;
        
        // æ£€æŸ¥æ˜¯å¦è¶Šè¿‡åˆå§‹çº¿
        // æ ¹æ®ç©å®¶æ–¹å‘åˆ¤æ–­ï¼š
        // - ç©å®¶åœ¨å·¦ä¾§ï¼ˆæ•Œäººåœ¨å³ä¾§ï¼‰ï¼šå•ä½ X < åˆå§‹çº¿ X è¡¨ç¤ºè¶Šçº¿
        // - ç©å®¶åœ¨å³ä¾§ï¼ˆæ•Œäººåœ¨å·¦ä¾§ï¼‰ï¼šå•ä½ X > åˆå§‹çº¿ X è¡¨ç¤ºè¶Šçº¿
        bool bCrossedLine = bPlayerOnLeftSide ? 
            (UnitX < InitialFrontLineX) : 
            (UnitX > InitialFrontLineX);
        
        // å¦‚æœå•ä½è¶Šè¿‡åˆå§‹çº¿ï¼Œæ›´æ–°å‰çº¿ä½ç½®
        if (bCrossedLine)
        {
            // è®¡ç®—å‰çº¿ä½ç½®
            if (bPlayerOnLeftSide)
            {
                // æ•Œäººåœ¨å³ä¾§ï¼Œå‰çº¿åœ¨å•ä½å·¦ä¾§
                // å‰çº¿ä½ç½® = å•ä½ä½ç½® - åç§»é‡
                NewEnemyFrontLineX = UnitX - FrontLineOffset;
            }
            else
            {
                // æ•Œäººåœ¨å·¦ä¾§ï¼Œå‰çº¿åœ¨å•ä½å³ä¾§
                // å‰çº¿ä½ç½® = å•ä½ä½ç½® + åç§»é‡
                NewEnemyFrontLineX = UnitX + FrontLineOffset;
            }
        }
    }

    // ========== åº”ç”¨æ–°ä½ç½® ==========
    
    // ç›´æ¥è®¾ç½®æ–°ä½ç½®ï¼ˆæ— æ’å€¼ï¼‰
    // æ£€æŸ¥ç©å®¶å‰çº¿æ˜¯å¦æ”¹å˜ï¼ˆå…è®¸1ä¸ªå•ä½çš„è¯¯å·®ï¼‰
    if (!FMath::IsNearlyEqual(CurrentPlayerFrontLineX, NewPlayerFrontLineX, 1.0f))
    {
        // ç›´æ¥èµ‹å€¼ï¼Œæ— æ’å€¼ï¼Œå®ç°é›¶å»¶è¿Ÿè·Ÿéš
        CurrentPlayerFrontLineX = NewPlayerFrontLineX;
        bChanged = true;
    }

    // æ£€æŸ¥æ•Œäººå‰çº¿æ˜¯å¦æ”¹å˜ï¼ˆå…è®¸1ä¸ªå•ä½çš„è¯¯å·®ï¼‰
    if (!FMath::IsNearlyEqual(CurrentEnemyFrontLineX, NewEnemyFrontLineX, 1.0f))
    {
        // ç›´æ¥èµ‹å€¼ï¼Œæ— æ’å€¼ï¼Œå®ç°é›¶å»¶è¿Ÿè·Ÿéš
        CurrentEnemyFrontLineX = NewEnemyFrontLineX;
        bChanged = true;
    }

    // åªåœ¨ä½ç½®æ”¹å˜æ—¶æ›´æ–°å¯è§†åŒ–
    // é¿å…ä¸å¿…è¦çš„è®¡ç®—å’Œç»˜åˆ¶
    if (bChanged)
    {
        // è°ƒæ•´å‰çº¿é—´è·
        // ç¡®ä¿åŒæ–¹å‰çº¿ä¸ä¼šè¿‡äºæ¥è¿‘
        AdjustFrontLineDistance();
        
        // æ›´æ–°å¯è§†åŒ–
        // æ›´æ–°æ ·æ¡çº¿å’Œç½‘æ ¼ä½“ä½ç½®
        UpdateFrontLineVisualization();
    }
}

/**
 * @brief é‡æ–°æ‰«ææœ€å‰æ–¹å•ä½ï¼ˆå®šæ—¶è°ƒç”¨ï¼‰
 * @details 
 * æ‰§è¡Œæµç¨‹ï¼š
 * 1. è·å–åœºæ™¯ä¸­æ‰€æœ‰å•ä½
 * 2. æ ¹æ®é˜µè¥æ ‡ç­¾åŒºåˆ†ç©å®¶å’Œæ•Œäººå•ä½
 * 3. æ ¹æ®ä½ç½®å’Œæ–¹å‘æ‰¾åˆ°æœ€å‰æ–¹çš„å•ä½
 * 4. æ›´æ–°ç¼“å­˜çš„æœ€å‰æ–¹å•ä½
 * 5. è§£ç»‘æ—§å•ä½çš„æ­»äº¡äº‹ä»¶
 * 6. ç»‘å®šæ–°å•ä½çš„æ­»äº¡äº‹ä»¶
 * 
 * è°ƒç”¨æ—¶æœºï¼š
 * - BeginPlay æ—¶ç«‹å³è°ƒç”¨ä¸€æ¬¡
 * - ä¹‹åæ¯éš” RescanInterval ç§’è°ƒç”¨ä¸€æ¬¡
 * - æœ€å‰æ–¹å•ä½æ­»äº¡æ—¶ç«‹å³è°ƒç”¨
 * 
 * æ€§èƒ½è¯´æ˜ï¼š
 * - éœ€è¦éå†æ‰€æœ‰å•ä½ï¼Œå¤æ‚åº¦ä¸º O(n)
 * - é€šè¿‡å®šæ—¶è°ƒç”¨è€Œéæ¯å¸§è°ƒç”¨æ¥å¹³è¡¡æ€§èƒ½
 * - åœ¨ä¸¤æ¬¡æ‰«æä¹‹é—´ï¼Œç›´æ¥è¯»å–ç¼“å­˜å•ä½ä½ç½®ï¼ˆO(1)ï¼‰
 */
void ASG_FrontLineManager::RescanFrontmostUnits()
{
    // æ‰“å°æ—¥å¿—ï¼Œæ ‡è®°å¼€å§‹é‡æ–°æ‰«æ
    UE_LOG(LogSGGameplay, Verbose, TEXT("========== é‡æ–°æ‰«ææœ€å‰æ–¹å•ä½ =========="));
    
    // è·å–åœºæ™¯ä¸­æ‰€æœ‰å•ä½
    // æŸ¥æ‰¾æ‰€æœ‰ ASG_UnitsBase ç±»å‹çš„ Actor
    TArray<AActor*> AllUnits;
    UGameplayStatics::GetAllActorsOfClass(GetWorld(), ASG_UnitsBase::StaticClass(), AllUnits);
    
    // å®šä¹‰é˜µè¥æ ‡ç­¾
    // ç”¨äºåŒºåˆ†ç©å®¶å’Œæ•Œäººå•ä½
    FGameplayTag PlayerFactionTag = FGameplayTag::RequestGameplayTag(TEXT("Unit.Faction.Player"));
    FGameplayTag EnemyFactionTag = FGameplayTag::RequestGameplayTag(TEXT("Unit.Faction.Enemy"));
    
    // ========== æŸ¥æ‰¾ç©å®¶æœ€å‰æ–¹å•ä½ ==========
    
    // åˆå§‹åŒ–ç©å®¶æå€¼ä½ç½®ä¸ºåˆå§‹çº¿
    float PlayerExtremumX = InitialFrontLineX;
    // åˆå§‹åŒ–ç©å®¶æœ€å‰æ–¹å•ä½ä¸ºç©º
    ASG_UnitsBase* PlayerFrontmost = nullptr;
    
    // ========== æŸ¥æ‰¾æ•Œäººæœ€å‰æ–¹å•ä½ ==========
    
    // åˆå§‹åŒ–æ•Œäººæå€¼ä½ç½®ä¸ºåˆå§‹çº¿
    float EnemyExtremumX = InitialFrontLineX;
    // åˆå§‹åŒ–æ•Œäººæœ€å‰æ–¹å•ä½ä¸ºç©º
    ASG_UnitsBase* EnemyFrontmost = nullptr;
    
    // ä¸€æ¬¡éå†åŒæ—¶æŸ¥æ‰¾åŒæ–¹æœ€å‰æ–¹å•ä½
    // é¿å…åˆ†ä¸¤æ¬¡éå†ï¼Œæé«˜æ€§èƒ½
    for (AActor* Actor : AllUnits)
    {
        // è½¬æ¢ä¸ºå•ä½ç±»å‹
        ASG_UnitsBase* Unit = Cast<ASG_UnitsBase>(Actor);
        
        // è·³è¿‡æ— æ•ˆæˆ–å·²æ­»äº¡çš„å•ä½
        if (!Unit || Unit->bIsDead)
        {
            continue;
        }
        
        // è·å–å•ä½çš„ X åæ ‡
        float UnitX = Unit->GetActorLocation().X;
        
        // ========== æ£€æŸ¥ç©å®¶å•ä½ ==========
        if (Unit->FactionTag.MatchesTag(PlayerFactionTag))
        {
            // åˆ¤æ–­æ˜¯å¦æ˜¯æœ€å‰æ–¹å•ä½
            bool bIsFrontmost = false;
            
            if (bPlayerOnLeftSide)
            {
                // ç©å®¶åœ¨å·¦ä¾§ï¼Œæ‰¾æœ€å³è¾¹çš„å•ä½
                if (bOnlyTrackCrossedUnits)
                {
                    // åªè¿½è¸ªè¶Šè¿‡åˆå§‹çº¿çš„å•ä½
                    // æ¡ä»¶ï¼šå•ä½ X > åˆå§‹çº¿ X ä¸” å•ä½ X > å½“å‰æå€¼ X
                    bIsFrontmost = (UnitX > InitialFrontLineX) && (UnitX > PlayerExtremumX);
                }
                else
                {
                    // è¿½è¸ªæ‰€æœ‰å•ä½
                    // æ¡ä»¶ï¼šå•ä½ X > å½“å‰æå€¼ X
                    bIsFrontmost = (UnitX > PlayerExtremumX);
                }
            }
            else
            {
                // ç©å®¶åœ¨å³ä¾§ï¼Œæ‰¾æœ€å·¦è¾¹çš„å•ä½
                if (bOnlyTrackCrossedUnits)
                {
                    // åªè¿½è¸ªè¶Šè¿‡åˆå§‹çº¿çš„å•ä½
                    // æ¡ä»¶ï¼šå•ä½ X < åˆå§‹çº¿ X ä¸” å•ä½ X < å½“å‰æå€¼ X
                    bIsFrontmost = (UnitX < InitialFrontLineX) && (UnitX < PlayerExtremumX);
                }
                else
                {
                    // è¿½è¸ªæ‰€æœ‰å•ä½
                    // æ¡ä»¶ï¼šå•ä½ X < å½“å‰æå€¼ X
                    bIsFrontmost = (UnitX < PlayerExtremumX);
                }
            }
            
            // å¦‚æœæ˜¯æœ€å‰æ–¹å•ä½ï¼Œæ›´æ–°æå€¼å’Œç¼“å­˜
            if (bIsFrontmost)
            {
                PlayerExtremumX = UnitX;
                PlayerFrontmost = Unit;
            }
        }
        // ========== æ£€æŸ¥æ•Œäººå•ä½ ==========
        else if (Unit->FactionTag.MatchesTag(EnemyFactionTag))
        {
            // åˆ¤æ–­æ˜¯å¦æ˜¯æœ€å‰æ–¹å•ä½
            bool bIsFrontmost = false;
            
            if (bPlayerOnLeftSide)
            {
                // æ•Œäººåœ¨å³ä¾§ï¼Œæ‰¾æœ€å·¦è¾¹çš„å•ä½
                if (bOnlyTrackCrossedUnits)
                {
                    // åªè¿½è¸ªè¶Šè¿‡åˆå§‹çº¿çš„å•ä½
                    // æ¡ä»¶ï¼šå•ä½ X < åˆå§‹çº¿ X ä¸” å•ä½ X < å½“å‰æå€¼ X
                    bIsFrontmost = (UnitX < InitialFrontLineX) && (UnitX < EnemyExtremumX);
                }
                else
                {
                    // è¿½è¸ªæ‰€æœ‰å•ä½
                    // æ¡ä»¶ï¼šå•ä½ X < å½“å‰æå€¼ X
                    bIsFrontmost = (UnitX < EnemyExtremumX);
                }
            }
            else
            {
                // æ•Œäººåœ¨å·¦ä¾§ï¼Œæ‰¾æœ€å³è¾¹çš„å•ä½
                if (bOnlyTrackCrossedUnits)
                {
                    // åªè¿½è¸ªè¶Šè¿‡åˆå§‹çº¿çš„å•ä½
                    // æ¡ä»¶ï¼šå•ä½ X > åˆå§‹çº¿ X ä¸” å•ä½ X > å½“å‰æå€¼ X
                    bIsFrontmost = (UnitX > InitialFrontLineX) && (UnitX > EnemyExtremumX);
                }
                else
                {
                    // è¿½è¸ªæ‰€æœ‰å•ä½
                    // æ¡ä»¶ï¼šå•ä½ X > å½“å‰æå€¼ X
                    bIsFrontmost = (UnitX > EnemyExtremumX);
                }
            }
            
            // å¦‚æœæ˜¯æœ€å‰æ–¹å•ä½ï¼Œæ›´æ–°æå€¼å’Œç¼“å­˜
            if (bIsFrontmost)
            {
                EnemyExtremumX = UnitX;
                EnemyFrontmost = Unit;
            }
        }
    }
    
    // ========== æ›´æ–°ç©å®¶æœ€å‰æ–¹å•ä½ç¼“å­˜ ==========
    
    // æ£€æŸ¥æœ€å‰æ–¹å•ä½æ˜¯å¦æ”¹å˜
    if (PlayerFrontmost != CachedPlayerFrontmostUnit)
    {
        // è§£ç»‘æ—§å•ä½çš„æ­»äº¡äº‹ä»¶
        if (CachedPlayerFrontmostUnit)
        {
            UnbindUnitDeathEvent(CachedPlayerFrontmostUnit);
        }
        
        // ç»‘å®šæ–°å•ä½çš„æ­»äº¡äº‹ä»¶
        if (PlayerFrontmost)
        {
            BindUnitDeathEvent(PlayerFrontmost);
            // æ‰“å°æ—¥å¿—ï¼Œè®°å½•æ–°çš„æœ€å‰æ–¹å•ä½
            UE_LOG(LogSGGameplay, Log, TEXT("âœ“ ç©å®¶æœ€å‰æ–¹å•ä½æ›´æ–°ï¼š%s (X = %.0f)"), 
                *PlayerFrontmost->GetName(), PlayerExtremumX);
        }
        else
        {
            // æ²¡æœ‰æ‰¾åˆ°è¶Šè¿‡åˆå§‹çº¿çš„å•ä½
            UE_LOG(LogSGGameplay, Log, TEXT("ç©å®¶æ— è¶Šè¿‡åˆå§‹çº¿çš„å•ä½"));
        }
        
        // æ›´æ–°ç¼“å­˜
        CachedPlayerFrontmostUnit = PlayerFrontmost;
    }
    
    // ========== æ›´æ–°æ•Œäººæœ€å‰æ–¹å•ä½ç¼“å­˜ ==========
    
    // æ£€æŸ¥æœ€å‰æ–¹å•ä½æ˜¯å¦æ”¹å˜
    if (EnemyFrontmost != CachedEnemyFrontmostUnit)
    {
        // è§£ç»‘æ—§å•ä½çš„æ­»äº¡äº‹ä»¶
        if (CachedEnemyFrontmostUnit)
        {
            UnbindUnitDeathEvent(CachedEnemyFrontmostUnit);
        }
        
        // ç»‘å®šæ–°å•ä½çš„æ­»äº¡äº‹ä»¶
        if (EnemyFrontmost)
        {
            BindUnitDeathEvent(EnemyFrontmost);
            // æ‰“å°æ—¥å¿—ï¼Œè®°å½•æ–°çš„æœ€å‰æ–¹å•ä½
            UE_LOG(LogSGGameplay, Log, TEXT("âœ“ æ•Œäººæœ€å‰æ–¹å•ä½æ›´æ–°ï¼š%s (X = %.0f)"), 
                *EnemyFrontmost->GetName(), EnemyExtremumX);
        }
        else
        {
            // æ²¡æœ‰æ‰¾åˆ°è¶Šè¿‡åˆå§‹çº¿çš„å•ä½
            UE_LOG(LogSGGameplay, Log, TEXT("æ•Œäººæ— è¶Šè¿‡åˆå§‹çº¿çš„å•ä½"));
        }
        
        // æ›´æ–°ç¼“å­˜
        CachedEnemyFrontmostUnit = EnemyFrontmost;
    }
    
    // æ‰“å°æ—¥å¿—ï¼Œæ ‡è®°æ‰«æç»“æŸ
    UE_LOG(LogSGGameplay, Verbose, TEXT("========================================"));
}

/**
 * @brief æ›´æ–°å‰çº¿å¯è§†åŒ–
 * @details 
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - æ›´æ–°æ ·æ¡çº¿ç»„ä»¶çš„ä½ç½®ï¼Œä½¿å…¶æ˜¾ç¤ºå½“å‰å‰çº¿
 * - âœ¨ æ–°å¢ - æ›´æ–°ç©å®¶å‰çº¿ç½‘æ ¼ä½“çš„ä½ç½®ã€æ—‹è½¬å’Œç¼©æ”¾
 * 
 * æ›´æ–°å†…å®¹ï¼š
 * 1. æ›´æ–°æ ·æ¡çº¿ä½ç½®ï¼ˆç¼–è¾‘å™¨å¯è§†åŒ–ï¼‰
 * 2. æ›´æ–°ç©å®¶å‰çº¿ç½‘æ ¼ä½“ä½ç½®ï¼ˆè¿è¡Œæ—¶å¯è§†åŒ–ï¼‰
 * 3. æ ¹æ® FrontLineWidth è‡ªåŠ¨è°ƒæ•´ç½‘æ ¼ä½“ Y è½´ç¼©æ”¾
 */
void ASG_FrontLineManager::UpdateFrontLineVisualization()
{
    // ========== æ›´æ–°ç©å®¶å‰çº¿æ ·æ¡çº¿ ==========
    if (PlayerFrontLineSpline)
    {
        // è®¡ç®—æ ·æ¡çº¿èµ·ç‚¹ï¼ˆå·¦ç«¯ç‚¹ï¼‰
        // X = å½“å‰ç©å®¶å‰çº¿ä½ç½®
        // Y = å‰çº¿å®½åº¦çš„ä¸€åŠï¼ˆè´Ÿå€¼ï¼Œè¡¨ç¤ºå·¦ä¾§ï¼‰
        // Z = å‰çº¿é«˜åº¦
        FVector StartPoint = FVector(CurrentPlayerFrontLineX, -FrontLineWidth / 2.0f, FrontLineHeight);
        
        // è®¡ç®—æ ·æ¡çº¿ç»ˆç‚¹ï¼ˆå³ç«¯ç‚¹ï¼‰
        // X = å½“å‰ç©å®¶å‰çº¿ä½ç½®
        // Y = å‰çº¿å®½åº¦çš„ä¸€åŠï¼ˆæ­£å€¼ï¼Œè¡¨ç¤ºå³ä¾§ï¼‰
        // Z = å‰çº¿é«˜åº¦
        FVector EndPoint = FVector(CurrentPlayerFrontLineX, FrontLineWidth / 2.0f, FrontLineHeight);
        
        // æ›´æ–°æ ·æ¡çº¿ç¬¬0ä¸ªç‚¹çš„ä½ç½®ï¼ˆèµ·ç‚¹ï¼‰
        PlayerFrontLineSpline->SetLocationAtSplinePoint(0, StartPoint, ESplineCoordinateSpace::World);
        // æ›´æ–°æ ·æ¡çº¿ç¬¬1ä¸ªç‚¹çš„ä½ç½®ï¼ˆç»ˆç‚¹ï¼‰
        PlayerFrontLineSpline->SetLocationAtSplinePoint(1, EndPoint, ESplineCoordinateSpace::World);
    }

    // ========== æ›´æ–°æ•Œäººå‰çº¿æ ·æ¡çº¿ ==========
    if (EnemyFrontLineSpline)
    {
        // è®¡ç®—æ ·æ¡çº¿èµ·ç‚¹ï¼ˆå·¦ç«¯ç‚¹ï¼‰
        // X = å½“å‰æ•Œäººå‰çº¿ä½ç½®
        // Y = å‰çº¿å®½åº¦çš„ä¸€åŠï¼ˆè´Ÿå€¼ï¼Œè¡¨ç¤ºå·¦ä¾§ï¼‰
        // Z = å‰çº¿é«˜åº¦
        FVector StartPoint = FVector(CurrentEnemyFrontLineX, -FrontLineWidth / 2.0f, FrontLineHeight);
        
        // è®¡ç®—æ ·æ¡çº¿ç»ˆç‚¹ï¼ˆå³ç«¯ç‚¹ï¼‰
        // X = å½“å‰æ•Œäººå‰çº¿ä½ç½®
        // Y = å‰çº¿å®½åº¦çš„ä¸€åŠï¼ˆæ­£å€¼ï¼Œè¡¨ç¤ºå³ä¾§ï¼‰
        // Z = å‰çº¿é«˜åº¦
        FVector EndPoint = FVector(CurrentEnemyFrontLineX, FrontLineWidth / 2.0f, FrontLineHeight);
        
        // æ›´æ–°æ ·æ¡çº¿ç¬¬0ä¸ªç‚¹çš„ä½ç½®ï¼ˆèµ·ç‚¹ï¼‰
        EnemyFrontLineSpline->SetLocationAtSplinePoint(0, StartPoint, ESplineCoordinateSpace::World);
        // æ›´æ–°æ ·æ¡çº¿ç¬¬1ä¸ªç‚¹çš„ä½ç½®ï¼ˆç»ˆç‚¹ï¼‰
        EnemyFrontLineSpline->SetLocationAtSplinePoint(1, EndPoint, ESplineCoordinateSpace::World);
    }

    // âœ¨ æ–°å¢ - æ›´æ–°ç©å®¶å‰çº¿ç½‘æ ¼ä½“
    if (PlayerFrontLineMesh)
    {
        // æ ¹æ®é…ç½®å†³å®šæ˜¯å¦æ˜¾ç¤ºç½‘æ ¼ä½“
        PlayerFrontLineMesh->SetVisibility(bShowPlayerFrontLineMesh);
        
        if (bShowPlayerFrontLineMesh)
        {
            // è®¡ç®—ç½‘æ ¼ä½“ä½ç½®
            // X = å½“å‰ç©å®¶å‰çº¿ä½ç½®
            // Y = 0ï¼ˆä¸­å¿ƒä½ç½®ï¼‰
            // Z = å‰çº¿é«˜åº¦
            FVector MeshLocation = FVector(CurrentPlayerFrontLineX, 0.0f, FrontLineHeight);
            
            // è®¾ç½®ç½‘æ ¼ä½“ä¸–ç•Œä½ç½®
            PlayerFrontLineMesh->SetWorldLocation(MeshLocation);
            
            // è®¾ç½®ç½‘æ ¼ä½“æ—‹è½¬
            // é¢å‘ Y è½´ï¼ˆå‰çº¿æ˜¯ä¸€æ¡ç«–çº¿ï¼‰
            FRotator MeshRotation = FRotator(0.0f, 0.0f, 0.0f);
            PlayerFrontLineMesh->SetWorldRotation(MeshRotation);
            
            // è®¡ç®—ç½‘æ ¼ä½“ç¼©æ”¾
            // X å’Œ Z ä½¿ç”¨é…ç½®çš„ç¼©æ”¾å€¼
            // Y æ ¹æ®å‰çº¿å®½åº¦è‡ªåŠ¨è®¡ç®—ï¼ˆå‡è®¾ç½‘æ ¼ä½“åŸå§‹å®½åº¦ä¸º100å•ä½ï¼‰
            FVector MeshScale = FrontLineMeshScale;
            // æ ¹æ®å‰çº¿å®½åº¦è°ƒæ•´ Y è½´ç¼©æ”¾
            // å‡è®¾ç½‘æ ¼ä½“åŸå§‹å®½åº¦ä¸º100å•ä½ï¼Œç¼©æ”¾åˆ° FrontLineWidth
            MeshScale.Y = (FrontLineWidth / 100.0f) * FrontLineMeshScale.Y;
            
            // è®¾ç½®ç½‘æ ¼ä½“ä¸–ç•Œç¼©æ”¾
            PlayerFrontLineMesh->SetWorldScale3D(MeshScale);
        }
    }
}

/**
 * @brief ç»˜åˆ¶è°ƒè¯•ä¿¡æ¯
 * @details 
 * ç»˜åˆ¶å†…å®¹ï¼š
 * 1. ç©å®¶å‰çº¿ï¼ˆè“è‰²å®çº¿ï¼‰
 * 2. æ•Œäººå‰çº¿ï¼ˆçº¢è‰²å®çº¿ï¼‰
 * 3. ä¸­ç«‹åŒºä¸­çº¿ï¼ˆé»„è‰²è™šçº¿ï¼‰
 * 4. å‰çº¿ä½ç½®æ–‡å­—
 * 5. æœ€å‰æ–¹å•ä½æ ‡è®°ï¼ˆçƒä½“ + æ–‡å­—ï¼‰
 * 
 * æ³¨æ„äº‹é¡¹ï¼š
 * - ä»…åœ¨ bEnableDebugDraw ä¸º true æ—¶ç»˜åˆ¶
 * - ä½¿ç”¨ DrawDebug ç³»åˆ—å‡½æ•°ï¼Œä»…åœ¨ç¼–è¾‘å™¨å’Œå¼€å‘ç‰ˆæœ¬ä¸­æ˜¾ç¤º
 */
void ASG_FrontLineManager::DrawDebugInfo()
{
    // æ£€æŸ¥ä¸–ç•Œå¯¹è±¡æ˜¯å¦æœ‰æ•ˆ
    if (!GetWorld())
    {
        return;
    }
    
    // ========== ç»˜åˆ¶ç©å®¶å‰çº¿ï¼ˆè“è‰²ï¼‰ ==========
    
    // è®¡ç®—å‰çº¿èµ·ç‚¹ï¼ˆå·¦ç«¯ç‚¹ï¼‰
    FVector PlayerLineStart = FVector(CurrentPlayerFrontLineX, -FrontLineWidth / 2.0f, 0.0f);
    // è®¡ç®—å‰çº¿ç»ˆç‚¹ï¼ˆå³ç«¯ç‚¹ï¼‰
    FVector PlayerLineEnd = FVector(CurrentPlayerFrontLineX, FrontLineWidth / 2.0f, 0.0f);
    // ç»˜åˆ¶è“è‰²çº¿æ¡
    DrawDebugLine(GetWorld(), PlayerLineStart, PlayerLineEnd, FColor::Blue, false, -1.0f, 0, FrontLineThickness);

    // ========== ç»˜åˆ¶æ•Œäººå‰çº¿ï¼ˆçº¢è‰²ï¼‰ ==========
    
    // è®¡ç®—å‰çº¿èµ·ç‚¹ï¼ˆå·¦ç«¯ç‚¹ï¼‰
    FVector EnemyLineStart = FVector(CurrentEnemyFrontLineX, -FrontLineWidth / 2.0f, 0.0f);
    // è®¡ç®—å‰çº¿ç»ˆç‚¹ï¼ˆå³ç«¯ç‚¹ï¼‰
    FVector EnemyLineEnd = FVector(CurrentEnemyFrontLineX, FrontLineWidth / 2.0f, 0.0f);
    // ç»˜åˆ¶çº¢è‰²çº¿æ¡
    DrawDebugLine(GetWorld(), EnemyLineStart, EnemyLineEnd, FColor::Red, false, -1.0f, 0, FrontLineThickness);

    // ========== ç»˜åˆ¶ä¸­ç«‹åŒºä¸­çº¿ï¼ˆé»„è‰²è™šçº¿ï¼‰ ==========
    
    // è®¡ç®—ä¸­ç«‹åŒºä¸­çº¿çš„ X åæ ‡ï¼ˆåŒæ–¹å‰çº¿çš„ä¸­ç‚¹ï¼‰
    float MidX = (CurrentPlayerFrontLineX + CurrentEnemyFrontLineX) / 2.0f;
    
    // è™šçº¿æ®µæ•°ï¼ˆå¶æ•°ï¼Œç”¨äºç»˜åˆ¶è™šçº¿æ•ˆæœï¼‰
    int32 SegmentCount = 20;
    // æ¯æ®µçš„é•¿åº¦
    float SegmentLength = FrontLineWidth / SegmentCount;
    
    // ç»˜åˆ¶è™šçº¿ï¼ˆæ¯éš”ä¸€æ®µç»˜åˆ¶ä¸€æ¬¡ï¼‰
    for (int32 i = 0; i < SegmentCount; i += 2)
    {
        // è®¡ç®—å½“å‰æ®µçš„èµ·ç‚¹
        FVector SegmentStart = FVector(MidX, -FrontLineWidth / 2.0f + i * SegmentLength, 0.0f);
        // è®¡ç®—å½“å‰æ®µçš„ç»ˆç‚¹
        FVector SegmentEnd = FVector(MidX, -FrontLineWidth / 2.0f + (i + 1) * SegmentLength, 0.0f);
        // ç»˜åˆ¶é»„è‰²çº¿æ¡ï¼ˆç²—ç»†ä¸ºå‰çº¿ç²—ç»†çš„ä¸€åŠï¼‰
        DrawDebugLine(GetWorld(), SegmentStart, SegmentEnd, FColor::Yellow, false, -1.0f, 0, FrontLineThickness / 2.0f);
    }
    
    // ========== ç»˜åˆ¶æ–‡å­—ä¿¡æ¯ ==========
    
    // ç»˜åˆ¶ç©å®¶å‰çº¿ä½ç½®æ–‡å­—ï¼ˆè“è‰²ï¼‰
    DrawDebugString(GetWorld(), FVector(CurrentPlayerFrontLineX, 0.0f, 200.0f), 
        FString::Printf(TEXT("ç©å®¶å‰çº¿: %.0f"), CurrentPlayerFrontLineX),
        nullptr, FColor::Blue, 0.0f, true, 1.5f);

    // ç»˜åˆ¶æ•Œäººå‰çº¿ä½ç½®æ–‡å­—ï¼ˆçº¢è‰²ï¼‰
    DrawDebugString(GetWorld(), FVector(CurrentEnemyFrontLineX, 0.0f, 200.0f), 
        FString::Printf(TEXT("æ•Œäººå‰çº¿: %.0f"), CurrentEnemyFrontLineX),
        nullptr, FColor::Red, 0.0f, true, 1.5f);

    // ========== ç»˜åˆ¶æœ€å‰æ–¹å•ä½æŒ‡ç¤º ==========
    
    // ç»˜åˆ¶ç©å®¶æœ€å‰æ–¹å•ä½æ ‡è®°
    if (CachedPlayerFrontmostUnit && !CachedPlayerFrontmostUnit->bIsDead)
    {
        // è·å–å•ä½ä½ç½®
        FVector UnitLoc = CachedPlayerFrontmostUnit->GetActorLocation();
        // ç»˜åˆ¶é’è‰²çƒä½“ï¼ˆåŠå¾„100ï¼‰
        DrawDebugSphere(GetWorld(), UnitLoc, 100.0f, 12, FColor::Cyan, false, -1.0f, 0, 5.0f);
        // ç»˜åˆ¶æ–‡å­—æ ‡ç­¾
        DrawDebugString(GetWorld(), UnitLoc + FVector(0.0f, 0.0f, 150.0f), 
            TEXT("ç©å®¶æœ€å‰æ–¹"), nullptr, FColor::Cyan, 0.0f, true, 1.2f);
    }

    // ç»˜åˆ¶æ•Œäººæœ€å‰æ–¹å•ä½æ ‡è®°
    if (CachedEnemyFrontmostUnit && !CachedEnemyFrontmostUnit->bIsDead)
    {
        // è·å–å•ä½ä½ç½®
        FVector UnitLoc = CachedEnemyFrontmostUnit->GetActorLocation();
        // ç»˜åˆ¶æ©™è‰²çƒä½“ï¼ˆåŠå¾„100ï¼‰
        DrawDebugSphere(GetWorld(), UnitLoc, 100.0f, 12, FColor::Orange, false, -1.0f, 0, 5.0f);
        // ç»˜åˆ¶æ–‡å­—æ ‡ç­¾
        DrawDebugString(GetWorld(), UnitLoc + FVector(0.0f, 0.0f, 150.0f), 
            TEXT("æ•Œäººæœ€å‰æ–¹"), nullptr, FColor::Orange, 0.0f, true, 1.2f);
    }
}

/**
 * @brief è°ƒæ•´å‰çº¿é—´è·
 * @details 
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - ç¡®ä¿åŒæ–¹å‰çº¿ä¸ä¼šè¿‡äºæ¥è¿‘
 * - å½“å‰çº¿é—´è·å°äº MinFrontLineDistance æ—¶ï¼Œå°†åŒæ–¹å‰çº¿å‘å¤–æ¨å¼€
 * - ä¿æŒå‰çº¿é—´è·è‡³å°‘ä¸º MinFrontLineDistance
 * 
 * è°ƒæ•´ç­–ç•¥ï¼š
 * - è®¡ç®—å½“å‰åŒæ–¹å‰çº¿çš„è·ç¦»
 * - å¦‚æœè·ç¦»å°äºæœ€å°é—´è·ï¼Œè®¡ç®—éœ€è¦è°ƒæ•´çš„è·ç¦»
 * - å°†åŒæ–¹å‰çº¿å„å‘å¤–æ¨å¼€ä¸€åŠçš„è°ƒæ•´è·ç¦»
 * - æ ¹æ®ç©å®¶æ–¹å‘ï¼ˆå·¦/å³ï¼‰å†³å®šæ¨å¼€çš„æ–¹å‘
 */
void ASG_FrontLineManager::AdjustFrontLineDistance()
{
    // è®¡ç®—å½“å‰åŒæ–¹å‰çº¿çš„è·ç¦»ï¼ˆç»å¯¹å€¼ï¼‰
    float CurrentDistance = FMath::Abs(CurrentEnemyFrontLineX - CurrentPlayerFrontLineX);
    
    // å¦‚æœå½“å‰è·ç¦»å°äºæœ€å°é—´è·ï¼Œéœ€è¦è°ƒæ•´
    if (CurrentDistance < MinFrontLineDistance)
    {
        // è®¡ç®—éœ€è¦è°ƒæ•´çš„è·ç¦»ï¼ˆæ€»å…±éœ€è¦å¢åŠ çš„è·ç¦»ï¼‰
        // é™¤ä»¥2æ˜¯å› ä¸ºåŒæ–¹å„å‘å¤–æ¨å¼€ä¸€åŠ
        float AdjustDistance = (MinFrontLineDistance - CurrentDistance) / 2.0f;
        
        // æ ¹æ®ç©å®¶æ–¹å‘è°ƒæ•´å‰çº¿ä½ç½®
        if (bPlayerOnLeftSide)
        {
            // ç©å®¶åœ¨å·¦ä¾§
            // ç©å®¶å‰çº¿å‘å·¦æ¨ï¼ˆå‡å° Xï¼‰
            CurrentPlayerFrontLineX -= AdjustDistance;
            // æ•Œäººå‰çº¿å‘å³æ¨ï¼ˆå¢å¤§ Xï¼‰
            CurrentEnemyFrontLineX += AdjustDistance;
        }
        else
        {
            // ç©å®¶åœ¨å³ä¾§
            // ç©å®¶å‰çº¿å‘å³æ¨ï¼ˆå¢å¤§ Xï¼‰
            CurrentPlayerFrontLineX += AdjustDistance;
            // æ•Œäººå‰çº¿å‘å·¦æ¨ï¼ˆå‡å° Xï¼‰
            CurrentEnemyFrontLineX -= AdjustDistance;
        }
    }
}

/**
 * @brief æŸ¥æ‰¾å¹¶ç¼“å­˜ä¸»åŸä½ç½®
 * @details 
 * æ‰§è¡Œæµç¨‹ï¼š
 * 1. è·å–åœºæ™¯ä¸­æ‰€æœ‰ä¸»åŸ
 * 2. æ ¹æ® Faction æ ‡ç­¾åŒºåˆ†ç©å®¶å’Œæ•Œäººä¸»åŸ
 * 3. ç¼“å­˜ä¸»åŸå¼•ç”¨å’Œä½ç½®
 * 4. æ ¹æ®ä¸»åŸä½ç½®ç¡®å®šç©å®¶æ–¹å‘ï¼ˆå·¦/å³ï¼‰
 * 
 * æ³¨æ„äº‹é¡¹ï¼š
 * - éœ€è¦ä¸»åŸæ­£ç¡®è®¾ç½® Faction æ ‡ç­¾
 * - ç©å®¶æ–¹å‘ç”±ä¸»åŸä½ç½®å†³å®šï¼šç©å®¶ä¸»åŸ X < æ•Œäººä¸»åŸ X åˆ™ç©å®¶åœ¨å·¦ä¾§
 */
void ASG_FrontLineManager::FindAndCacheMainCities()
{
    // æ‰“å°æ—¥å¿—ï¼Œå¼€å§‹æŸ¥æ‰¾ä¸»åŸ
    UE_LOG(LogSGGameplay, Log, TEXT("æŸ¥æ‰¾ä¸»åŸ..."));
    
    // è·å–åœºæ™¯ä¸­æ‰€æœ‰ä¸»åŸ
    TArray<AActor*> FoundMainCities;
    UGameplayStatics::GetAllActorsOfClass(GetWorld(), ASG_MainCityBase::StaticClass(), FoundMainCities);
    
    // å®šä¹‰é˜µè¥æ ‡ç­¾
    FGameplayTag PlayerFactionTag = FGameplayTag::RequestGameplayTag(TEXT("Unit.Faction.Player"));
    FGameplayTag EnemyFactionTag = FGameplayTag::RequestGameplayTag(TEXT("Unit.Faction.Enemy"));
    
    // éå†æ‰€æœ‰ä¸»åŸ
    for (AActor* Actor : FoundMainCities)
    {
        // è½¬æ¢ä¸ºä¸»åŸç±»å‹
        ASG_MainCityBase* MainCity = Cast<ASG_MainCityBase>(Actor);
        if (!MainCity)
        {
            continue;
        }
        
        // æ£€æŸ¥æ˜¯å¦æ˜¯ç©å®¶ä¸»åŸ
        if (MainCity->FactionTag.MatchesTag(PlayerFactionTag))
        {
            // ç¼“å­˜ç©å®¶ä¸»åŸå¼•ç”¨
            CachedPlayerMainCity = MainCity;
            // ç¼“å­˜ç©å®¶ä¸»åŸ X åæ ‡
            PlayerMainCityX = MainCity->GetActorLocation().X;
            // æ‰“å°æ—¥å¿—
            UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ ç©å®¶ä¸»åŸï¼šX = %.0f"), PlayerMainCityX);
        }
        // æ£€æŸ¥æ˜¯å¦æ˜¯æ•Œäººä¸»åŸ
        else if (MainCity->FactionTag.MatchesTag(EnemyFactionTag))
        {
            // ç¼“å­˜æ•Œäººä¸»åŸå¼•ç”¨
            CachedEnemyMainCity = MainCity;
            // ç¼“å­˜æ•Œäººä¸»åŸ X åæ ‡
            EnemyMainCityX = MainCity->GetActorLocation().X;
            // æ‰“å°æ—¥å¿—
            UE_LOG(LogSGGameplay, Log, TEXT("  âœ“ æ•Œäººä¸»åŸï¼šX = %.0f"), EnemyMainCityX);
        }
    }
    
    // å¦‚æœåŒæ–¹ä¸»åŸéƒ½æ‰¾åˆ°äº†ï¼Œç¡®å®šç©å®¶æ–¹å‘
    if (CachedPlayerMainCity && CachedEnemyMainCity)
    {
        // ç©å®¶ä¸»åŸ X < æ•Œäººä¸»åŸ Xï¼Œåˆ™ç©å®¶åœ¨å·¦ä¾§
        bPlayerOnLeftSide = (PlayerMainCityX < EnemyMainCityX);
    }
}

/**
 * @brief è·å–ä½ç½®æ‰€å±åŒºåŸŸ
 * @param Location è¦æŸ¥è¯¢çš„ä¸–ç•Œåæ ‡ä½ç½®
 * @return è¯¥ä½ç½®æ‰€å±çš„åŒºåŸŸç±»å‹ï¼ˆç©å®¶åŒºåŸŸ/ä¸­ç«‹åŒºåŸŸ/æ•ŒäººåŒºåŸŸï¼‰
 * @details 
 * åˆ¤æ–­é€»è¾‘ï¼š
 * - æ ¹æ®ç©å®¶æ–¹å‘ï¼ˆå·¦/å³ï¼‰å’Œä½ç½® X åæ ‡åˆ¤æ–­
 * - ç©å®¶åœ¨å·¦ä¾§æ—¶ï¼š
 *   - X < ç©å®¶å‰çº¿ â†’ ç©å®¶åŒºåŸŸ
 *   - ç©å®¶å‰çº¿ < X < æ•Œäººå‰çº¿ â†’ ä¸­ç«‹åŒºåŸŸ
 *   - X > æ•Œäººå‰çº¿ â†’ æ•ŒäººåŒºåŸŸ
 * - ç©å®¶åœ¨å³ä¾§æ—¶ï¼š
 *   - X > ç©å®¶å‰çº¿ â†’ ç©å®¶åŒºåŸŸ
 *   - æ•Œäººå‰çº¿ < X < ç©å®¶å‰çº¿ â†’ ä¸­ç«‹åŒºåŸŸ
 *   - X < æ•Œäººå‰çº¿ â†’ æ•ŒäººåŒºåŸŸ
 */
ESGFrontLineZone ASG_FrontLineManager::GetZoneAtLocation(const FVector& Location) const
{
    // è·å–ä½ç½®çš„ X åæ ‡
    float LocationX = Location.X;
    
    // æ ¹æ®ç©å®¶æ–¹å‘åˆ¤æ–­
    if (bPlayerOnLeftSide)
    {
        // ç©å®¶åœ¨å·¦ä¾§
        if (LocationX < CurrentPlayerFrontLineX)
        {
            // ä½ç½®åœ¨ç©å®¶å‰çº¿å·¦ä¾§ â†’ ç©å®¶åŒºåŸŸ
            return ESGFrontLineZone::PlayerZone;
        }
        else if (LocationX > CurrentEnemyFrontLineX)
        {
            // ä½ç½®åœ¨æ•Œäººå‰çº¿å³ä¾§ â†’ æ•ŒäººåŒºåŸŸ
            return ESGFrontLineZone::EnemyZone;
        }
        else
        {
            // ä½ç½®åœ¨åŒæ–¹å‰çº¿ä¹‹é—´ â†’ ä¸­ç«‹åŒºåŸŸ
            return ESGFrontLineZone::NeutralZone;
        }
    }
    else
    {
        // ç©å®¶åœ¨å³ä¾§
        if (LocationX > CurrentPlayerFrontLineX)
        {
            // ä½ç½®åœ¨ç©å®¶å‰çº¿å³ä¾§ â†’ ç©å®¶åŒºåŸŸ
            return ESGFrontLineZone::PlayerZone;
        }
        else if (LocationX < CurrentEnemyFrontLineX)
        {
            // ä½ç½®åœ¨æ•Œäººå‰çº¿å·¦ä¾§ â†’ æ•ŒäººåŒºåŸŸ
            return ESGFrontLineZone::EnemyZone;
        }
        else
        {
            // ä½ç½®åœ¨åŒæ–¹å‰çº¿ä¹‹é—´ â†’ ä¸­ç«‹åŒºåŸŸ
            return ESGFrontLineZone::NeutralZone;
        }
    }
}

/**
 * @brief åˆ¤æ–­ä½ç½®æ˜¯å¦åœ¨ç©å®¶åŒºåŸŸ
 * @param Location è¦æŸ¥è¯¢çš„ä¸–ç•Œåæ ‡ä½ç½®
 * @return trueï¼šåœ¨ç©å®¶åŒºåŸŸï¼›falseï¼šä¸åœ¨ç©å®¶åŒºåŸŸ
 */
bool ASG_FrontLineManager::IsInPlayerZone(const FVector& Location) const
{
    return GetZoneAtLocation(Location) == ESGFrontLineZone::PlayerZone;
}

/**
 * @brief åˆ¤æ–­ä½ç½®æ˜¯å¦åœ¨æ•ŒäººåŒºåŸŸ
 * @param Location è¦æŸ¥è¯¢çš„ä¸–ç•Œåæ ‡ä½ç½®
 * @return trueï¼šåœ¨æ•ŒäººåŒºåŸŸï¼›falseï¼šä¸åœ¨æ•ŒäººåŒºåŸŸ
 */
bool ASG_FrontLineManager::IsInEnemyZone(const FVector& Location) const
{
    return GetZoneAtLocation(Location) == ESGFrontLineZone::EnemyZone;
}

/**
 * @brief åˆ¤æ–­ä½ç½®æ˜¯å¦åœ¨ä¸­ç«‹åŒºåŸŸ
 * @param Location è¦æŸ¥è¯¢çš„ä¸–ç•Œåæ ‡ä½ç½®
 * @return trueï¼šåœ¨ä¸­ç«‹åŒºåŸŸï¼›falseï¼šä¸åœ¨ä¸­ç«‹åŒºåŸŸ
 */
bool ASG_FrontLineManager::IsInNeutralZone(const FVector& Location) const
{
    return GetZoneAtLocation(Location) == ESGFrontLineZone::NeutralZone;
}

/**
 * @brief å•ä½æ­»äº¡å›è°ƒ
 * @param DeadUnit æ­»äº¡çš„å•ä½
 * @details 
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - å½“æœ€å‰æ–¹å•ä½æ­»äº¡æ—¶è§¦å‘
 * - ç«‹å³æ¸…é™¤ç¼“å­˜å¹¶é‡æ–°æ‰«æ
 * - ç¡®ä¿å‰çº¿å§‹ç»ˆè·Ÿè¸ªæœ‰æ•ˆå•ä½
 * 
 * æ‰§è¡Œæµç¨‹ï¼š
 * 1. æ£€æŸ¥æ­»äº¡å•ä½æ˜¯å¦æ˜¯ç¼“å­˜çš„æœ€å‰æ–¹å•ä½
 * 2. å¦‚æœæ˜¯ï¼Œæ‰“å°è­¦å‘Šæ—¥å¿—
 * 3. æ¸…é™¤ç¼“å­˜
 * 4. ç«‹å³è°ƒç”¨ RescanFrontmostUnits é‡æ–°æ‰«æ
 */
void ASG_FrontLineManager::OnUnitDeath(ASG_UnitsBase* DeadUnit)
{
    // æ£€æŸ¥æ˜¯å¦æ˜¯ç©å®¶æœ€å‰æ–¹å•ä½æ­»äº¡
    if (DeadUnit == CachedPlayerFrontmostUnit)
    {
        // æ‰“å°è­¦å‘Šæ—¥å¿—
        UE_LOG(LogSGGameplay, Warning, TEXT("âš ï¸ ç©å®¶æœ€å‰æ–¹å•ä½æ­»äº¡ï¼Œç«‹å³é‡æ–°æ‰«æ"));
        // æ¸…é™¤ç¼“å­˜
        CachedPlayerFrontmostUnit = nullptr;
        // ç«‹å³é‡æ–°æ‰«æ
        RescanFrontmostUnits();
    }
    // æ£€æŸ¥æ˜¯å¦æ˜¯æ•Œäººæœ€å‰æ–¹å•ä½æ­»äº¡
    else if (DeadUnit == CachedEnemyFrontmostUnit)
    {
        // æ‰“å°è­¦å‘Šæ—¥å¿—
        UE_LOG(LogSGGameplay, Warning, TEXT("âš ï¸ æ•Œäººæœ€å‰æ–¹å•ä½æ­»äº¡ï¼Œç«‹å³é‡æ–°æ‰«æ"));
        // æ¸…é™¤ç¼“å­˜
        CachedEnemyFrontmostUnit = nullptr;
        // ç«‹å³é‡æ–°æ‰«æ
        RescanFrontmostUnits();
    }
}

/**
 * @brief ç»‘å®šå•ä½æ­»äº¡äº‹ä»¶
 * @param Unit è¦ç»‘å®šçš„å•ä½
 * @details å°† OnUnitDeath å‡½æ•°ç»‘å®šåˆ°å•ä½çš„æ­»äº¡å§”æ‰˜
 */
void ASG_FrontLineManager::BindUnitDeathEvent(ASG_UnitsBase* Unit)
{
    if (Unit)
    {
        // å°† OnUnitDeath å‡½æ•°æ·»åŠ åˆ°å•ä½çš„æ­»äº¡äº‹ä»¶å§”æ‰˜
        Unit->OnUnitDeathEvent.AddDynamic(this, &ASG_FrontLineManager::OnUnitDeath);
    }
}

/**
 * @brief è§£ç»‘å•ä½æ­»äº¡äº‹ä»¶
 * @param Unit è¦è§£ç»‘çš„å•ä½
 * @details ä»å•ä½çš„æ­»äº¡å§”æ‰˜ä¸­ç§»é™¤ OnUnitDeath å‡½æ•°
 */
void ASG_FrontLineManager::UnbindUnitDeathEvent(ASG_UnitsBase* Unit)
{
    if (Unit)
    {
        // ä»å•ä½çš„æ­»äº¡äº‹ä»¶å§”æ‰˜ä¸­ç§»é™¤ OnUnitDeath å‡½æ•°
        Unit->OnUnitDeathEvent.RemoveDynamic(this, &ASG_FrontLineManager::OnUnitDeath);
    }
}

/**
 * @brief è·å–å‰çº¿ç®¡ç†å™¨å•ä¾‹
 * @param WorldContextObject ä¸–ç•Œä¸Šä¸‹æ–‡å¯¹è±¡
 * @return å‰çº¿ç®¡ç†å™¨å®ä¾‹æŒ‡é’ˆï¼Œå¦‚æœä¸å­˜åœ¨åˆ™è¿”å› nullptr
 * @details 
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - ä½¿ç”¨é™æ€ç¼“å­˜ä¼˜åŒ–æŸ¥è¯¢æ€§èƒ½
 * - é¦–æ¬¡æŸ¥è¯¢æ—¶éå†åœºæ™¯æŸ¥æ‰¾
 * - åç»­æŸ¥è¯¢ç›´æ¥è¿”å›ç¼“å­˜çš„å®ä¾‹
 * 
 * æ³¨æ„äº‹é¡¹ï¼š
 * - åœºæ™¯ä¸­åªåº”å­˜åœ¨ä¸€ä¸ªå‰çº¿ç®¡ç†å™¨å®ä¾‹
 * - ä½¿ç”¨å¼±æŒ‡é’ˆé¿å…å†…å­˜æ³„æ¼
 */
ASG_FrontLineManager* ASG_FrontLineManager::GetFrontLineManager(UObject* WorldContextObject)
{
    // æ£€æŸ¥ä¸–ç•Œä¸Šä¸‹æ–‡å¯¹è±¡æ˜¯å¦æœ‰æ•ˆ
    if (!WorldContextObject)
    {
        return nullptr;
    }
    
    // è·å–ä¸–ç•Œå¯¹è±¡
    UWorld* World = WorldContextObject->GetWorld();
    if (!World)
    {
        return nullptr;
    }
    
    // é™æ€ç¼“å­˜ï¼Œå­˜å‚¨å‰çº¿ç®¡ç†å™¨å®ä¾‹
    // ä½¿ç”¨å¼±æŒ‡é’ˆé¿å…å†…å­˜æ³„æ¼
    static TWeakObjectPtr<ASG_FrontLineManager> CachedManager;
    
    // å¦‚æœç¼“å­˜æœ‰æ•ˆï¼Œç›´æ¥è¿”å›
    if (CachedManager.IsValid())
    {
        return CachedManager.Get();
    }
    
    // ç¼“å­˜æ— æ•ˆï¼Œéœ€è¦é‡æ–°æŸ¥æ‰¾
    TArray<AActor*> FoundActors;
    UGameplayStatics::GetAllActorsOfClass(World, ASG_FrontLineManager::StaticClass(), FoundActors);
    
    // å¦‚æœæ‰¾åˆ°äº†å‰çº¿ç®¡ç†å™¨
    if (FoundActors.Num() > 0)
    {
        // è½¬æ¢ä¸ºå‰çº¿ç®¡ç†å™¨ç±»å‹
        ASG_FrontLineManager* Manager = Cast<ASG_FrontLineManager>(FoundActors[0]);
        // æ›´æ–°ç¼“å­˜
        CachedManager = Manager;
        return Manager;
    }
    
    // æ²¡æœ‰æ‰¾åˆ°å‰çº¿ç®¡ç†å™¨
    return nullptr;
}
