// ğŸ“„ æ–‡ä»¶ï¼šSource/Sguo/Private/Actors/SG_Projectile.cpp

#include "Actors/SG_Projectile.h"
#include "Components/CapsuleComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Components/BoxComponent.h"  // âœ¨ æ–°å¢ - ä¿®å¤ UBoxComponent æœªå®šä¹‰
#include "AbilitySystemComponent.h"
#include "AbilitySystemGlobals.h"
#include "Units/SG_UnitsBase.h"
#include "Buildings/SG_MainCityBase.h"
#include "Debug/SG_LogCategories.h"
#include "GameplayEffect.h"
#include "GameplayCueManager.h"
#include "DrawDebugHelpers.h"

// ========== æ„é€ å‡½æ•° ==========
ASG_Projectile::ASG_Projectile()
{
	PrimaryActorTick.bCanEverTick = true;

	// ========== åˆ›å»ºåœºæ™¯æ ¹ç»„ä»¶ ==========
	SceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("SceneRoot"));
	RootComponent = SceneRoot;

	// ========== åˆ›å»ºèƒ¶å›Šä½“ç¢°æ’ç»„ä»¶ ==========
	CollisionCapsule = CreateDefaultSubobject<UCapsuleComponent>(TEXT("CollisionCapsule"));
	CollisionCapsule->SetupAttachment(RootComponent);
	
	CollisionCapsule->SetCapsuleRadius(CapsuleRadius);
	CollisionCapsule->SetCapsuleHalfHeight(CapsuleHalfHeight);
	CollisionCapsule->SetRelativeRotation(CollisionRotationOffset);
	
	// ğŸ”§ ä¿®æ”¹ - ç¢°æ’è®¾ç½®
	CollisionCapsule->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
	CollisionCapsule->SetCollisionObjectType(ECC_WorldDynamic);
	CollisionCapsule->SetCollisionResponseToAllChannels(ECR_Ignore);
	CollisionCapsule->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
	CollisionCapsule->SetCollisionResponseToChannel(ECC_WorldStatic, ECR_Block);
	CollisionCapsule->SetCollisionResponseToChannel(ECC_WorldDynamic, ECR_Overlap);
	// âœ¨ æ–°å¢ - ç¡®ä¿èƒ½æ£€æµ‹åˆ° OverlapAllDynamic ç±»å‹çš„ç¢°æ’ä½“
	CollisionCapsule->SetGenerateOverlapEvents(true);
	
	// ç»‘å®šç¢°æ’äº‹ä»¶
	CollisionCapsule->OnComponentBeginOverlap.AddDynamic(this, &ASG_Projectile::OnCapsuleOverlap);
	CollisionCapsule->OnComponentHit.AddDynamic(this, &ASG_Projectile::OnCapsuleHit);

	// ========== åˆ›å»ºç½‘æ ¼ä½“ç»„ä»¶ ==========
	MeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComponent"));
	MeshComponent->SetupAttachment(RootComponent);
	MeshComponent->SetCollisionEnabled(ECollisionEnabled::NoCollision);

	bReplicates = true;
}

// ========== BeginPlay ==========
void ASG_Projectile::BeginPlay()
{
	Super::BeginPlay();

	SetLifeSpan(LifeSpan);

	// æ›´æ–°èƒ¶å›Šä½“å°ºå¯¸å’Œæ—‹è½¬
	if (CollisionCapsule)
	{
		CollisionCapsule->SetCapsuleRadius(CapsuleRadius);
		CollisionCapsule->SetCapsuleHalfHeight(CapsuleHalfHeight);
		CollisionCapsule->SetRelativeRotation(CollisionRotationOffset);
	}

	// æ¿€æ´»é£è¡Œ GC
	ActivateTrailGameplayCue();

	UE_LOG(LogSGGameplay, Verbose, TEXT("æŠ•å°„ç‰©ç”Ÿæˆï¼š%s"), *GetName());
	UE_LOG(LogSGGameplay, Verbose, TEXT("  é£è¡Œæ¨¡å¼ï¼š%s"), 
		FlightMode == ESGProjectileFlightMode::Linear ? TEXT("ç›´çº¿") :
		FlightMode == ESGProjectileFlightMode::Parabolic ? TEXT("æŠ›ç‰©çº¿") : TEXT("å½’èˆª"));
	UE_LOG(LogSGGameplay, Verbose, TEXT("  é£è¡Œé€Ÿåº¦ï¼š%.1f"), FlightSpeed);
	UE_LOG(LogSGGameplay, Verbose, TEXT("  å¼§åº¦é«˜åº¦ï¼š%.1f"), ArcHeight);
}

// ========== EndPlay ==========
void ASG_Projectile::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	RemoveTrailGameplayCue();
	ExecuteDestroyGameplayCue();
	
	K2_OnProjectileDestroyed(GetActorLocation());
	
	FSGProjectileHitInfo DestroyInfo;
	DestroyInfo.HitLocation = GetActorLocation();
	DestroyInfo.ProjectileDirection = CurrentVelocity.GetSafeNormal();
	DestroyInfo.ProjectileSpeed = CurrentVelocity.Size();
	OnProjectileDestroyed.Broadcast(DestroyInfo);

	Super::EndPlay(EndPlayReason);
}

// ========== Tick ==========
void ASG_Projectile::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	if (!bIsInitialized)
	{
		return;
	}

	// æ ¹æ®é£è¡Œæ¨¡å¼æ›´æ–°ä½ç½®
	switch (FlightMode)
	{
	case ESGProjectileFlightMode::Linear:
		UpdateLinearFlight(DeltaTime);
		break;

	case ESGProjectileFlightMode::Parabolic:
		UpdateParabolicFlight(DeltaTime);
		break;

	case ESGProjectileFlightMode::Homing:
		UpdateHomingFlight(DeltaTime);
		break;
	}

	// æ›´æ–°æ—‹è½¬
	UpdateRotation();

#if WITH_EDITOR
	// è°ƒè¯•ç»˜åˆ¶
	if (bDrawDebugTrajectory)
	{
		DrawDebugLine(GetWorld(), GetActorLocation(), GetActorLocation() + CurrentVelocity.GetSafeNormal() * 100.0f, FColor::Red, false, -1.0f, 0, 2.0f);
	}
#endif
}

// ========== åˆå§‹åŒ–æŠ•å°„ç‰© ==========
void ASG_Projectile::InitializeProjectile(
	UAbilitySystemComponent* InInstigatorASC,
	FGameplayTag InFactionTag,
	AActor* InTarget,
	float InArcHeight
)
{
	InstigatorASC = InInstigatorASC;
	InstigatorFactionTag = InFactionTag;
	CurrentTarget = InTarget;

	// è®°å½•èµ·å§‹ä½ç½®
	StartLocation = GetActorLocation();

	// è®¡ç®—ç›®æ ‡ä½ç½®
	if (InTarget)
	{
		TargetLocation = InTarget->GetActorLocation();

		// ç„å‡†ç›®æ ‡ä¸­å¿ƒ
		if (ASG_UnitsBase* TargetUnit = Cast<ASG_UnitsBase>(InTarget))
		{
			if (UCapsuleComponent* Capsule = TargetUnit->GetCapsuleComponent())
			{
				TargetLocation.Z += Capsule->GetScaledCapsuleHalfHeight() * 0.5f;
			}
		}
		else if (ASG_MainCityBase* MainCity = Cast<ASG_MainCityBase>(InTarget))
		{
			if (UBoxComponent* DetectionBox = MainCity->GetAttackDetectionBox())
			{
				TargetLocation = DetectionBox->GetComponentLocation();
			}
		}
	}
	else
	{
		// å¦‚æœæ²¡æœ‰ç›®æ ‡ï¼Œå‘å‰é£è¡Œ
		TargetLocation = StartLocation + GetActorForwardVector() * 5000.0f;
	}

	// åº”ç”¨å¼§åº¦é«˜åº¦è¦†ç›–
	if (InArcHeight >= 0.0f)
	{
		ArcHeight = InArcHeight;
	}

	// è®¡ç®—é£è¡Œè·ç¦»
	TotalFlightDistance = FVector::Dist(StartLocation, TargetLocation);

	// åˆå§‹åŒ–é€Ÿåº¦å‘é‡
	FVector Direction = (TargetLocation - StartLocation).GetSafeNormal();
	CurrentVelocity = Direction * FlightSpeed;

	// é‡ç½®é£è¡Œè¿›åº¦
	FlightProgress = 0.0f;

	bIsInitialized = true;

	UE_LOG(LogSGGameplay, Log, TEXT("========== åˆå§‹åŒ–æŠ•å°„ç‰© =========="));
	UE_LOG(LogSGGameplay, Log, TEXT("  ç›®æ ‡ï¼š%s"), InTarget ? *InTarget->GetName() : TEXT("æ— "));
	UE_LOG(LogSGGameplay, Log, TEXT("  èµ·ç‚¹ï¼š%s"), *StartLocation.ToString());
	UE_LOG(LogSGGameplay, Log, TEXT("  ç»ˆç‚¹ï¼š%s"), *TargetLocation.ToString());
	UE_LOG(LogSGGameplay, Log, TEXT("  è·ç¦»ï¼š%.1f"), TotalFlightDistance);
	UE_LOG(LogSGGameplay, Log, TEXT("  é€Ÿåº¦ï¼š%.1f"), FlightSpeed);
	UE_LOG(LogSGGameplay, Log, TEXT("  å¼§åº¦ï¼š%.1f"), ArcHeight);
	UE_LOG(LogSGGameplay, Log, TEXT("  æ¨¡å¼ï¼š%s"), 
		FlightMode == ESGProjectileFlightMode::Linear ? TEXT("ç›´çº¿") :
		FlightMode == ESGProjectileFlightMode::Parabolic ? TEXT("æŠ›ç‰©çº¿") : TEXT("å½’èˆª"));
	UE_LOG(LogSGGameplay, Log, TEXT("========================================"));
}

// ========== è®¾ç½®é£è¡Œé€Ÿåº¦ ==========
void ASG_Projectile::SetFlightSpeed(float NewSpeed)
{
	FlightSpeed = FMath::Max(100.0f, NewSpeed);
	
	// æ›´æ–°å½“å‰é€Ÿåº¦å‘é‡çš„å¤§å°
	if (!CurrentVelocity.IsNearlyZero())
	{
		CurrentVelocity = CurrentVelocity.GetSafeNormal() * FlightSpeed;
	}
}

// ========== ç›´çº¿é£è¡Œ ==========
void ASG_Projectile::UpdateLinearFlight(float DeltaTime)
{
	// è®¡ç®—ç§»åŠ¨è·ç¦»
	float MoveDistance = FlightSpeed * DeltaTime;
	
	// è®¡ç®—æ–¹å‘ï¼ˆæŒç»­æŒ‡å‘ç›®æ ‡ï¼‰
	FVector CurrentLocation = GetActorLocation();
	FVector ToTarget = TargetLocation - CurrentLocation;
	
	if (ToTarget.Size() <= MoveDistance)
	{
		// å·²åˆ°è¾¾ç›®æ ‡ä½ç½®
		SetActorLocation(TargetLocation);
		CurrentVelocity = ToTarget.GetSafeNormal() * FlightSpeed;
	}
	else
	{
		// ç»§ç»­é£è¡Œ
		FVector Direction = ToTarget.GetSafeNormal();
		CurrentVelocity = Direction * FlightSpeed;
		SetActorLocation(CurrentLocation + CurrentVelocity * DeltaTime);
	}
}

// ========== æŠ›ç‰©çº¿é£è¡Œ ==========
void ASG_Projectile::UpdateParabolicFlight(float DeltaTime)
{
	// æ›´æ–°é£è¡Œè¿›åº¦
	float DistanceThisFrame = FlightSpeed * DeltaTime;
	FlightProgress += DistanceThisFrame / TotalFlightDistance;
	FlightProgress = FMath::Clamp(FlightProgress, 0.0f, 1.0f);

	// è®¡ç®—å½“å‰ä½ç½®
	FVector NewLocation = CalculateParabolicPosition(FlightProgress);
	
	// è®¡ç®—é€Ÿåº¦å‘é‡ï¼ˆç”¨äºæ—‹è½¬ï¼‰
	FVector PreviousLocation = GetActorLocation();
	CurrentVelocity = (NewLocation - PreviousLocation) / DeltaTime;
	
	// å¦‚æœé€Ÿåº¦è¿‡å°ï¼Œä½¿ç”¨æ–¹å‘ä¼°ç®—
	if (CurrentVelocity.Size() < 1.0f)
	{
		// ä½¿ç”¨ä¸‹ä¸€å¸§çš„ä½ç½®ä¼°ç®—æ–¹å‘
		float NextProgress = FMath::Clamp(FlightProgress + 0.01f, 0.0f, 1.0f);
		FVector NextLocation = CalculateParabolicPosition(NextProgress);
		CurrentVelocity = (NextLocation - NewLocation).GetSafeNormal() * FlightSpeed;
	}

	// æ›´æ–°ä½ç½®
	SetActorLocation(NewLocation);

	// å¦‚æœç›®æ ‡è¿˜æ´»ç€ï¼ŒåŠ¨æ€æ›´æ–°ç›®æ ‡ä½ç½®
	if (CurrentTarget.IsValid())
	{
		AActor* Target = CurrentTarget.Get();
		FVector NewTargetLocation = Target->GetActorLocation();
		
		// ç„å‡†ç›®æ ‡ä¸­å¿ƒ
		if (ASG_UnitsBase* TargetUnit = Cast<ASG_UnitsBase>(Target))
		{
			if (UCapsuleComponent* Capsule = TargetUnit->GetCapsuleComponent())
			{
				NewTargetLocation.Z += Capsule->GetScaledCapsuleHalfHeight() * 0.5f;
			}
		}
		
		// å¹³æ»‘æ›´æ–°ç›®æ ‡ä½ç½®ï¼ˆé¿å…æŠ–åŠ¨ï¼‰
		TargetLocation = FMath::VInterpTo(TargetLocation, NewTargetLocation, DeltaTime, 5.0f);
	}

#if WITH_EDITOR
	// è°ƒè¯•ç»˜åˆ¶æŠ›ç‰©çº¿
	if (bDrawDebugTrajectory)
	{
		for (float t = 0.0f; t < 1.0f; t += 0.05f)
		{
			FVector P1 = CalculateParabolicPosition(t);
			FVector P2 = CalculateParabolicPosition(t + 0.05f);
			DrawDebugLine(GetWorld(), P1, P2, FColor::Green, false, 0.1f, 0, 1.0f);
		}
	}
#endif
}

// ========== è®¡ç®—æŠ›ç‰©çº¿ä½ç½® ==========
FVector ASG_Projectile::CalculateParabolicPosition(float Progress) const
{
	// çº¿æ€§æ’å€¼åŸºç¡€ä½ç½®
	FVector LinearPosition = FMath::Lerp(StartLocation, TargetLocation, Progress);

	// è®¡ç®—æŠ›ç‰©çº¿é«˜åº¦åç§»
	// ä½¿ç”¨ sin æ›²çº¿ï¼šåœ¨ Progress=0.5 æ—¶è¾¾åˆ°æœ€å¤§é«˜åº¦
	float HeightOffset = FMath::Sin(Progress * PI) * ArcHeight;

	// åº”ç”¨é«˜åº¦åç§»
	return LinearPosition + FVector(0.0f, 0.0f, HeightOffset);
}

// ========== å½’èˆªé£è¡Œ ==========
void ASG_Projectile::UpdateHomingFlight(float DeltaTime)
{
	// æ›´æ–°ç›®æ ‡ä½ç½®
	if (CurrentTarget.IsValid())
	{
		AActor* Target = CurrentTarget.Get();
		TargetLocation = Target->GetActorLocation();
		
		// ç„å‡†ç›®æ ‡ä¸­å¿ƒ
		if (ASG_UnitsBase* TargetUnit = Cast<ASG_UnitsBase>(Target))
		{
			if (UCapsuleComponent* Capsule = TargetUnit->GetCapsuleComponent())
			{
				TargetLocation.Z += Capsule->GetScaledCapsuleHalfHeight() * 0.5f;
			}
		}
	}

	// è®¡ç®—å½“å‰æ–¹å‘å’Œç›®æ ‡æ–¹å‘
	FVector CurrentDirection = CurrentVelocity.GetSafeNormal();
	FVector DesiredDirection = (TargetLocation - GetActorLocation()).GetSafeNormal();

	// è®¡ç®—æœ€å¤§è½¬å‘è§’åº¦
	float MaxTurnAngle = HomingStrength * DeltaTime;

	// æ’å€¼è½¬å‘
	FVector NewDirection = FMath::VInterpNormalRotationTo(
		CurrentDirection,
		DesiredDirection,
		DeltaTime,
		HomingStrength
	);

	// æ›´æ–°é€Ÿåº¦å‘é‡
	CurrentVelocity = NewDirection * FlightSpeed;

	// æ›´æ–°ä½ç½®
	SetActorLocation(GetActorLocation() + CurrentVelocity * DeltaTime);
}

// ========== æ›´æ–°æ—‹è½¬ ==========
void ASG_Projectile::UpdateRotation()
{
	if (!CurrentVelocity.IsNearlyZero())
	{
		FRotator NewRotation = CurrentVelocity.Rotation();
		SetActorRotation(NewRotation);
	}
}

// ========== èƒ¶å›Šä½“ Overlap äº‹ä»¶ ==========
void ASG_Projectile::OnCapsuleOverlap(
	UPrimitiveComponent* OverlappedComponent,
	AActor* OtherActor,
	UPrimitiveComponent* OtherComp,
	int32 OtherBodyIndex,
	bool bFromSweep,
	const FHitResult& SweepResult
)
{
	HandleProjectileImpact(OtherActor, SweepResult);
}

// ========== èƒ¶å›Šä½“ Hit äº‹ä»¶ ==========
void ASG_Projectile::OnCapsuleHit(
	UPrimitiveComponent* HitComponent,
	AActor* OtherActor,
	UPrimitiveComponent* OtherComp,
	FVector NormalImpulse,
	const FHitResult& Hit
)
{
	HandleProjectileImpact(OtherActor, Hit);
}

// ========== ç¢°æ’å¤„ç† ==========
void ASG_Projectile::HandleProjectileImpact(AActor* OtherActor, const FHitResult& Hit)
{
	UE_LOG(LogSGGameplay, Verbose, TEXT("æŠ•å°„ç‰©ç¢°æ’ï¼š%s"), OtherActor ? *OtherActor->GetName() : TEXT("None"));

	if (!OtherActor || OtherActor == GetOwner() || OtherActor == GetInstigator())
	{
		return;
	}

	// ========== æ£€æŸ¥æ˜¯å¦æ˜¯ä¸»åŸ ==========
	ASG_MainCityBase* TargetMainCity = Cast<ASG_MainCityBase>(OtherActor);
	if (TargetMainCity)
	{
		if (TargetMainCity->FactionTag == InstigatorFactionTag)
		{
			UE_LOG(LogSGGameplay, Verbose, TEXT("  ç¢°æ’å‹æ–¹ä¸»åŸï¼Œå¿½ç•¥"));
			return;
		}

		if (HitActors.Contains(OtherActor))
		{
			return;
		}

		if (!TargetMainCity->IsAlive())
		{
			Destroy();
			return;
		}

		UE_LOG(LogSGGameplay, Log, TEXT("  ğŸ° å‡»ä¸­æ•Œæ–¹ä¸»åŸï¼š%s"), *TargetMainCity->GetName());

		FSGProjectileHitInfo HitInfo;
		HitInfo.HitActor = OtherActor;
		HitInfo.HitLocation = Hit.ImpactPoint.IsNearlyZero() ? OtherActor->GetActorLocation() : FVector(Hit.ImpactPoint);
		HitInfo.HitNormal = Hit.ImpactNormal.IsNearlyZero() ? -GetActorForwardVector() : FVector(Hit.ImpactNormal);
		HitInfo.ProjectileDirection = CurrentVelocity.GetSafeNormal();
		HitInfo.ProjectileSpeed = CurrentVelocity.Size();

		ApplyDamageToTarget(OtherActor);
		HitActors.Add(OtherActor);

		ExecuteHitGameplayCue(HitInfo);
		K2_OnHitTarget(HitInfo);
		OnProjectileHitTarget.Broadcast(HitInfo);

		if (!bPenetrate || (MaxPenetrateCount > 0 && HitActors.Num() >= MaxPenetrateCount))
		{
			Destroy();
		}
		return;
	}

	// ========== æ£€æŸ¥æ˜¯å¦æ˜¯å•ä½ ==========
	ASG_UnitsBase* TargetUnit = Cast<ASG_UnitsBase>(OtherActor);
	if (!TargetUnit)
	{
		// æ’å¢™
		FSGProjectileHitInfo HitInfo;
		HitInfo.HitActor = OtherActor;
		HitInfo.HitLocation = Hit.ImpactPoint.IsNearlyZero() ? GetActorLocation() : FVector(Hit.ImpactPoint);
		HitInfo.HitNormal = Hit.ImpactNormal.IsNearlyZero() ? -GetActorForwardVector() : FVector(Hit.ImpactNormal);
		HitInfo.ProjectileDirection = CurrentVelocity.GetSafeNormal();
		HitInfo.ProjectileSpeed = CurrentVelocity.Size();
		
		ExecuteHitGameplayCue(HitInfo);
		K2_OnHitTarget(HitInfo);
		OnProjectileHitTarget.Broadcast(HitInfo);
		
		Destroy();
		return;
	}

	// æ£€æŸ¥é˜µè¥
	if (TargetUnit->FactionTag == InstigatorFactionTag)
	{
		return;
	}

	// æ£€æŸ¥æ˜¯å¦å·²å‡»ä¸­
	if (HitActors.Contains(OtherActor))
	{
		return;
	}

	// æ£€æŸ¥æ˜¯å¦å·²æ­»äº¡
	if (TargetUnit->bIsDead)
	{
		return;
	}

	UE_LOG(LogSGGameplay, Log, TEXT("  ğŸ¯ å‡»ä¸­æ•Œæ–¹å•ä½ï¼š%s"), *TargetUnit->GetName());

	FSGProjectileHitInfo HitInfo;
	HitInfo.HitActor = OtherActor;
	HitInfo.HitLocation = Hit.ImpactPoint.IsNearlyZero() ? OtherActor->GetActorLocation() : FVector(Hit.ImpactPoint);
	HitInfo.HitNormal = Hit.ImpactNormal.IsNearlyZero() ? -GetActorForwardVector() : FVector(Hit.ImpactNormal);
	HitInfo.HitBoneName = Hit.BoneName;
	HitInfo.ProjectileDirection = CurrentVelocity.GetSafeNormal();
	HitInfo.ProjectileSpeed = CurrentVelocity.Size();

	ApplyDamageToTarget(OtherActor);
	HitActors.Add(OtherActor);

	ExecuteHitGameplayCue(HitInfo);
	K2_OnHitTarget(HitInfo);
	OnProjectileHitTarget.Broadcast(HitInfo);

	if (!bPenetrate || (MaxPenetrateCount > 0 && HitActors.Num() >= MaxPenetrateCount))
	{
		Destroy();
	}
}

// ========== åº”ç”¨ä¼¤å®³ ==========
void ASG_Projectile::ApplyDamageToTarget(AActor* Target)
{
	if (!Target)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("ApplyDamageToTarget å¤±è´¥ï¼šç›®æ ‡ä¸ºç©º"));
		return;
	}

	UAbilitySystemComponent* TargetASC = UAbilitySystemGlobals::GetAbilitySystemComponentFromActor(Target);
	if (!TargetASC)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("ApplyDamageToTarget å¤±è´¥ï¼šç›®æ ‡æ²¡æœ‰ ASC"));
		return;
	}

	if (!InstigatorASC)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("ApplyDamageToTarget å¤±è´¥ï¼šæ”»å‡»è€… ASC ä¸ºç©º"));
		return;
	}

	if (!DamageEffectClass)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("ApplyDamageToTarget å¤±è´¥ï¼šä¼¤å®³ GE æœªè®¾ç½®"));
		return;
	}

	FGameplayEffectContextHandle EffectContext = InstigatorASC->MakeEffectContext();
	EffectContext.AddInstigator(GetOwner(), this);

	FGameplayEffectSpecHandle SpecHandle = InstigatorASC->MakeOutgoingSpec(DamageEffectClass, 1.0f, EffectContext);

	if (!SpecHandle.IsValid())
	{
		UE_LOG(LogSGGameplay, Error, TEXT("ApplyDamageToTarget å¤±è´¥ï¼šåˆ›å»º EffectSpec å¤±è´¥"));
		return;
	}

	FGameplayTag DamageTag = FGameplayTag::RequestGameplayTag(FName("Data.Damage"));
	SpecHandle.Data->SetSetByCallerMagnitude(DamageTag, DamageMultiplier);

	FActiveGameplayEffectHandle ActiveHandle = InstigatorASC->ApplyGameplayEffectSpecToTarget(*SpecHandle.Data.Get(), TargetASC);

	if (ActiveHandle.IsValid() || SpecHandle.IsValid())
	{
		UE_LOG(LogSGGameplay, Log, TEXT("    âœ“ æŠ•å°„ç‰©ä¼¤å®³åº”ç”¨æˆåŠŸï¼ˆå€ç‡ï¼š%.2fï¼‰"), DamageMultiplier);
	}
	else
	{
		UE_LOG(LogSGGameplay, Error, TEXT("    âŒ æŠ•å°„ç‰©ä¼¤å®³åº”ç”¨å¤±è´¥"));
	}
}

// ========== GameplayCue å‡½æ•° ==========

void ASG_Projectile::ExecuteHitGameplayCue(const FSGProjectileHitInfo& HitInfo)
{
	if (!HitGameplayCueTag.IsValid())
	{
		return;
	}

	FGameplayCueParameters CueParams;
	CueParams.Location = HitInfo.HitLocation;
	CueParams.Normal = HitInfo.HitNormal;
	CueParams.Instigator = GetInstigator();
	CueParams.EffectCauser = this;
	CueParams.SourceObject = this;
	
	if (InstigatorASC)
	{
		InstigatorASC->ExecuteGameplayCue(HitGameplayCueTag, CueParams);
	}
	else
	{
		if (UGameplayCueManager* CueManager = UAbilitySystemGlobals::Get().GetGameplayCueManager())
		{
			CueManager->HandleGameplayCue(nullptr, HitGameplayCueTag, EGameplayCueEvent::Executed, CueParams);
		}
	}
}

void ASG_Projectile::ActivateTrailGameplayCue()
{
	if (!TrailGameplayCueTag.IsValid() || bTrailCueActive)
	{
		return;
	}

	FGameplayCueParameters CueParams;
	CueParams.Location = GetActorLocation();
	CueParams.Instigator = GetInstigator();
	CueParams.EffectCauser = this;
	CueParams.SourceObject = this;

	if (InstigatorASC)
	{
		InstigatorASC->AddGameplayCue(TrailGameplayCueTag, CueParams);
		bTrailCueActive = true;
	}
}

void ASG_Projectile::RemoveTrailGameplayCue()
{
	if (!TrailGameplayCueTag.IsValid() || !bTrailCueActive)
	{
		return;
	}

	if (InstigatorASC)
	{
		InstigatorASC->RemoveGameplayCue(TrailGameplayCueTag);
		bTrailCueActive = false;
	}
}

void ASG_Projectile::ExecuteDestroyGameplayCue()
{
	if (!DestroyGameplayCueTag.IsValid())
	{
		return;
	}

	FGameplayCueParameters CueParams;
	CueParams.Location = GetActorLocation();
	CueParams.Normal = -GetActorForwardVector();
	CueParams.Instigator = GetInstigator();
	CueParams.EffectCauser = this;

	if (InstigatorASC)
	{
		InstigatorASC->ExecuteGameplayCue(DestroyGameplayCueTag, CueParams);
	}
}
