// SG_PlacementPreview.cpp
// Fill out your copyright notice in the Description page of Project Settings.

#include "Actors/SG_PlacementPreview.h"
#include "Components/StaticMeshComponent.h"
#include "Components/DecalComponent.h"
#include "Data/SG_CardDataBase.h"
#include "Engine/OverlapResult.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Kismet/GameplayStatics.h"
#include "DrawDebugHelpers.h"
#include "Debug/SG_LogCategories.h"
#include "Actors/SG_FrontLineManager.h"
#include "Engine/World.h"
#include "GameFramework/Character.h"

ASG_PlacementPreview::ASG_PlacementPreview()
{
    PrimaryActorTick.bCanEverTick = true;

    // åˆ›å»ºæ ¹ç»„ä»¶
    RootComp = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
    RootComponent = RootComp;

    // åˆ›å»ºé¢„è§ˆç½‘æ ¼ä½“
    PreviewMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("PreviewMesh"));
    PreviewMesh->SetupAttachment(RootComp);
    PreviewMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    PreviewMesh->SetVisibility(false);

    // åˆ›å»ºåŒºåŸŸæŒ‡ç¤ºå™¨ï¼ˆè®¡è°‹å¡Areaå¸¸ç”¨ï¼‰
    AreaIndicator = CreateDefaultSubobject<UDecalComponent>(TEXT("AreaIndicator"));
    AreaIndicator->SetupAttachment(RootComp);
    AreaIndicator->SetVisibility(false);
    AreaIndicator->DecalSize = FVector(100.0f, 100.0f, 100.0f);
    // ğŸ”§ ä¿®æ”¹ - ç¡®ä¿ Decal æœä¸‹æŠ•å°„
    AreaIndicator->SetRelativeRotation(FRotator(-90.0f, 0.0f, 0.0f));

    // åˆå§‹åŒ–
    PreviewLocation = FVector::ZeroVector;
    PreviewRotation = FRotator::ZeroRotator;
    bCanPlace = false;

    // é»˜è®¤è®¾ç½®ï¼šç¢°æ’æ£€æµ‹ä½¿ç”¨ Pawn å¯¹è±¡ç±»å‹
    CollisionObjectTypes.Add(UEngineTypes::ConvertToObjectType(ECC_Pawn));
    
    // ğŸ”§ ä¼˜åŒ– - é»˜è®¤ä»…æ£€æµ‹ WorldStaticï¼Œè¿™æ˜¯å¿½ç•¥ Pawn æœ€å¿«çš„æ–¹æ³•
    bOnlyTraceWorldStatic = true;
}

void ASG_PlacementPreview::BeginPlay()
{
    Super::BeginPlay();
    
    CachedFrontLineManager = ASG_FrontLineManager::GetFrontLineManager(this);
    
    if (CachedFrontLineManager)
    {
        UE_LOG(LogSGGameplay, Verbose, TEXT("âœ“ æ‰¾åˆ°å‰çº¿ç®¡ç†å™¨"));
    }
}

void ASG_PlacementPreview::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);

    // æ›´æ–°ä½ç½®
    UpdatePreviewLocation();

    // æ£€æµ‹æ˜¯å¦å¯æ”¾ç½®
    bCanPlace = CanPlaceAtCurrentLocation();

    // æ›´æ–°é¢œè‰²
    UpdatePreviewColor();
}

void ASG_PlacementPreview::InitializePreview(USG_CardDataBase* InCardData, APlayerController* InPlayerController)
{
    CardData = InCardData;
    PlayerController = InPlayerController;

    if (!CardData || !PlayerController)
    {
        return;
    }

    switch (CardData->PlacementType)
    {
    case ESGPlacementType::Single:
        CreateSinglePointPreview();
        break;

    case ESGPlacementType::Area:
        CreateAreaPreview(); // è®¡è°‹å¡é€šå¸¸èµ°è¿™é‡Œ
        break;

    case ESGPlacementType::Global:
        Destroy(); // ä¸éœ€è¦é¢„è§ˆ
        break;

    default:
        Destroy();
        break;
    }
}

bool ASG_PlacementPreview::CanPlaceAtCurrentLocation() const
{
    // æ£€æŸ¥å¡ç‰Œæ•°æ®
    if (!CardData)
    {
        return false;
    }

    // æ£€æŸ¥ä½ç½®æ˜¯å¦æœ‰æ•ˆ
    if (PreviewLocation.IsNearlyZero())
    {
        return false;
    }
    
    // æ£€æŸ¥å‰çº¿é™åˆ¶
    if (CheckFrontLineViolation())
    {
        return false;
    }

    // æ£€æŸ¥ç¢°æ’
    if (CheckCollision())
    {
        return false;
    }

    return true;
}

void ASG_PlacementPreview::UpdatePreviewLocation()
{
    if (!PlayerController) return;

    // è·å–é¼ æ ‡ä½ç½®
    float MouseX, MouseY;
    if (!PlayerController->GetMousePosition(MouseX, MouseY)) return;

    // è½¬æ¢ä¸ºä¸–ç•Œå°„çº¿
    FVector WorldLocation, WorldDirection;
    if (!PlayerController->DeprojectScreenPositionToWorld(MouseX, MouseY, WorldLocation, WorldDirection)) return;

    FVector Start = WorldLocation;
    FVector End = Start + WorldDirection * RaycastDistance;

    // âœ¨ ä¼˜åŒ– - åŸºç¡€æŸ¥è¯¢å‚æ•°ï¼ˆä¸åŒ…å«æ¯å¸§éå†ï¼ï¼‰
    FCollisionQueryParams QueryParams;
    QueryParams.AddIgnoredActor(this); // å¿½ç•¥è‡ªå·±
    if (APawn* PlayerPawn = PlayerController->GetPawn())
    {
        QueryParams.AddIgnoredActor(PlayerPawn); // å¿½ç•¥ç©å®¶æ§åˆ¶çš„è§’è‰²
    }
    
    // æ‰§è¡Œå°„çº¿æ£€æµ‹
    FHitResult HitResult;
    bool bHit = false;

    // âœ¨ æ ¸å¿ƒé€»è¾‘ï¼šåŒºåˆ†â€œå¼ºåˆ¶é™æ€æ£€æµ‹â€å’Œâ€œè‡ªå®šä¹‰æ£€æµ‹â€
    if (bOnlyTraceWorldStatic)
    {
        // ğŸš€ é«˜æ€§èƒ½æ¨¡å¼ï¼šåªæ£€æµ‹ Staticï¼Œå®Œç¾å¿½ç•¥æ‰€æœ‰å•ä½ï¼ˆDynamic/Pawnï¼‰
        FCollisionObjectQueryParams ObjectParams;
        ObjectParams.AddObjectTypesToQuery(ECC_WorldStatic); 
        // ä¹Ÿå¯ä»¥åŠ ä¸Š Landscape å¦‚æœå®ƒæ˜¯å•ç‹¬çš„ç±»å‹
        
        bHit = GetWorld()->LineTraceSingleByObjectType(
            HitResult,
            Start,
            End,
            ObjectParams,
            QueryParams
        );
    }
    else
    {
        // ä¼ ç»Ÿçš„é€šé“/ç±»å‹æ··åˆæ¨¡å¼
        if (GroundObjectTypes.Num() > 0)
        {
            FCollisionObjectQueryParams ObjectParams;
            for (auto ObjectType : GroundObjectTypes)
            {
                ObjectParams.AddObjectTypesToQuery(UEngineTypes::ConvertToCollisionChannel(ObjectType));
            }
            bHit = GetWorld()->LineTraceSingleByObjectType(HitResult, Start, End, ObjectParams, QueryParams);
        }
        else
        {
            bHit = GetWorld()->LineTraceSingleByChannel(HitResult, Start, End, GroundTraceChannel, QueryParams);
        }
    }

    // æ›´æ–°ä½ç½®
    if (bHit)
    {
        // âœ¨ æ–°å¢ - æ›´åŠ è´´åˆåœ°é¢çš„æ³•çº¿æ—‹è½¬ï¼ˆå¯é€‰ï¼Œå¦‚æœæ˜¯Decalä¼šè‡ªåŠ¨è´´åˆï¼Œä½†Meshéœ€è¦æ—‹è½¬ï¼‰
        PreviewLocation = HitResult.Location + HitResult.ImpactNormal * GroundOffset;
        
        // å¦‚æœæ˜¯ Meshï¼Œå¯ä»¥æ ¹æ®æ³•çº¿è°ƒæ•´æ—‹è½¬
        // FRotator NewRot = FRotationMatrix::MakeFromZ(HitResult.ImpactNormal).Rotator();
        // SetActorRotation(NewRot); // æ ¹æ®éœ€æ±‚å¼€å¯

        SetActorLocation(PreviewLocation);

        if (bDebugGroundTrace)
        {
            DrawDebugLine(GetWorld(), Start, HitResult.Location, FColor::Green, false, 0.0f, 0, 1.0f);
            DrawDebugSphere(GetWorld(), HitResult.Location, 10.0f, 8, FColor::Cyan, false, 0.0f);
        }
    }
    else
    {
        // æœªæ£€æµ‹åˆ°åœ°é¢ï¼ŒæŠ•å½±åˆ°è¿œç«¯æˆ–ä¿æŒåŸä½
        if (bDebugGroundTrace)
        {
            DrawDebugLine(GetWorld(), Start, End, FColor::Red, false, 0.0f, 0, 1.0f);
        }
    }
}

bool ASG_PlacementPreview::CheckCollision() const
{
   // å¦‚æœæ˜¯è®¡è°‹å¡ï¼ˆAreaæ¨¡å¼ï¼‰ï¼Œä¸”ä¸éœ€è¦æ£€æµ‹ç¢°æ’ï¼ˆä¾‹å¦‚ç«çŸ¢è®¡å¯ä»¥éšä¾¿æ”¾ï¼‰ï¼Œåˆ™ç›´æ¥è¿”å› falseï¼ˆæ— ç¢°æ’ï¼‰
    // é€šå¸¸è®¡è°‹å¡æ˜¯å¯ä»¥é‡å é‡Šæ”¾çš„ï¼Œé™¤éä½ çš„è®¾è®¡ä¸å…è®¸
    if (CardData && CardData->PlacementType == ESGPlacementType::Area)
    {
        // ğŸ”§ è¿™é‡Œå‡è®¾è®¡è°‹å¡ä¸éœ€è¦é¿å¼€å•ä½ã€‚å¦‚æœéœ€è¦ï¼Œè¯·ä¿ç•™ä¸‹æ–¹é€»è¾‘ã€‚
        // return false; 
    }
    
    if (PreviewLocation.IsNearlyZero()) return true;

    FCollisionQueryParams QueryParams;
    QueryParams.AddIgnoredActor(this);
    if (PlayerController && PlayerController->GetPawn())
    {
        QueryParams.AddIgnoredActor(PlayerController->GetPawn());
    }

    // ä»…å¿½ç•¥å½“å‰å·²ç»ç¼“å­˜çš„ï¼Œä¸æ¯å¸§éå†
    // å¦‚æœæœ‰ç‰¹æ®Šéœ€æ±‚è¦å¿½ç•¥ç‰¹å®šå•ä½ï¼Œå»ºè®®åœ¨ Start æ—¶è·å–ä¸€æ¬¡
    
    TArray<FOverlapResult> OverlapResults;
    bool bHasOverlap = false;

    if (CollisionObjectTypes.Num() > 0)
    {
        FCollisionObjectQueryParams ObjectParams;
        for (auto ObjectType : CollisionObjectTypes)
        {
            ObjectParams.AddObjectTypesToQuery(UEngineTypes::ConvertToCollisionChannel(ObjectType));
        }
        
        bHasOverlap = GetWorld()->OverlapMultiByObjectType(
            OverlapResults,
            PreviewLocation,
            FQuat::Identity,
            ObjectParams,
            FCollisionShape::MakeSphere(CollisionCheckRadius),
            QueryParams
        );
    }
    else
    {
        bHasOverlap = GetWorld()->OverlapMultiByChannel(
            OverlapResults,
            PreviewLocation,
            FQuat::Identity,
            CollisionCheckChannel,
            FCollisionShape::MakeSphere(CollisionCheckRadius),
            QueryParams
        );
    }

    int32 ValidOverlapCount = 0;
    for (const FOverlapResult& Result : OverlapResults)
    {
        AActor* OverlappedActor = Result.GetActor();
        if (!OverlappedActor || OverlappedActor == this) continue;

        if (bIgnoreDeadUnits)
        {
            if (ACharacter* Character = Cast<ACharacter>(OverlappedActor))
            {
                // å¦‚æœæ˜¯æ­»äº¡å•ä½ï¼Œå¿½ç•¥
                // æ³¨æ„ï¼šè¿™é‡Œéœ€è¦ä½ çš„ UnitBase æœ‰ IsDead æ¥å£æˆ–è€… LifeSpan
                // å‡è®¾ LifeSpan > 0 æ„å‘³ç€æ­£åœ¨æ­»äº¡è¿‡ç¨‹ä¸­
                if (Character->GetLifeSpan() > 0.0f) continue;
            }
        }
        ValidOverlapCount++;
    }

    return (ValidOverlapCount > 0);
}

void ASG_PlacementPreview::BuildGroundTraceIgnoreList(FCollisionQueryParams& OutParams) const
{
    // å¿½ç•¥é…ç½®çš„ç±»
    for (TSubclassOf<AActor> ActorClass : GroundTraceIgnoredClasses)
    {
        if (!ActorClass)
        {
            continue;
        }

        TArray<AActor*> FoundActors;
        UGameplayStatics::GetAllActorsOfClass(GetWorld(), ActorClass, FoundActors);
        
        for (AActor* Actor : FoundActors)
        {
            if (Actor)
            {
                OutParams.AddIgnoredActor(Actor);
            }
        }
    }

    // å§‹ç»ˆå¿½ç•¥å…¶ä»–é¢„è§ˆ Actor
    TArray<AActor*> AllPreviews;
    UGameplayStatics::GetAllActorsOfClass(GetWorld(), ASG_PlacementPreview::StaticClass(), AllPreviews);
    for (AActor* Preview : AllPreviews)
    {
        if (Preview)
        {
            OutParams.AddIgnoredActor(Preview);
        }
    }
}


bool ASG_PlacementPreview::CheckFrontLineViolation() const
{
    if (!CardData)
    {
        return false;
    }
    
    if (CardData->PlacementType == ESGPlacementType::Global)
    {
        return false;
    }
    
    if (!CardData->bRespectFrontLine)
    {
        return false;
    }
    
    if (!CachedFrontLineManager)
    {
        return false;
    }
    
    ESGFrontLineZone Zone = CachedFrontLineManager->GetZoneAtLocation(PreviewLocation);
    bool bIsValidPlacement = (Zone == ESGFrontLineZone::PlayerZone) || (Zone == ESGFrontLineZone::NeutralZone);
    
    return !bIsValidPlacement;
}

void ASG_PlacementPreview::UpdatePreviewColor()
{
    FLinearColor TargetColor = bCanPlace ? ValidPlacementColor : InvalidPlacementColor;

    if (PreviewMesh && PreviewMesh->IsVisible())
    {
        if (!PreviewMaterialInstance && PreviewMesh->GetMaterial(0))
        {
            PreviewMaterialInstance = PreviewMesh->CreateDynamicMaterialInstance(0);
        }

        if (PreviewMaterialInstance)
        {
            PreviewMaterialInstance->SetVectorParameterValue(TEXT("PreviewColor"), TargetColor);
            PreviewMaterialInstance->SetScalarParameterValue(TEXT("Opacity"), PreviewOpacity);
        }
    }

    if (AreaIndicator && AreaIndicator->IsVisible())
    {
        if (AreaIndicator->GetDecalMaterial())
        {
            UMaterialInstanceDynamic* DecalMaterial = AreaIndicator->CreateDynamicMaterialInstance();
            if (DecalMaterial)
            {
                DecalMaterial->SetVectorParameterValue(TEXT("Color"), TargetColor);
                DecalMaterial->SetScalarParameterValue(TEXT("Opacity"), PreviewOpacity);
            }
        }
    }
}

void ASG_PlacementPreview::CreateSinglePointPreview()
{
    UE_LOG(LogTemp, Log, TEXT("åˆ›å»ºå•ç‚¹é¢„è§ˆ"));

    PreviewMesh->SetVisibility(true);

    if (!PreviewMesh->GetStaticMesh())
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> SphereMesh(TEXT("/Engine/BasicShapes/Sphere"));
        if (SphereMesh.Succeeded())
        {
            PreviewMesh->SetStaticMesh(SphereMesh.Object);
            PreviewMesh->SetRelativeScale3D(FVector(1.0f, 1.0f, 1.0f));
        }
    }

    AreaIndicator->SetVisibility(false);
}

void ASG_PlacementPreview::CreateAreaPreview()
{
    UE_LOG(LogTemp, Log, TEXT("åˆ›å»ºåŒºåŸŸé¢„è§ˆ"));

    // åŒºåŸŸé¢„è§ˆï¼ˆå¦‚ç«çŸ¢è®¡ï¼‰
    PreviewMesh->SetVisibility(false);
    AreaIndicator->SetVisibility(true);

    if (CardData)
    {
        // Decal çš„ Size X/Y/Z å¯¹åº”ï¼šåšåº¦ / å®½ / é«˜
        // CardData->PlacementAreaSize æ˜¯åŠå¾„è¿˜æ˜¯ç›´å¾„ï¼Ÿå‡è®¾æ˜¯åŠå¾„
        float Radius = CardData->PlacementAreaSize.X; // å‡è®¾ X æ˜¯åŠå¾„
        AreaIndicator->DecalSize = FVector(200.0f, Radius, Radius); // 200åšåº¦ï¼Œç¡®ä¿è¦†ç›–æ–œå¡
    }
 
}
