// ğŸ“„ æ–‡ä»¶ï¼šSource/Sguo/Private/Units/SG_StationaryUnit.cpp
// ğŸ”§ ä¿®æ”¹ - å®ç°è®¡è°‹æŠ€èƒ½æ‰§è¡Œç³»ç»Ÿ
// âœ… è¿™æ˜¯å®Œæ•´æ–‡ä»¶

#include "Units/SG_StationaryUnit.h"
#include "AI/SG_StationaryAIController.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Debug/SG_LogCategories.h"
#include "Animation/AnimInstance.h"
#include "Animation/AnimMontage.h"
#include "Actors/SG_Projectile.h"
#include "AbilitySystemComponent.h"
#include "AbilitySystemGlobals.h"
#include "AbilitySystem/SG_AttributeSet.h"
#include "Data/Type/SG_UnitDataTable.h"

ASG_StationaryUnit::ASG_StationaryUnit()
{
    bEnableHover = false;
    HoverHeight = 0;
    bDisableGravity = true;
    bCanBeTargeted = true;
    bDisableMovement = true;

    // è®¾ç½®é»˜è®¤ AI æ§åˆ¶å™¨ç±»
    AIControllerClass = ASG_StationaryAIController::StaticClass();
    AutoPossessAI = EAutoPossessAI::PlacedInWorldOrSpawned;

    // âœ¨ æ–°å¢ - å¯ç”¨ Tick
    PrimaryActorTick.bCanEverTick = true;
}

void ASG_StationaryUnit::BeginPlay()
{
    Super::BeginPlay();
    ApplyStationarySettings();

    UE_LOG(LogSGUnit, Log, TEXT("[ç«™æ¡©å•ä½] %s åˆå§‹åŒ–å®Œæˆ | æµ®ç©º:%s | é«˜åº¦:%.1f | å¯è¢«é€‰ä¸­:%s | ç¦ç”¨ç§»åŠ¨:%s"),
        *GetName(),
        bEnableHover ? TEXT("æ˜¯") : TEXT("å¦"),
        HoverHeight,
        bCanBeTargeted ? TEXT("æ˜¯") : TEXT("å¦"),
        bDisableMovement ? TEXT("æ˜¯") : TEXT("å¦")
    );
}

// âœ¨ æ–°å¢ - Tick å‡½æ•°
void ASG_StationaryUnit::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);

    // æ›´æ–°è®¡è°‹æŠ€èƒ½
    if (StrategySkillState == ESGStrategySkillState::Executing)
    {
        UpdateStrategySkill(DeltaTime);
    }
}

bool ASG_StationaryUnit::CanBeTargeted() const
{
    return bCanBeTargeted;
}

void ASG_StationaryUnit::ApplyStationarySettings()
{
    if (bDisableMovement)
    {
        DisableMovementCapability();
    }

    if (bEnableHover)
    {
        ApplyHoverEffect();
    }
}

void ASG_StationaryUnit::DisableMovementCapability()
{
    UCharacterMovementComponent* MovementComp = GetCharacterMovement();
    
    if (!MovementComp)
    {
        return;
    }

    MovementComp->MaxWalkSpeed = 0.0f;
    MovementComp->MaxAcceleration = 0.0f;
    
    if (bEnableHover || bDisableGravity)
    {
        MovementComp->SetMovementMode(MOVE_Flying);
        MovementComp->GravityScale = 0.0f;
    }
    else
    {
        MovementComp->SetMovementMode(MOVE_Walking);
    }
    
    MovementComp->bUseRVOAvoidance = false;
}

void ASG_StationaryUnit::ApplyHoverEffect()
{
    FVector CurrentLocation = GetActorLocation();
    FVector NewLocation = CurrentLocation;
    NewLocation.Z += HoverHeight;
    
    SetActorLocation(NewLocation, false, nullptr, ETeleportType::TeleportPhysics);
    
    if (bDisableGravity)
    {
        UCharacterMovementComponent* MovementComp = GetCharacterMovement();
        
        if (MovementComp)
        {
            MovementComp->GravityScale = 0.0f;
            MovementComp->SetMovementMode(MOVE_Flying);
        }
    }
}

// ========== âœ¨ æ–°å¢ - è®¡è°‹æŠ€èƒ½ç³»ç»Ÿå®ç° ==========

/**
 * @brief å¼€å§‹æ‰§è¡Œè®¡è°‹æŠ€èƒ½
 */
void ASG_StationaryUnit::StartStrategySkill(
    const FVector& TargetLocation,
    float AreaRadius,
    float Duration,
    float FireInterval,
    int32 ArrowsPerRound,
    TSubclassOf<AActor> ProjectileClass,
    UAnimMontage* AttackMontage)
{
    UE_LOG(LogSGUnit, Log, TEXT("[ç«™æ¡©å•ä½] %s å¼€å§‹è®¡è°‹æŠ€èƒ½"), *GetName());
    UE_LOG(LogSGUnit, Log, TEXT("  ç›®æ ‡ä½ç½®: %s"), *TargetLocation.ToString());
    UE_LOG(LogSGUnit, Log, TEXT("  åŒºåŸŸåŠå¾„: %.0f"), AreaRadius);
    UE_LOG(LogSGUnit, Log, TEXT("  æŒç»­æ—¶é—´: %.1f ç§’"), Duration);
    UE_LOG(LogSGUnit, Log, TEXT("  å°„å‡»é—´éš”: %.2f ç§’"), FireInterval);
    UE_LOG(LogSGUnit, Log, TEXT("  æ¯è½®æ•°é‡: %d"), ArrowsPerRound);

    // æ‰“æ–­å½“å‰æ™®é€šæ”»å‡»
    if (bIsAttacking)
    {
        if (USkeletalMeshComponent* MeshComp = GetMesh())
        {
            if (UAnimInstance* AnimInstance = MeshComp->GetAnimInstance())
            {
                AnimInstance->Montage_Stop(0.1f);
            }
        }
        bIsAttacking = false;
    }

    // è®¾ç½®è®¡è°‹æŠ€èƒ½å‚æ•°
    StrategySkillState = ESGStrategySkillState::Executing;
    StrategySkillRemainingTime = Duration;
    StrategySkillFireTimer = 0.0f;  // ç«‹å³å¼€å§‹ç¬¬ä¸€æ¬¡å°„å‡»
    CurrentFireInterval = FireInterval;
    StrategySkillTargetLocation = TargetLocation;
    StrategySkillAreaRadius = AreaRadius;
    StrategySkillArrowsPerRound = ArrowsPerRound;

    // è®¾ç½®æŠ•å°„ç‰©ç±»ï¼ˆä¼˜å…ˆä½¿ç”¨ä¼ å…¥çš„ï¼Œå…¶æ¬¡ä½¿ç”¨ DataTable é…ç½®ï¼‰
    if (ProjectileClass)
    {
        CurrentProjectileClass = ProjectileClass;
    }
    else
    {
        CurrentProjectileClass = GetDataTableProjectileClass();
    }

    // è®¾ç½®æ”»å‡»è’™å¤ªå¥‡ï¼ˆä¼˜å…ˆä½¿ç”¨ä¼ å…¥çš„ï¼Œå…¶æ¬¡ä½¿ç”¨ DataTable é…ç½®ï¼‰
    if (AttackMontage)
    {
        CurrentAttackMontage = AttackMontage;
    }
    else
    {
        CurrentAttackMontage = GetDataTableAttackMontage();
    }

    UE_LOG(LogSGUnit, Log, TEXT("  æŠ•å°„ç‰©ç±»: %s"), 
        CurrentProjectileClass ? *CurrentProjectileClass->GetName() : TEXT("é»˜è®¤"));
    UE_LOG(LogSGUnit, Log, TEXT("  æ”»å‡»è’™å¤ªå¥‡: %s"), 
        CurrentAttackMontage ? *CurrentAttackMontage->GetName() : TEXT("æ— "));

    // å…¼å®¹æ—§ä»£ç 
    bIsExecutingFireArrow = true;
}

/**
 * @brief åœæ­¢è®¡è°‹æŠ€èƒ½
 */
void ASG_StationaryUnit::StopStrategySkill()
{
    UE_LOG(LogSGUnit, Log, TEXT("[ç«™æ¡©å•ä½] %s åœæ­¢è®¡è°‹æŠ€èƒ½"), *GetName());

    StrategySkillState = ESGStrategySkillState::None;
    StrategySkillRemainingTime = 0.0f;
    StrategySkillFireTimer = 0.0f;
    CurrentFireInterval = 0.0f;
    StrategySkillTargetLocation = FVector::ZeroVector;
    StrategySkillAreaRadius = 0.0f;
    StrategySkillArrowsPerRound = 1;
    CurrentProjectileClass = nullptr;
    CurrentAttackMontage = nullptr;

    // å…¼å®¹æ—§ä»£ç 
    bIsExecutingFireArrow = false;
}

/**
 * @brief æ›´æ–°è®¡è°‹æŠ€èƒ½é€»è¾‘
 * @param DeltaTime å¸§é—´éš”
 */
void ASG_StationaryUnit::UpdateStrategySkill(float DeltaTime)
{
    // æ›´æ–°å‰©ä½™æ—¶é—´
    StrategySkillRemainingTime -= DeltaTime;

    // æ£€æŸ¥æ˜¯å¦ç»“æŸ
    if (StrategySkillRemainingTime <= 0.0f)
    {
        StopStrategySkill();
        return;
    }

    // æ›´æ–°å°„å‡»è®¡æ—¶å™¨
    StrategySkillFireTimer += DeltaTime;

    // æ£€æŸ¥æ˜¯å¦åˆ°è¾¾å°„å‡»é—´éš”
    if (StrategySkillFireTimer >= CurrentFireInterval)
    {
        StrategySkillFireTimer = 0.0f;
        ExecuteStrategyFire();
    }
}

/**
 * @brief æ‰§è¡Œä¸€æ¬¡è®¡è°‹æŠ€èƒ½å°„å‡»
 */
void ASG_StationaryUnit::ExecuteStrategyFire()
{
    if (StrategySkillState != ESGStrategySkillState::Executing)
    {
        return;
    }

    UE_LOG(LogSGUnit, Verbose, TEXT("[ç«™æ¡©å•ä½] %s æ‰§è¡Œè®¡è°‹å°„å‡» x%d"), 
        *GetName(), StrategySkillArrowsPerRound);

    // ========== æ’­æ”¾æ”»å‡»è’™å¤ªå¥‡ ==========
    if (CurrentAttackMontage)
    {
        if (USkeletalMeshComponent* MeshComp = GetMesh())
        {
            if (UAnimInstance* AnimInstance = MeshComp->GetAnimInstance())
            {
                // ğŸ”§ æ ¸å¿ƒï¼šæ ¹æ®å°„å‡»é—´éš”è®¡ç®—æ’­æ”¾é€Ÿç‡
                // æ’­æ”¾é€Ÿç‡ = è’™å¤ªå¥‡æ—¶é•¿ / å°„å‡»é—´éš”
                // ç¡®ä¿è’™å¤ªå¥‡åœ¨ä¸‹ä¸€æ¬¡å°„å‡»å‰æ’­æ”¾å®Œæ¯•
                float MontageLength = CurrentAttackMontage->GetPlayLength();
                float PlayRate = 1.0f;
                
                if (CurrentFireInterval > 0.0f && MontageLength > 0.0f)
                {
                    // è®¡ç®—éœ€è¦çš„æ’­æ”¾é€Ÿç‡
                    // å¦‚æœè’™å¤ªå¥‡æ—¶é•¿å¤§äºå°„å‡»é—´éš”ï¼Œéœ€è¦åŠ é€Ÿæ’­æ”¾
                    PlayRate = MontageLength / CurrentFireInterval;
                    
                    // é™åˆ¶æœ€å¤§æ’­æ”¾é€Ÿç‡ï¼Œé¿å…åŠ¨ç”»è¿‡å¿«
                    PlayRate = FMath::Clamp(PlayRate, 0.5f, 5.0f);
                    
                    // åŒæ—¶è€ƒè™‘æ”»å‡»é€Ÿåº¦å±æ€§
                    if (AttributeSet)
                    {
                        PlayRate *= AttributeSet->GetAttackSpeed();
                    }
                }

                AnimInstance->Montage_Play(CurrentAttackMontage, PlayRate);

                UE_LOG(LogSGUnit, Verbose, TEXT("  æ’­æ”¾è’™å¤ªå¥‡: %s (é€Ÿç‡: %.2f, é—´éš”: %.2f, æ—¶é•¿: %.2f)"),
                    *CurrentAttackMontage->GetName(),
                    PlayRate,
                    CurrentFireInterval,
                    MontageLength);
            }
        }
    }

    // ========== å‘å°„æŠ•å°„ç‰© ==========
    for (int32 i = 0; i < StrategySkillArrowsPerRound; ++i)
    {
        // åœ¨åŒºåŸŸå†…éšæœºä½ç½®
        FVector RandomOffset = FVector(
            FMath::FRandRange(-StrategySkillAreaRadius, StrategySkillAreaRadius),
            FMath::FRandRange(-StrategySkillAreaRadius, StrategySkillAreaRadius),
            0.0f
        );
        
        // ç¡®ä¿éšæœºç‚¹åœ¨åœ†å½¢åŒºåŸŸå†…
        while (RandomOffset.Size2D() > StrategySkillAreaRadius)
        {
            RandomOffset = FVector(
                FMath::FRandRange(-StrategySkillAreaRadius, StrategySkillAreaRadius),
                FMath::FRandRange(-StrategySkillAreaRadius, StrategySkillAreaRadius),
                0.0f
            );
        }

        FVector TargetPos = StrategySkillTargetLocation + RandomOffset;

        // å‘å°„ç«çŸ¢
        FireArrow(TargetPos, CurrentProjectileClass);
    }
}

/**
 * @brief è·å– DataTable ä¸­é…ç½®çš„æ”»å‡»è’™å¤ªå¥‡
 */
UAnimMontage* ASG_StationaryUnit::GetDataTableAttackMontage(int32 AbilityIndex) const
{
    if (CachedAttackAbilities.IsValidIndex(AbilityIndex))
    {
        return CachedAttackAbilities[AbilityIndex].Montage;
    }
    return nullptr;
}

/**
 * @brief è·å– DataTable ä¸­é…ç½®çš„æŠ•å°„ç‰©ç±»
 */
TSubclassOf<AActor> ASG_StationaryUnit::GetDataTableProjectileClass(int32 AbilityIndex) const
{
    if (CachedAttackAbilities.IsValidIndex(AbilityIndex))
    {
        return CachedAttackAbilities[AbilityIndex].ProjectileClass;
    }
    return nullptr;
}

// ========== æ—§ç‰ˆç«çŸ¢æ¥å£ï¼ˆä¿æŒå…¼å®¹ï¼‰ ==========

void ASG_StationaryUnit::StartFireArrowSkill()
{
    UE_LOG(LogSGUnit, Log, TEXT("[ç«™æ¡©å•ä½] %s å¼€å§‹ç«çŸ¢æŠ€èƒ½ï¼ˆæ—§æ¥å£ï¼‰"), *GetName());

    if (bIsAttacking)
    {
        if (USkeletalMeshComponent* MeshComp = GetMesh())
        {
            if (UAnimInstance* AnimInstance = MeshComp->GetAnimInstance())
            {
                AnimInstance->Montage_Stop(0.2f);
            }
        }
        bIsAttacking = false;
    }

    bIsExecutingFireArrow = true;

    if (CachedAttackAbilities.Num() > 0)
    {
        CachedOriginalProjectileClass = CachedAttackAbilities[CurrentAttackIndex].ProjectileClass;
    }
}

void ASG_StationaryUnit::EndFireArrowSkill()
{
    UE_LOG(LogSGUnit, Log, TEXT("[ç«™æ¡©å•ä½] %s ç»“æŸç«çŸ¢æŠ€èƒ½ï¼ˆæ—§æ¥å£ï¼‰"), *GetName());

    bIsExecutingFireArrow = false;

    if (CachedOriginalProjectileClass && CachedAttackAbilities.Num() > 0)
    {
        CachedAttackAbilities[CurrentAttackIndex].ProjectileClass = CachedOriginalProjectileClass;
    }
    
    CachedOriginalProjectileClass = nullptr;
}

AActor* ASG_StationaryUnit::FireArrow(const FVector& TargetLocation, TSubclassOf<AActor> ProjectileClassOverride)
{
    // ç¡®å®šä½¿ç”¨çš„æŠ•å°„ç‰©ç±»
    TSubclassOf<AActor> ProjectileClass = ProjectileClassOverride;
    if (!ProjectileClass)
    {
        ProjectileClass = GetFireArrowProjectileClass();
    }
    if (!ProjectileClass)
    {
        ProjectileClass = ASG_Projectile::StaticClass();
    }

    // è·å–å‘å°„ä½ç½®
    FVector SpawnLocation = GetActorLocation();
    
    // è®¡ç®—å‘å°„æ–¹å‘
    FVector ToTarget = TargetLocation - SpawnLocation;
    FRotator SpawnRotation = ToTarget.Rotation();

    // ç”ŸæˆæŠ•å°„ç‰©
    FActorSpawnParameters SpawnParams;
    SpawnParams.Owner = this;
    SpawnParams.Instigator = this;
    SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;

    AActor* SpawnedActor = GetWorld()->SpawnActor<AActor>(
        ProjectileClass,
        SpawnLocation,
        SpawnRotation,
        SpawnParams
    );

    // åˆå§‹åŒ–æŠ•å°„ç‰©
    if (ASG_Projectile* Projectile = Cast<ASG_Projectile>(SpawnedActor))
    {
        UAbilitySystemComponent* MyASC = GetAbilitySystemComponent();

        Projectile->InitializeProjectileToLocation(
            MyASC,
            FactionTag,
            TargetLocation,
            -1.0f
        );

        Projectile->TargetMode = ESGProjectileTargetMode::TargetLocation;
    }

    return SpawnedActor;
}

TSubclassOf<AActor> ASG_StationaryUnit::GetFireArrowProjectileClass() const
{
    if (FireArrowProjectileClass)
    {
        return FireArrowProjectileClass;
    }

    if (CachedAttackAbilities.Num() > 0 && CachedAttackAbilities[CurrentAttackIndex].ProjectileClass)
    {
        return CachedAttackAbilities[CurrentAttackIndex].ProjectileClass;
    }

    return ASG_Projectile::StaticClass();
}
