// Fill out your copyright notice in the Description page of Project Settings.


#include "Units/SG_UnitsBase.h"

#include "Debug/SG_LogCategories.h"
#include "AbilitySystem/SG_AbilitySystemComponent.h"
#include "AbilitySystem/SG_AttributeSet.h"
#include "GameFramework/CharacterMovementComponent.h"  // å¿…é¡»åŒ…å«
#include "Components/CapsuleComponent.h"                // å¿…é¡»åŒ…å«
#include "Kismet/GameplayStatics.h"
// âœ¨ æ–°å¢ - DataTable ç›¸å…³å¤´æ–‡ä»¶
#include "Data/Type/SG_UnitDataTable.h"
#include "Engine/DataTable.h"
// âœ¨ æ–°å¢ - Gameplay Ability ç›¸å…³å¤´æ–‡ä»¶
#include "AbilitySystemGlobals.h"
#include "Abilities/GameplayAbility.h"     

// æ„é€ å‡½æ•°
ASG_UnitsBase::ASG_UnitsBase()
{
	// å¯ç”¨ Tickï¼ˆå¦‚æœéœ€è¦çš„è¯ï¼‰
	PrimaryActorTick.bCanEverTick = true;

	// åˆ›å»º Ability System Component
	// ä¸ºä»€ä¹ˆåœ¨æ„é€ å‡½æ•°åˆ›å»ºï¼šç»„ä»¶å¿…é¡»åœ¨æ„é€ æ—¶åˆ›å»º
	AbilitySystemComponent = CreateDefaultSubobject<USG_AbilitySystemComponent>(TEXT("AbilitySystemComponent"));
	// è®¾ç½®å¤åˆ¶æ¨¡å¼ï¼ˆå•äººæ¸¸æˆå¯ä»¥ä¸è®¾ç½®ï¼Œä½†ä¸ºäº†æ‰©å±•æ€§è¿˜æ˜¯è®¾ç½®ï¼‰
	AbilitySystemComponent->SetIsReplicated(true);
	// è®¾ç½®å¤åˆ¶æ¨¡å¼ä¸º Mixedï¼ˆé€‚åˆå¤§å¤šæ•°æƒ…å†µï¼‰
	AbilitySystemComponent->SetReplicationMode(EGameplayEffectReplicationMode::Mixed);

	// åˆ›å»º Attribute Set
	// ä¸ºä»€ä¹ˆç”¨ CreateDefaultSubobjectï¼šç¡®ä¿åœ¨æ„é€ æ—¶åˆ›å»ºï¼Œæ”¯æŒç½‘ç»œå¤åˆ¶
	AttributeSet = CreateDefaultSubobject<USG_AttributeSet>(TEXT("AttributeSet"));
}

// è·å– AbilitySystemComponentï¼ˆGAS æ¥å£ï¼‰
UAbilitySystemComponent* ASG_UnitsBase::GetAbilitySystemComponent() const
{
	return AbilitySystemComponent;
}

// BeginPlay
void ASG_UnitsBase::BeginPlay()
{
	Super::BeginPlay();
	
	UE_LOG(LogTemp, Log, TEXT("è§’è‰²ç”Ÿæˆï¼š%s"), *GetName());
	
	// âœ¨ æ–°å¢ - ä» DataTable åŠ è½½é…ç½®
	// å¦‚æœå¯ç”¨äº† DataTable é…ç½®ï¼Œåœ¨åˆå§‹åŒ–å‰åŠ è½½æ•°æ®
	if (bUseDataTable && UnitDataTable && !UnitDataRowName.IsNone())
	{
		LoadUnitDataFromTable();
	}
	
	// âœ¨ æ–°å¢ - æˆäºˆæ”»å‡»èƒ½åŠ›
	// åœ¨åˆå§‹åŒ–åæˆäºˆæ”»å‡»èƒ½åŠ›
	GrantAttackAbility();
	
	// âœ¨ æ–°å¢ - è‡ªåŠ¨ç”ŸæˆAIæ§åˆ¶å™¨
	if (bUseAIController && !Controller && AIControllerClass)
	{
		// ä½¿ç”¨SpawnDefaultControllerä¼šè°ƒç”¨AIControllerClass
		AutoPossessAI = EAutoPossessAI::PlacedInWorldOrSpawned;
		SpawnDefaultController();
		UE_LOG(LogSGGameplay, Log, TEXT("âœ… è‡ªåŠ¨ç”ŸæˆAIæ§åˆ¶å™¨ï¼š%s"), *AIControllerClass->GetName());
	}
}

// è¢«æ§åˆ¶æ—¶è°ƒç”¨
void ASG_UnitsBase::PossessedBy(AController* NewController)
{
	Super::PossessedBy(NewController);
	
	// åˆå§‹åŒ– ASCï¼ˆæœåŠ¡å™¨ç«¯ï¼‰
	if (AbilitySystemComponent)
	{
		// è®¾ç½® ASC çš„ Owner å’Œ Avatar
		// Ownerï¼šæ‹¥æœ‰æ­¤ ASC çš„ Actorï¼ˆé€šå¸¸æ˜¯ PlayerState æˆ– Characterï¼‰
		// Avatarï¼šASC ä½œç”¨çš„ Actorï¼ˆé€šå¸¸æ˜¯ Characterï¼‰
		AbilitySystemComponent->InitAbilityActorInfo(this, this);
		
		UE_LOG(LogTemp, Log, TEXT("âœ“ ASC åˆå§‹åŒ–å®Œæˆï¼š%s"), *GetName());
	}
}

/**
 * @brief åˆå§‹åŒ–è§’è‰²
 * @param InFactionTag é˜µè¥æ ‡ç­¾
 * @param HealthMultiplier ç”Ÿå‘½å€¼å€ç‡
 * @param DamageMultiplier ä¼¤å®³å€ç‡
 * @param SpeedMultiplier é€Ÿåº¦å€ç‡
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - è®¾ç½®é˜µè¥æ ‡ç­¾
 * - åˆå§‹åŒ–å±æ€§å€¼
 * - ç»‘å®šå±æ€§å˜åŒ–å§”æ‰˜
 * è¯¦ç»†æµç¨‹ï¼š
 * 1. ä¿å­˜é˜µè¥æ ‡ç­¾
 * 2. åˆå§‹åŒ–å±æ€§ï¼ˆåœ¨ç»‘å®šå§”æ‰˜ä¹‹å‰ï¼‰
 * 3. ç»‘å®šå±æ€§å˜åŒ–å§”æ‰˜
 * æ³¨æ„äº‹é¡¹ï¼š
 * - ğŸ”§ MODIFIED - å…ˆåˆå§‹åŒ–å±æ€§ï¼Œå†ç»‘å®šå§”æ‰˜ï¼Œé¿å…è§¦å‘è¯¯åˆ¤
 */
void ASG_UnitsBase::InitializeCharacter(
	FGameplayTag InFactionTag,
	float HealthMultiplier,
	float DamageMultiplier,
	float SpeedMultiplier)
{
	// è®°å½•åˆå§‹åŒ–å¼€å§‹
	UE_LOG(LogSGGameplay, Log, TEXT("========== åˆå§‹åŒ–è§’è‰²ï¼š%s =========="), *GetName());
    
	// è®¾ç½®é˜µè¥æ ‡ç­¾
	FactionTag = InFactionTag;
	UE_LOG(LogSGGameplay, Log, TEXT("  é˜µè¥ï¼š%s"), *FactionTag.ToString());
    
	// ğŸ”§ MODIFIED - å…ˆåˆå§‹åŒ–å±æ€§
	InitializeAttributes(HealthMultiplier, DamageMultiplier, SpeedMultiplier);
    
	// ğŸ”§ MODIFIED - å†ç»‘å®šå§”æ‰˜ï¼ˆæ­¤æ—¶å±æ€§å·²ç»æ˜¯æ­£ç¡®å€¼ï¼‰
	BindAttributeDelegates();
    
	// è®°å½•åˆå§‹åŒ–å®Œæˆ
	UE_LOG(LogSGGameplay, Log, TEXT("âœ“ è§’è‰²åˆå§‹åŒ–å®Œæˆ"));
	UE_LOG(LogSGGameplay, Log, TEXT("========================================"));
}

// åˆå§‹åŒ–å±æ€§
void ASG_UnitsBase::InitializeAttributes(float HealthMult, float DamageMult, float SpeedMult)
{
	// æ£€æŸ¥ AttributeSet æ˜¯å¦æœ‰æ•ˆ
	if (!AttributeSet)
	{
		UE_LOG(LogTemp, Error, TEXT("âœ— AttributeSet ä¸ºç©ºï¼Œæ— æ³•åˆå§‹åŒ–å±æ€§ï¼"));
		return;
	}

	// è®¡ç®—æœ€ç»ˆå±æ€§å€¼
	float FinalMaxHealth = BaseHealth * HealthMult;
	float FinalDamage = BaseAttackDamage * DamageMult;
	float FinalMoveSpeed = BaseMoveSpeed * SpeedMult;
	float FinalAttackSpeed = BaseAttackSpeed * SpeedMult;
	UE_LOG(LogTemp, Log, TEXT("============AttributeSetåˆå§‹åŒ–å±æ€§å¼€å§‹============"));
	UE_LOG(LogTemp, Log, TEXT("  æœ€å¤§ç”Ÿå‘½å€¼ï¼š%.0f (åŸºç¡€: %.0f, å€ç‡: %.2f)"), FinalMaxHealth, BaseHealth, HealthMult);
	UE_LOG(LogTemp, Log, TEXT("  æ”»å‡»åŠ›ï¼š%.0f (åŸºç¡€: %.0f, å€ç‡: %.2f)"), FinalDamage, BaseAttackDamage, DamageMult);
	UE_LOG(LogTemp, Log, TEXT("  ç§»åŠ¨é€Ÿåº¦ï¼š%.0f (åŸºç¡€: %.0f, å€ç‡: %.2f)"), FinalMoveSpeed, BaseMoveSpeed, SpeedMult);
	UE_LOG(LogTemp, Log, TEXT("  æ”»å‡»é€Ÿåº¦ï¼š%.2f (åŸºç¡€: %.2f, å€ç‡: %.2f)"), FinalAttackSpeed, BaseAttackSpeed, SpeedMult);

	// è®¾ç½®å±æ€§å€¼
	// æ³¨æ„ï¼šç›´æ¥è®¾ç½®å±æ€§å€¼ï¼Œä¸ä½¿ç”¨ GameplayEffectï¼ˆç®€åŒ–ç‰ˆæœ¬ï¼‰	
	AttributeSet->SetMaxHealth(FinalMaxHealth);
	AttributeSet->SetHealth(FinalMaxHealth); // åˆå§‹æ»¡è¡€
	AttributeSet->SetAttackDamage(FinalDamage);
	AttributeSet->SetMoveSpeed(FinalMoveSpeed);
	AttributeSet->SetAttackSpeed(FinalAttackSpeed);
	AttributeSet->SetAttackRange(BaseAttackRange);
	// åŒæ­¥ç§»åŠ¨é€Ÿåº¦åˆ° CharacterMovement ç»„ä»¶
	if (UCharacterMovementComponent* MoveComp = GetCharacterMovement())
	{
		MoveComp->MaxWalkSpeed = FinalMoveSpeed;
		UE_LOG(LogTemp, Verbose, TEXT("  âœ“ åŒæ­¥ç§»åŠ¨é€Ÿåº¦åˆ° CharacterMovement"));
	}
	UE_LOG(LogTemp, Log, TEXT("============AttributeSetåˆå§‹åŒ–å±æ€§ç»“æŸ============"));
}

// ç»‘å®šå±æ€§å˜åŒ–å§”æ‰˜
void ASG_UnitsBase::BindAttributeDelegates()
{
	// æ£€æŸ¥ ASC å’Œ AttributeSet æ˜¯å¦æœ‰æ•ˆ
	if (!AbilitySystemComponent || !AttributeSet)
	{
		UE_LOG(LogTemp, Warning, TEXT("âš ï¸ æ— æ³•ç»‘å®šå±æ€§å§”æ‰˜ï¼šASC æˆ– AttributeSet ä¸ºç©º"));
		return;
	}

	// ç›‘å¬ç”Ÿå‘½å€¼å˜åŒ–
	// GetGameplayAttributeValueChangeDelegate è¿”å›ä¸€ä¸ªå§”æ‰˜ï¼Œå½“å±æ€§å˜åŒ–æ—¶è§¦å‘
	AbilitySystemComponent->GetGameplayAttributeValueChangeDelegate(AttributeSet->GetHealthAttribute())
		.AddUObject(this, &ASG_UnitsBase::OnHealthChanged);
	
	UE_LOG(LogTemp, Verbose, TEXT("âœ“ å·²ç»‘å®šç”Ÿå‘½å€¼å˜åŒ–å§”æ‰˜"));
}

/**
 * @brief ç”Ÿå‘½å€¼å˜åŒ–å›è°ƒ
 * @param Data å±æ€§å˜åŒ–æ•°æ®
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - ç›‘å¬ç”Ÿå‘½å€¼å˜åŒ–
 * - æ£€æµ‹å•ä½æ­»äº¡
 * è¯¦ç»†æµç¨‹ï¼š
 * 1. è·å–æ–°æ—§ç”Ÿå‘½å€¼
 * 2. è¾“å‡ºæ—¥å¿—
 * 3. æ£€æµ‹æ­»äº¡æ¡ä»¶
 * æ³¨æ„äº‹é¡¹ï¼š
 * - ğŸ”§ MODIFIED - å¢åŠ åˆå§‹åŒ–æ£€æµ‹ï¼Œé¿å…è¯¯åˆ¤
 */
void ASG_UnitsBase::OnHealthChanged(const FOnAttributeChangeData& Data)
{
	// ğŸ”§ MODIFIED - å¦‚æœå·²ç»æ­»äº¡ï¼Œç›´æ¥è¿”å›
	if (bIsDead)
	{
		return;
	}
	// è·å–æ–°çš„ç”Ÿå‘½å€¼
	float NewHealth = Data.NewValue;
	// è·å–æœ€å¤§ç”Ÿå‘½å€¼
	float MaxHealth = AttributeSet->GetMaxHealth();
    
	// è¾“å‡ºç”Ÿå‘½å€¼å˜åŒ–æ—¥å¿—
	UE_LOG(LogSGGameplay, Verbose, TEXT("%s ç”Ÿå‘½å€¼å˜åŒ–ï¼š%.0f / %.0f (æ—§å€¼: %.0f)"), 
		*GetName(), NewHealth, MaxHealth, Data.OldValue);

	// ğŸ”§ MODIFIED - å¢å¼ºæ­»äº¡åˆ¤æ–­
	// æ¡ä»¶1ï¼šæ–°ç”Ÿå‘½å€¼ <= 0
	// æ¡ä»¶2ï¼šæ—§ç”Ÿå‘½å€¼ > 0ï¼ˆé¿å…åˆå§‹åŒ–æ—¶è¯¯åˆ¤ï¼‰
	// æ¡ä»¶3ï¼šæœ€å¤§ç”Ÿå‘½å€¼ > 0ï¼ˆç¡®ä¿å·²åˆå§‹åŒ–ï¼‰
	// æ¡ä»¶4ï¼šä¸æ˜¯ä» 0 å˜ä¸ºæ»¡è¡€ï¼ˆåˆå§‹åŒ–æƒ…å†µï¼‰
	bool bIsDeath = (NewHealth <= 0.0f) && 
					(Data.OldValue > 0.0f) && 
					(MaxHealth > 0.0f) &&
					!(Data.OldValue == 0.0f && NewHealth == MaxHealth);
    
	// æ£€æµ‹æ­»äº¡
	if (bIsDeath)
	{
		// è¾“å‡ºæ­»äº¡æ—¥å¿—
		UE_LOG(LogSGGameplay, Warning, TEXT("âœ— %s æ­»äº¡"), *GetName());
		// è°ƒç”¨æ­»äº¡å¤„ç†
		OnDeath();
	}
}

// æ­»äº¡å¤„ç†
void ASG_UnitsBase::OnDeath_Implementation()
{
	// ğŸ”§ MODIFIED - è®¾ç½®æ­»äº¡æ ‡è®°
	bIsDead = true;
	
	// âœ¨ æ–°å¢ - å¹¿æ’­æ­»äº¡äº‹ä»¶ï¼ˆåœ¨æœ€å¼€å§‹ï¼‰
	UE_LOG(LogSGGameplay, Log, TEXT("ğŸ“¢ å¹¿æ’­å•ä½æ­»äº¡äº‹ä»¶ï¼š%s"), *GetName());
	OnUnitDeathEvent.Broadcast(this);
	
	// è¾“å‡ºæ­»äº¡æ—¥å¿—
	UE_LOG(LogSGGameplay, Log, TEXT("========== %s æ‰§è¡Œæ­»äº¡é€»è¾‘ =========="), *GetName());
    
	// ç¦ç”¨ç¢°æ’
	if (UCapsuleComponent* Capsule = GetCapsuleComponent())
	{
		// ç¦ç”¨ç¢°æ’
		Capsule->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		// è¾“å‡ºæ—¥å¿—
		UE_LOG(LogSGGameplay, Verbose, TEXT("  âœ“ ç¦ç”¨ç¢°æ’"));
	}

	// ç¦ç”¨è¾“å…¥ï¼ˆå¦‚æœæ˜¯ç©å®¶æ§åˆ¶ï¼‰
	if (AController* Ctrl = GetController())
	{
		// ç¦ç”¨è¾“å…¥
		DisableInput(Cast<APlayerController>(Ctrl));
		// è¾“å‡ºæ—¥å¿—
		UE_LOG(LogSGGameplay, Verbose, TEXT("  âœ“ ç¦ç”¨è¾“å…¥"));
	}

	// TODO: æ’­æ”¾æ­»äº¡åŠ¨ç”»
	// TODO: æ’­æ”¾æ­»äº¡éŸ³æ•ˆ
	// TODO: ç”Ÿæˆæ‰è½ç‰©

	// å»¶è¿Ÿé”€æ¯ï¼ˆç»™åŠ¨ç”»æ’­æ”¾æ—¶é—´ï¼‰
	SetLifeSpan(5.0f);
	// è¾“å‡ºæ—¥å¿—
	UE_LOG(LogSGGameplay, Log, TEXT("  å°†åœ¨ 5 ç§’åé”€æ¯"));
}

// æŸ¥æ‰¾æœ€è¿‘çš„ç›®æ ‡
AActor* ASG_UnitsBase::FindNearestTarget()
{
	// è·å–æ‰€æœ‰è§’è‰²
	TArray<AActor*> AllCharacters;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), ASG_UnitsBase::StaticClass(), AllCharacters);

	AActor* NearestEnemy = nullptr;
	float MinDistance = FLT_MAX; // æœ€å¤§æµ®ç‚¹æ•°

	// éå†æ‰€æœ‰è§’è‰²
	for (AActor* Actor : AllCharacters)
	{
		// æ’é™¤è‡ªå·±
		if (Actor == this)
		{
			continue;
		}

		// è½¬æ¢ä¸ºè§’è‰²ç±»å‹
		ASG_UnitsBase* OtherCharacter = Cast<ASG_UnitsBase>(Actor);
		if (!OtherCharacter)
		{
			continue;
		}

		// æ£€æŸ¥é˜µè¥ï¼ˆä¸åŒé˜µè¥æ‰æ˜¯æ•Œäººï¼‰
		if (OtherCharacter->FactionTag != this->FactionTag)
		{
			// è®¡ç®—è·ç¦»
			float Distance = FVector::Dist(GetActorLocation(), OtherCharacter->GetActorLocation());
			
			// æ›´æ–°æœ€è¿‘æ•Œäºº
			if (Distance < MinDistance)
			{
				MinDistance = Distance;
				NearestEnemy = OtherCharacter;
			}
		}
	}

	// å¦‚æœæ‰¾åˆ°æ•Œäººï¼Œè¿”å›
	if (NearestEnemy)
	{
		UE_LOG(LogTemp, Verbose, TEXT("%s æ‰¾åˆ°æœ€è¿‘çš„æ•Œäººï¼š%s (è·ç¦»: %.0f)"), 
			*GetName(), *NearestEnemy->GetName(), MinDistance);
		return NearestEnemy;
	}

	// å¦‚æœæ²¡æœ‰æ•Œäººï¼ŒæŸ¥æ‰¾æ•Œæ–¹ä¸»åŸ
	// TODO: å®ç°æŸ¥æ‰¾ä¸»åŸé€»è¾‘
	UE_LOG(LogTemp, Verbose, TEXT("%s æœªæ‰¾åˆ°æ•Œäººï¼Œå°è¯•æŸ¥æ‰¾æ•Œæ–¹ä¸»åŸ"), *GetName());
	
	return nullptr;
}

// è®¾ç½®ç›®æ ‡
void ASG_UnitsBase::SetTarget(AActor* NewTarget)
{
	if (NewTarget != CurrentTarget)
	{
		CurrentTarget = NewTarget;
		
		if (CurrentTarget)
		{
			UE_LOG(LogTemp, Log, TEXT("%s åˆ‡æ¢ç›®æ ‡ï¼š%s"), *GetName(), *CurrentTarget->GetName());
		}
		else
		{
			UE_LOG(LogTemp, Log, TEXT("%s æ¸…ç©ºç›®æ ‡"), *GetName());
		}
	}
}

// ========== âœ¨ æ–°å¢ - DataTable ç›¸å…³å‡½æ•°å®ç° ==========

/**
 * @brief ä» DataTable åŠ è½½å•ä½é…ç½®
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - ä» DataTable è¯»å–æŒ‡å®šè¡Œçš„æ•°æ®
 * - åº”ç”¨å±æ€§åˆ° BaseHealthã€BaseAttackDamage ç­‰
 * - åº”ç”¨æ”»å‡»é…ç½®ï¼ˆæ”»å‡»åŠ¨ç”»ã€æŠ•å°„ç‰©ç±»ç­‰ï¼‰
 * è¯¦ç»†æµç¨‹ï¼š
 * 1. æ£€æŸ¥ DataTable å’Œè¡Œåç§°æ˜¯å¦æœ‰æ•ˆ
 * 2. ä» DataTable æŸ¥æ‰¾æŒ‡å®šè¡Œ
 * 3. è¯»å–å±æ€§å€¼å¹¶è¦†ç›–åŸºç¡€å±æ€§
 * 4. è¯»å–æ”»å‡»é…ç½®
 * æ³¨æ„äº‹é¡¹ï¼š
 * - åœ¨ InitializeCharacter() ä¹‹å‰è°ƒç”¨
 * - å¦‚æœ bUseDataTable = falseï¼Œä¸ä¼šæ‰§è¡Œ
 */
void ASG_UnitsBase::LoadUnitDataFromTable()
{
	// ========== æ­¥éª¤1ï¼šæ£€æŸ¥æœ‰æ•ˆæ€§ ==========
	// æ£€æŸ¥ DataTable æ˜¯å¦æœ‰æ•ˆ
	if (!UnitDataTable)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("âœ— %s: UnitDataTable ä¸ºç©ºï¼"), *GetName());
		return;
	}
	
	// æ£€æŸ¥è¡Œåç§°æ˜¯å¦æœ‰æ•ˆ
	if (UnitDataRowName.IsNone())
	{
		UE_LOG(LogSGGameplay, Error, TEXT("âœ— %s: UnitDataRowName ä¸ºç©ºï¼"), *GetName());
		return;
	}
	
	// ========== æ­¥éª¤2ï¼šæŸ¥æ‰¾ DataTable è¡Œ ==========
	// ä» DataTable æŸ¥æ‰¾æŒ‡å®šè¡Œ
	// FindRow æ˜¯ UDataTable çš„æ¨¡æ¿å‡½æ•°ï¼Œè¿”å›æŒ‡å®šè¡Œçš„æ•°æ®æŒ‡é’ˆ
	FSGUnitDataRow* RowData = UnitDataTable->FindRow<FSGUnitDataRow>(
		UnitDataRowName,
		TEXT("LoadUnitDataFromTable")  // ç”¨äºé”™è¯¯æ—¥å¿—çš„ä¸Šä¸‹æ–‡
	);
	
	// æ£€æŸ¥æ˜¯å¦æ‰¾åˆ°æ•°æ®
	if (!RowData)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("âœ— %s: åœ¨ DataTable ä¸­æ‰¾ä¸åˆ°è¡Œ '%s'ï¼"), 
			*GetName(), *UnitDataRowName.ToString());
		return;
	}
	
	// è¾“å‡ºæ—¥å¿—
	UE_LOG(LogSGGameplay, Log, TEXT("========== ä» DataTable åŠ è½½å•ä½é…ç½® =========="));
	UE_LOG(LogSGGameplay, Log, TEXT("  å•ä½ï¼š%s"), *GetName());
	UE_LOG(LogSGGameplay, Log, TEXT("  æ•°æ®è¡Œï¼š%s"), *UnitDataRowName.ToString());
	UE_LOG(LogSGGameplay, Log, TEXT("  å•ä½åç§°ï¼š%s"), *RowData->UnitName.ToString());
	
	// ========== æ­¥éª¤3ï¼šåº”ç”¨å±æ€§å€¼ ==========
	// ä» DataTable è¯»å–çš„å€¼ä¼šè¦†ç›– Blueprint ä¸­è®¾ç½®çš„ Base å€¼
	BaseHealth = RowData->BaseHealth;
	BaseAttackDamage = RowData->BaseAttackDamage;
	BaseMoveSpeed = RowData->BaseMoveSpeed;
	BaseAttackSpeed = RowData->BaseAttackSpeed;
	BaseAttackRange = RowData->BaseAttackRange;
	
	// è¾“å‡ºæ—¥å¿—
	UE_LOG(LogSGGameplay, Log, TEXT("  å±æ€§é…ç½®ï¼š"));
	UE_LOG(LogSGGameplay, Log, TEXT("    ç”Ÿå‘½å€¼ï¼š%.0f"), BaseHealth);
	UE_LOG(LogSGGameplay, Log, TEXT("    æ”»å‡»åŠ›ï¼š%.0f"), BaseAttackDamage);
	UE_LOG(LogSGGameplay, Log, TEXT("    ç§»åŠ¨é€Ÿåº¦ï¼š%.0f"), BaseMoveSpeed);
	UE_LOG(LogSGGameplay, Log, TEXT("    æ”»å‡»é€Ÿåº¦ï¼š%.2f"), BaseAttackSpeed);
	UE_LOG(LogSGGameplay, Log, TEXT("    æ”»å‡»èŒƒå›´ï¼š%.0f"), BaseAttackRange);
	
	// ========== æ­¥éª¤4ï¼šåº”ç”¨æ”»å‡»é…ç½® ==========
	// åº”ç”¨å•ä½ç±»å‹æ ‡ç­¾
	if (RowData->UnitTypeTag.IsValid())
	{
		UnitTypeTag = RowData->UnitTypeTag;
		UE_LOG(LogSGGameplay, Log, TEXT("  å•ä½ç±»å‹ï¼š%s"), *UnitTypeTag.ToString());
	}
	
	// åº”ç”¨æ”»å‡»åŠ¨ç”»
	if (RowData->AttackMontage)
	{
		AttackMontage = RowData->AttackMontage;
		UE_LOG(LogSGGameplay, Log, TEXT("  æ”»å‡»åŠ¨ç”»ï¼š%s"), *AttackMontage->GetName());
	}
	
	// åº”ç”¨æŠ•å°„ç‰©ç±»ï¼ˆä»…è¿œç¨‹å•ä½ï¼‰
	if (RowData->AttackType != ESGUnitAttackType::Melee && RowData->ProjectileClass)
	{
		ProjectileClass = RowData->ProjectileClass;
		UE_LOG(LogSGGameplay, Log, TEXT("  æŠ•å°„ç‰©ç±»ï¼š%s"), *ProjectileClass->GetName());
	}
	
	// è¾“å‡ºæ—¥å¿—
	UE_LOG(LogSGGameplay, Log, TEXT("âœ“ å•ä½é…ç½®åŠ è½½å®Œæˆ"));
	UE_LOG(LogSGGameplay, Log, TEXT("==============================================="));
}

// ========== âœ¨ æ–°å¢ - æ”»å‡»ç³»ç»Ÿå‡½æ•°å®ç° ==========

/**
 * @brief æˆäºˆæ”»å‡»èƒ½åŠ›
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - æ ¹æ®å•ä½ç±»å‹æˆäºˆå¯¹åº”çš„æ”»å‡» Gameplay Ability
 * - è¿‘æˆ˜å•ä½ä½¿ç”¨ GA_Attack_Melee
 * - è¿œç¨‹å•ä½ä½¿ç”¨ GA_Attack_Ranged
 * è¯¦ç»†æµç¨‹ï¼š
 * 1. æ£€æŸ¥ ASC æ˜¯å¦æœ‰æ•ˆ
 * 2. æ ¹æ® UnitTypeTag ç¡®å®šæ”»å‡»ç±»å‹
 * 3. åˆ›å»º Ability Spec å¹¶æˆäºˆèƒ½åŠ›
 * 4. ç¼“å­˜ Ability Handle ä¾›åç»­ä½¿ç”¨
 * æ³¨æ„äº‹é¡¹ï¼š
 * - åœ¨ BeginPlay ä¸­è‡ªåŠ¨è°ƒç”¨
 * - éœ€è¦å…ˆé…ç½® UnitTypeTag
 */
void ASG_UnitsBase::GrantAttackAbility()
{
	// ========== æ­¥éª¤1ï¼šæ£€æŸ¥ ASC æ˜¯å¦æœ‰æ•ˆ ==========
	if (!AbilitySystemComponent)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("âœ— %s: AbilitySystemComponent ä¸ºç©ºï¼Œæ— æ³•æˆäºˆæ”»å‡»èƒ½åŠ›ï¼"), *GetName());
		return;
	}
	
	// ========== æ­¥éª¤2ï¼šç¡®å®šæ”»å‡»èƒ½åŠ›ç±» ==========
	// âœ¨ æ–°å¢ - æ”¯æŒå¤šç§æ–¹å¼é…ç½®æ”»å‡»èƒ½åŠ›ç±»
	// ä¼˜å…ˆçº§ï¼š
	// 1. AttackAbilityClassï¼ˆBlueprint ä¸­ç›´æ¥é…ç½®ï¼‰
	// 2. æ ¹æ® UnitTypeTag è‡ªåŠ¨é€‰æ‹©ï¼ˆé»˜è®¤è¡Œä¸ºï¼‰
	TSubclassOf<UGameplayAbility> AbilityClassToGrant = AttackAbilityClass;
	
	// å¦‚æœæ²¡æœ‰åœ¨ Blueprint ä¸­é…ç½®ï¼Œåˆ™æ ¹æ®å•ä½ç±»å‹è‡ªåŠ¨é€‰æ‹©
	if (!AbilityClassToGrant)
	{
		UE_LOG(LogSGGameplay, Log, TEXT("  %s: æœªé…ç½® AttackAbilityClassï¼Œæ ¹æ® UnitTypeTag è‡ªåŠ¨é€‰æ‹©"), *GetName());
		
		// ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨å¯é€‰çš„ GameplayTagï¼ˆé¿å…æœªé…ç½®æ—¶æŠ¥é”™ï¼‰
		FGameplayTag InfantryTag = FGameplayTag::RequestGameplayTag(FName("Unit.Type.Infantry"), false);
		FGameplayTag CavalryTag = FGameplayTag::RequestGameplayTag(FName("Unit.Type.Cavalry"), false);
		FGameplayTag ArcherTag = FGameplayTag::RequestGameplayTag(FName("Unit.Type.Archer"), false);
		FGameplayTag CrossbowTag = FGameplayTag::RequestGameplayTag(FName("Unit.Type.Crossbow"), false);
		
		if ((InfantryTag.IsValid() && UnitTypeTag.MatchesTag(InfantryTag)) ||
			(CavalryTag.IsValid() && UnitTypeTag.MatchesTag(CavalryTag)))
		{
			// è¿‘æˆ˜å•ä½ - å°è¯•åŠ è½½é»˜è®¤è¿‘æˆ˜æ”»å‡»èƒ½åŠ›
			UE_LOG(LogSGGameplay, Log, TEXT("  %s ä¸ºè¿‘æˆ˜å•ä½ï¼Œå°è¯•åŠ è½½é»˜è®¤ GA_Attack_Melee"), *GetName());
			
			AbilityClassToGrant = LoadClass<UGameplayAbility>(
				nullptr,
				TEXT("/Game/Blueprints/GAS/Abilities/GA_Attack_Melee.GA_Attack_Melee_C")
			);
			
			if (!AbilityClassToGrant)
			{
				UE_LOG(LogSGGameplay, Warning, TEXT("âš ï¸ %s: é»˜è®¤ GA_Attack_Melee ä¸å­˜åœ¨ï¼Œè¯·åœ¨ Blueprint ä¸­æ‰‹åŠ¨é…ç½® AttackAbilityClass"), *GetName());
			}
		}
		else if ((ArcherTag.IsValid() && UnitTypeTag.MatchesTag(ArcherTag)) ||
				 (CrossbowTag.IsValid() && UnitTypeTag.MatchesTag(CrossbowTag)))
		{
			// è¿œç¨‹å•ä½ - å°è¯•åŠ è½½é»˜è®¤è¿œç¨‹æ”»å‡»èƒ½åŠ›
			UE_LOG(LogSGGameplay, Log, TEXT("  %s ä¸ºè¿œç¨‹å•ä½ï¼Œå°è¯•åŠ è½½é»˜è®¤ GA_Attack_Ranged"), *GetName());
			
			AbilityClassToGrant = LoadClass<UGameplayAbility>(
				nullptr,
				TEXT("/Game/Blueprints/GAS/Abilities/GA_Attack_Ranged.GA_Attack_Ranged_C")
			);
			
			if (!AbilityClassToGrant)
			{
				UE_LOG(LogSGGameplay, Warning, TEXT("âš ï¸ %s: é»˜è®¤ GA_Attack_Ranged ä¸å­˜åœ¨ï¼Œè¯·åœ¨ Blueprint ä¸­æ‰‹åŠ¨é…ç½® AttackAbilityClass"), *GetName());
			}
		}
		else
		{
			UE_LOG(LogSGGameplay, Warning, TEXT("âš ï¸ %s: æœªçŸ¥çš„å•ä½ç±»å‹ '%s'ï¼Œä¸”æœªé…ç½® AttackAbilityClass"), 
				*GetName(), *UnitTypeTag.ToString());
		}
	}
	else
	{
		// ä½¿ç”¨ Blueprint ä¸­é…ç½®çš„æ”»å‡»èƒ½åŠ›ç±»
		UE_LOG(LogSGGameplay, Log, TEXT("  %s: ä½¿ç”¨ Blueprint é…ç½®çš„ AttackAbilityClass: %s"), 
			*GetName(), *AbilityClassToGrant->GetName());
	}
	
	// ========== æ­¥éª¤3ï¼šæˆäºˆèƒ½åŠ› ==========
	if (AbilityClassToGrant)
	{
		// åˆ›å»º Ability Spec
		FGameplayAbilitySpec AbilitySpec(
			AbilityClassToGrant,  // èƒ½åŠ›ç±»
			1,                    // èƒ½åŠ›ç­‰çº§
			INDEX_NONE,           // è¾“å…¥IDï¼ˆä¸ä½¿ç”¨è¾“å…¥ç»‘å®šï¼‰
			this                  // èƒ½åŠ›çš„ Source Object
		);
		
		// æˆäºˆèƒ½åŠ›å¹¶ç¼“å­˜ Handle
		GrantedAttackAbilityHandle = AbilitySystemComponent->GiveAbility(AbilitySpec);
		
		// è¾“å‡ºæ—¥å¿—
		UE_LOG(LogSGGameplay, Log, TEXT("âœ“ %s: æˆäºˆæ”»å‡»èƒ½åŠ›æˆåŠŸ (ç±»: %s, Handle: %s)"), 
			*GetName(), *AbilityClassToGrant->GetName(), *GrantedAttackAbilityHandle.ToString());
	}
	else
	{
		UE_LOG(LogSGGameplay, Warning, TEXT("âš ï¸ %s: æ— æ³•ç¡®å®šæ”»å‡»èƒ½åŠ›ç±»ï¼Œè·³è¿‡æˆäºˆ"), *GetName());
		UE_LOG(LogSGGameplay, Warning, TEXT("  æç¤ºï¼šè¯·åœ¨å•ä½ Blueprint ä¸­é…ç½® 'Attack Config â†’ æ”»å‡»èƒ½åŠ›ç±»'"));
	}
}

/**
 * @brief æ‰§è¡Œæ”»å‡»
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - è§¦å‘å·²æˆäºˆçš„æ”»å‡»èƒ½åŠ›
 * - ä¾› AI æˆ–ç©å®¶è¾“å…¥è°ƒç”¨
 * è¯¦ç»†æµç¨‹ï¼š
 * 1. æ£€æŸ¥ ASC å’Œæ”»å‡»èƒ½åŠ›æ˜¯å¦æœ‰æ•ˆ
 * 2. æ£€æŸ¥èƒ½åŠ›æ˜¯å¦å¯ä»¥æ¿€æ´»ï¼ˆå†·å´ã€æˆæœ¬ç­‰ï¼‰
 * 3. æ¿€æ´»æ”»å‡»èƒ½åŠ›
 * æ³¨æ„äº‹é¡¹ï¼š
 * - åœ¨ StateTree AI ä¸­è°ƒç”¨
 * - éœ€è¦å…ˆè°ƒç”¨ GrantAttackAbility()
 * @return æ˜¯å¦æˆåŠŸè§¦å‘æ”»å‡»
 */
bool ASG_UnitsBase::PerformAttack()
{
	// ========== æ­¥éª¤1ï¼šæ£€æŸ¥ ASC æ˜¯å¦æœ‰æ•ˆ ==========
	if (!AbilitySystemComponent)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("âœ— %s: AbilitySystemComponent ä¸ºç©ºï¼Œæ— æ³•æ‰§è¡Œæ”»å‡»ï¼"), *GetName());
		return false;
	}
	
	// ========== æ­¥éª¤2ï¼šæ£€æŸ¥æ”»å‡»èƒ½åŠ›æ˜¯å¦å·²æˆäºˆ ==========
	if (!GrantedAttackAbilityHandle.IsValid())
	{
		UE_LOG(LogSGGameplay, Warning, TEXT("âš ï¸ %s: æ”»å‡»èƒ½åŠ›æœªæˆäºˆï¼Œæ— æ³•æ‰§è¡Œæ”»å‡»ï¼"), *GetName());
		return false;
	}
	
	// ========== æ­¥éª¤3ï¼šæ£€æŸ¥èƒ½åŠ›æ˜¯å¦å¯ä»¥æ¿€æ´» ==========
	// FindAbilitySpecFromHandle æŸ¥æ‰¾èƒ½åŠ›è§„æ ¼
	FGameplayAbilitySpec* AbilitySpec = AbilitySystemComponent->FindAbilitySpecFromHandle(GrantedAttackAbilityHandle);
	if (!AbilitySpec)
	{
		UE_LOG(LogSGGameplay, Error, TEXT("âœ— %s: æ‰¾ä¸åˆ°æ”»å‡»èƒ½åŠ› Specï¼"), *GetName());
		return false;
	}
	
	// æ£€æŸ¥èƒ½åŠ›æ˜¯å¦å¯ä»¥æ¿€æ´»ï¼ˆæ£€æŸ¥å†·å´ã€æˆæœ¬ã€Tag é™åˆ¶ç­‰ï¼‰
	if (!AbilitySpec->Ability->CanActivateAbility(
		GrantedAttackAbilityHandle,
		AbilitySystemComponent->AbilityActorInfo.Get()))
	{
		UE_LOG(LogSGGameplay, Verbose, TEXT("âš ï¸ %s: æ”»å‡»èƒ½åŠ›æ— æ³•æ¿€æ´»ï¼ˆå¯èƒ½åœ¨å†·å´ä¸­ï¼‰"), *GetName());
		return false;
	}
	
	// ========== æ­¥éª¤4ï¼šæ¿€æ´»æ”»å‡»èƒ½åŠ› ==========
	// TryActivateAbility å°è¯•æ¿€æ´»èƒ½åŠ›
	bool bSuccess = AbilitySystemComponent->TryActivateAbility(GrantedAttackAbilityHandle);
	
	// è¾“å‡ºæ—¥å¿—
	if (bSuccess)
	{
		UE_LOG(LogSGGameplay, Verbose, TEXT("âœ“ %s: è§¦å‘æ”»å‡»"), *GetName());
	}
	else
	{
		UE_LOG(LogSGGameplay, Warning, TEXT("âš ï¸ %s: è§¦å‘æ”»å‡»å¤±è´¥"), *GetName());
	}
	
	return bSuccess;
}

/**
 * @brief æ£€æŸ¥å½“å‰ç›®æ ‡æ˜¯å¦æœ‰æ•ˆ
 * @details
 * åŠŸèƒ½è¯´æ˜ï¼š
 * - æ£€æŸ¥ç›®æ ‡æ˜¯å¦å­˜åœ¨ã€æ˜¯å¦å­˜æ´»ã€æ˜¯å¦åœ¨èŒƒå›´å†…
 * è¯¦ç»†æµç¨‹ï¼š
 * 1. æ£€æŸ¥ CurrentTarget æ˜¯å¦ä¸ºç©º
 * 2. æ£€æŸ¥ç›®æ ‡æ˜¯å¦å·²æ­»äº¡
 * 3. æ£€æŸ¥ç›®æ ‡æ˜¯å¦ä»åœ¨æ”»å‡»èŒƒå›´å†…
 * æ³¨æ„äº‹é¡¹ï¼š
 * - åœ¨ AI ä¸­æ¯å¸§æ£€æŸ¥
 * - å¦‚æœæ— æ•ˆï¼Œéœ€è¦é‡æ–°æŸ¥æ‰¾ç›®æ ‡
 * @return ç›®æ ‡æ˜¯å¦æœ‰æ•ˆ
 */
bool ASG_UnitsBase::IsTargetValid() const
{
	// ========== æ­¥éª¤1ï¼šæ£€æŸ¥ç›®æ ‡æ˜¯å¦ä¸ºç©º ==========
	if (!CurrentTarget)
	{
		return false;
	}
	
	// ========== æ­¥éª¤2ï¼šæ£€æŸ¥ç›®æ ‡æ˜¯å¦å·²æ­»äº¡ ==========
	// å°è¯•è½¬æ¢ä¸º ASG_UnitsBase
	const ASG_UnitsBase* TargetUnit = Cast<ASG_UnitsBase>(CurrentTarget);
	if (TargetUnit)
	{
		// å¦‚æœç›®æ ‡å·²æ­»äº¡ï¼Œè¿”å› false
		if (TargetUnit->bIsDead)
		{
			return false;
		}
		
		// å¦‚æœç›®æ ‡ç”Ÿå‘½å€¼ <= 0ï¼Œè¿”å› false
		if (TargetUnit->AttributeSet && TargetUnit->AttributeSet->GetHealth() <= 0.0f)
		{
			return false;
		}
	}
	
	// ========== æ­¥éª¤3ï¼šæ£€æŸ¥ç›®æ ‡æ˜¯å¦åœ¨æ”»å‡»èŒƒå›´å†… ==========
	// è®¡ç®—ä¸ç›®æ ‡çš„è·ç¦»
	float DistanceToTarget = FVector::Dist(GetActorLocation(), CurrentTarget->GetActorLocation());
	
	// è·å–æ”»å‡»èŒƒå›´ï¼ˆä» AttributeSet è·å–ï¼‰
	float AttackRange = BaseAttackRange;
	if (AttributeSet)
	{
		AttackRange = AttributeSet->GetAttackRange();
	}
	
	// æ·»åŠ ä¸€äº›å®¹å·®ï¼ˆé¿å…è¾¹ç•ŒæŠ–åŠ¨ï¼‰
	float RangeTolerance = 50.0f;
	
	// å¦‚æœè·ç¦»è¶…å‡ºæ”»å‡»èŒƒå›´ + å®¹å·®ï¼Œè¿”å› false
	if (DistanceToTarget > AttackRange + RangeTolerance)
	{
		return false;
	}
	
	// ========== æ‰€æœ‰æ£€æŸ¥é€šè¿‡ï¼Œç›®æ ‡æœ‰æ•ˆ ==========
	return true;
}